### DISCUSSION TITLE
machine template would not allow to add metadata labels

### DISCUSSION THREAD

**Discussion by kotyara85** [kubernetes-sigs/cluster-api#10863] [General]
Hey there,
I have a custom machine template for our infra which looks like this
```
type InfraTemplateSpec struct {
	ObjectMeta metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec       MachineSpec      `json:"spec,omitempty"`
}
```

generated crd:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  name: infratemplate.infrastructure.cluster.x-k8s.io
spec:
  conversion:
    strategy: None
  group: infrastructure.cluster.x-k8s.io
  names:
    kind: InfraTemplate
    listKind: InfraTemplateList
    plural: infratemplate
    singular: InfraTemplate
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: InfraTemplate is the Schema for the infratemplate API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: infratemplatepec defines the desired state of InfraTemplate
            properties:
              template:
                properties:
                  metadata:
                    type: object
                  spec:
                    description: Machin spec
                    properties:
                      providerID:
                        type: string
                    type: object
                type: object
            required:
            - template
            type: object
          status:
            description: infratemplatetatus defines the observed state of InfraTemplate
            type: object
        type: object
    served: true
    storage: true
```

Object I'm trying to apply:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: InfraTemplate
metadata:
  name: controlplane
  namespace: default
spec:
  template:
    metadata:
      labels:
        label1: "test"
        label2: "test"
```

Which results into `strict decoding error: unknown field "spec.template.metadata.labels"`

Any help is appreciated
