### DISCUSSION TITLE
skip-kube-proxy doesn't seem to be working

### DISCUSSION THREAD

**Discussion by kotyara85** [kubernetes-sigs/cluster-api#11005] [General]
Hello everyone,
I'm running into an issue when I can't disable kube-proxy to get provisioned:
CAPI Version: v1.7.3

```
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: ${CLUSTER_NAME}
  namespace: ${NAMESPACE}
  annotations:
    controlplane.cluster.x-k8s.io/skip-kube-proxy: "true"
```

Daemon set is still being deployed with this annotation
