### ISSUE TITLE
Consistent reporting of paused resources

### ISSUE THREAD

**Issue by JoelSpeed** [kubernetes-sigs/cluster-api#10130]
### What would you like to be added (User Story)?

As a user of Cluster API, I would like to see a condition on each resources status that tells me if a resource is paused, so that I know that controllers have seen my pause request and acknowledged it before operate on the resources manually.

### Detailed Description

Kubernetes is a distributed and event driven system, with a tendency for caching. This means that, if I set `spec.paused` on a  resource, the controller for it may be processing an older event from the same resource, and it may take some amount of time before it reconciles the event relating to my change to pause the resource.

Before I make my changes, I want to be sure that the controller has seen my request to pause the resource, so that I am certain that no further changes will be made.

To do this, I think we should make all controllers add a condition that shows whether or not the controller believes they are paused or not.

In the general running case:
```
conditions:
- type: Paused
  status: False
  reason: ResourceNotPaused
  message: "Resource is operating as expected"
```
However, when paused, I want to see
```
conditions:
- type: Paused
  status: True
  reason: ResourcePaused
  message: "Resource has been paused by spec.paused"
```
This will allow integrations with `kubectl wait` to wait for the condition before continuing.

### Anything else you would like to add?

Alternatively, you could set this as a `pausedGeneration` but I feel a condition is more expressive for this use case.

It would be good to define this as part of the contracts so that every CAPI controller eventually sets this in a consistent way.

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
