### ISSUE TITLE
Unbound resource creation within managed topologies

### ISSUE THREAD

**Issue by mnaser** [kubernetes-sigs/cluster-api#10275]
### What steps did you take and what happened?

When using managed topologies, we've ran into an issue where if the user creates a `Cluster` with some invalid value that ends up failing validation down the line, CAPI will keep creating resources non-stop.

For example:

```
status:
  conditions:
  - lastTransitionTime: "2024-02-29T14:07:45Z"
    message: 'error reconciling the Cluster topology: failed to create KubeadmControlPlane.controlplane.cluster.x-k8s.io:
      FieldValueForbidden: spec.kubeadmConfigSpec.format: Forbidden: can be set only
      if the KubeadmBootstrapFormatIgnition feature gate is enabled FieldValueForbidden:
      spec.kubeadmConfigSpec.ignition: Forbidden: can be set only if the KubeadmBootstrapFormatIgnition
      feature gate is enabled'
    reason: TopologyReconcileFailed
    severity: Error
    status: "False"
    type: TopologyReconciled
  observedGeneration: 1
  phase: Pending
```

As it keeps trying again and again, it will keep spawning more `InfrastructureCluster` resources, in my case, got up to ~5k and ~11k at some point.

### What did you expect to happen?

CAPI should try and figure out if there is an existing `InfrastructureCluster` tied to this, if there is, then just re-use that instead of creating it again.

### Cluster API version

1.6.0

### Kubernetes version

1.28

### Anything else you would like to add?

Happy to assist to fixing it if we're pointed where to go.

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
