### ISSUE TITLE
Move fails when in-cluster IPAM is in use 

### ISSUE THREAD

**Issue by peppi-lotta** [kubernetes-sigs/cluster-api#10300]
### What steps did you take and what happened?

I followed the CAPI quick start guide and use Docker as the infrastructure provider. I created two clusters; source and target. These are the commands I use to get the clusters up and running: 
```
sudo sysctl fs.inotify.max_user_watches=1048576
sudo sysctl fs.inotify.max_user_instances=8192

export CLUSTER_TOPOLOGY=true
export EXP_MACHINE_POOL=true
export SERVICE_CIDR=["10.96.0.0/12"]
export POD_CIDR=["192.168.0.0/16"]
export SERVICE_DOMAIN="k8s.test"

cat > kind-cluster-with-extramounts.yaml <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
EOF

kind create cluster --name target --config kind-cluster-with-extramounts.yaml

clusterctl init --infrastructure docker --ipam in-cluster

clusterctl generate cluster capi-quickstart-target --flavor development \
  --kubernetes-version v1.29.0 \
  --control-plane-machine-count=3 \
  --worker-machine-count=3 \
  > capi-quickstart-target.yaml

kubectl apply -f capi-quickstart-target.yaml

kind get kubeconfig --name capi-quickstart-target > capi-quickstart-target.kubeconfig

kubectl --kubeconfig=./capi-quickstart-target.kubeconfig \
  apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml
```
I'm changing the word target to source when I make the source cluster. 

I `apply` these two CRs in the source cluster:
```
apiVersion: ipam.cluster.x-k8s.io/v1alpha2
kind: InClusterIPPool
metadata:
  name: inclusterippool-sample
spec:
  addresses:
    - 10.0.0.0/24
  prefix: 24
  gateway: 10.0.0.1
---
apiVersion: ipam.cluster.x-k8s.io/v1beta1
kind: IPAddressClaim
metadata:
  name: my-ip-address-claim
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
spec:
  poolRef:
    apiGroup: ipam.cluster.x-k8s.io
    kind: InClusterIPPool 
    name: inclusterippool-sample
```
I get the target clusters config:
`kind get kubeconfig --name target > target-kubeconfig.yaml`
and then I make sure that source cluster is set as my current context and I run: 
`clusterctl move --to-kubeconfig target-kubeconfig.yaml `
I get error:
```
Deleting objects from the source cluster
Error: action failed after 10 attempts: error deleting "ipam.cluster.x-k8s.io/v1alpha2, Kind=InClusterIPPool" default/inclusterippool-sample: admission webhook "validation.inclusterippool.ipam.cluster.x-k8s.io" denied the request: Pool has IPAddresses allocated. Cannot delete Pool until all IPAddresses have been removed.
```

### What did you expect to happen?

After move I have all the same pool, claim and address objects in the target cluster as I had in the source cluster. Then the source cluster should be deleted but it can't because it 'Pool has IPAddresses allocated'. Move is not deleting ipaddresses in the source cluster. 

### Cluster API version

v1.6.3

### Kubernetes version

v1.29.2

### Anything else you would like to add?

I would be happy to keep looking into this and fix this bug. 

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by fabriziopandini** [comment]
cc @schrej @rikatz

**Comment by peppi-lotta** [comment]
I'm using the latest version. I followed the instruction in [IPAM README](https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster) 'Setup via clusterctl' and added the snippet below to my ~/.config/cluster-api/clusterctl.yaml.
```
providers:
  - name: in-cluster
    url: https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/releases/latest/ipam-components.yaml
    type: IPAMProvider
```
