### ISSUE TITLE
Conditions do not contain objects GroupVersionKind anymore

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api#10405]
### What steps did you take and what happened?

Aggregated conditions normally contain the GroupVersionKind + object name when bubbling up e.g. from Machines to the MachineSet.

on main this is currently not the case anymore:

Example:

```yaml
  - lastTransitionTime: "2024-04-08T15:51:21Z"
    message: 0 of 1 completed
    reason: WaitingForBootstrapData @ /k8s-upgrade-with-runtimesdk-m0bd5d-md-md-0-652m9-bhqw4-zgw9q
    severity: Info
    status: "False"
    type: MachinesReady
```

source: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/10384/pull-cluster-api-e2e-mink8s-main/1777347731522588672/artifacts/clusters/bootstrap/resources/k8s-upgrade-with-runtimesdk-c42gsm/MachineSet/k8s-upgrade-with-runtimesdk-m0bd5d-md-md-0-652m9-bhqw4.yaml
Prowjob: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/10384/pull-cluster-api-e2e-mink8s-main/1777347731522588672

### What did you expect to happen?

```yaml
  - lastTransitionTime: "2024-04-08T15:51:21Z"
    message: 0 of 1 completed
    reason: WaitingForBootstrapData @ Machine/k8s-upgrade-with-runtimesdk-m0bd5d-md-md-0-652m9-bhqw4-zgw9q
    severity: Info
    status: "False"
    type: MachinesReady
```

### Cluster API version

This branch: https://github.com/kubernetes-sigs/cluster-api/pull/10384

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
