### ISSUE TITLE
kubeadmcontrol plane is never initialized when using kind cluster

### ISSUE THREAD

**Issue by pigaur** [kubernetes-sigs/cluster-api#10468]
### What steps did you take and what happened?

I was trying to create a cluster using Cluster API quick start guide. However, I came across this scenario where when you create the kind cluster using default `kind create cluster`, the cluster control plane is never initialized.

https://cluster-api.sigs.k8s.io/user/quick-start

```
kind create cluster
```

```
kubectl get kubeadmcontrolplane
NAME                     CLUSTER    INITIALIZED   API SERVER AVAILABLE   REPLICAS   READY   UPDATED   UNAVAILABLE   AGE     VERSION
wardaddy-control-plane   wardaddy                                        1                  1         1             2m48s   v1.26.7
```

When I created a kind cluster based on Docker, it works.

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
```

```
kubectl get kubeadmcontrolplane
NAME                     CLUSTER    INITIALIZED   API SERVER AVAILABLE   REPLICAS   READY   UPDATED   UNAVAILABLE   AGE     VERSION
wardaddy-control-plane   wardaddy   true                                 3                  3         3             9m16s   v1.26.7
```

Cloud Provided Platform in use is GCP. 

### What did you expect to happen?

I expect the cluster to be initilized and in ready state once CNI is installed. 

### Cluster API version

`cluster.x-k8s.io/v1beta1`

### Kubernetes version

v1.26.7

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
