### ISSUE TITLE
MachineDeployment rolling update surges and then stops working

### ISSUE THREAD

**Issue by erstaples** [kubernetes-sigs/cluster-api#1049]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Created a `MachineDeployment`:
```
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: nodes
spec:
  replicas: 3
  selector:
    matchLabels:
      set: node
      cluster.k8s.io/cluster-name: foo
  strategy:
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        set: node
        cluster.k8s.io/cluster-name: foo
    spec:
      versions:
        kubelet: v1.13.6
```
I get expected behavior:
* A `MachineSet` is created
* 3 `Machine`s are created
* 3 nodes are created in `foo` cluster

Then I change a value in the `MachineDeployment` `.spec.template.spec.providerSpec` (not included in the snippet above) in order to trigger a rolling update.

This results in the unexpected behavior of 1 new `Machine` created and 3 old `Machine`s remaining in the cluster for a total of 4 `Machine`s. 

**What did you expect to happen:**
Since I have `maxSurge` set to `1`, I expected a cycle of 1 new `Machine` to be created and then 1 old `Machine` to be removed until only 3 new `Machine`s remained.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
2 `MachineSet`s were generated during this process and after running the update the old `MachineSet` has this status:

```
Status:
  Fully Labeled Replicas:  3
  Observed Generation:     3
  Replicas:                3
```

The new `MachineSet` status:
```
Status:
  Fully Labeled Replicas:  1
  Observed Generation:     1
  Replicas:                1
```

**Environment:**

- Cluster-api version: 0.1.1
- Minikube version: v0.32.0
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):
```
NAME=Buildroot
VERSION=2018.05
ID=buildroot
VERSION_ID=2018.05
PRETTY_NAME="Buildroot 2018.05"
```
