### ISSUE TITLE
`Microsoft Entra ID authentication with Kubernetes RBAC` not working though aadprofile is enabled with adminGroupObjectIDs

### ISSUE THREAD

**Issue by RSE132** [kubernetes-sigs/cluster-api#10713]
### What steps did you take and what happened?

I have been trying to a deploy a managed aks cluster. The deployment happened properly but the aad integration is not working properly

I have following parameters enabled under `AzureManagedControlPlane`

```
  aadProfile:
    managed: true
    adminGroupObjectIDs: 
    - fe7b0187-979d-43c1-848c-2f58f7ff4424
  disableLocalAccounts: false
```

But when I look through azure portal I see it is enabling `Microsoft Entra ID authentication with azure RBAC` instead of `Microsoft Entra ID authentication with Kubernetes RBAC`

### What did you expect to happen?

I expected on the azure portal it will show me `Microsoft Entra ID authentication with Kubernetes RBAC` for the cluster instead I see this -

![image](https://github.com/kubernetes-sigs/cluster-api/assets/70406583/e2684717-865d-460d-88f3-d7660ff3d4cc)

### Cluster API version

cluster.x-k8s.io/v1beta1

### Kubernetes version

v1.28.9

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
