### ISSUE TITLE
clusterclass control-plane namingStrategy is not applied for Azure cluster

### ISSUE THREAD

**Issue by arno-pons** [kubernetes-sigs/cluster-api#10754]
### What steps did you take and what happened?

Deploying an Azure cluster using a clusterclass with a [spec.controlPlane.namingStrategy.template](https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-class/write-clusterclass#defining-a-custom-naming-strategy-for-controlplane-objects) attribute with value:
`"{{ .cluster.name }}-control-plane-{{ .random }}"`

doesn't create capz objects name (azuremachinetemplate, azuremachine and azure VM) matching this strategy.
Only capi objects (kubeadmcontrolplane and machine) are correctly named.
capz objects seems to be named with default strategy:
`"{{ .cluster.name }}-{{ .random }}"`

Here the clusterclass configuration:

```
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: my-cc
  namespace: default
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: my-kcpt
      namespace: default
    namingStrategy:
      template: "{{ .cluster.name }}-control-plane-{{ .random }}"
[...]
```

### What did you expect to happen?

Names of control-plane VM and nodes should match clusterclass namingStrategy.

### Cluster API version

- capi version: 1.6.1 
- capz version: 1.13.0

### Kubernetes version

- kubernetes version: v1.28.5

### Anything else you would like to add?

clusterclass with same namingStrategy for another infrastructure provider (vSphere capv) results in VM and node names matching the naming strategy.

Same issue has been opened on capz provider side:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4597

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
