### ISSUE TITLE
ClusterClass MachinePool reference naming validation with "Template" suffix

### ISSUE THREAD

**Issue by mweibel** [kubernetes-sigs/cluster-api#10768]
### What steps did you take and what happened?

Defined a ClusterClass for an CAPZ cluster with MachinePools:

```yaml
# minimized it so the issue becomes apparent
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: basic-001
  namespace: default
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: ctrl-plane-001
    machineInfrastructure:
      ref:
        kind: AzureMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: ctrl-plane-001
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AzureClusterTemplate
      name: azure-cluster
  workers:
    machinePools:
      - class: worker-001
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: KubeadmConfigTemplate
              name: worker-001
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: AzureMachinePool
              name: worker-001
```

Ran this with `clusterctl alpha topology plan`:
```bash
 » clusterctl alpha topology plan --file test.yaml --output-directory test
Command "plan" is deprecated, it will be removed in one of the upcoming releases.

Detected a cluster with Cluster API installed. Will use it to fetch missing objects.
Error: failed defaulting and validation on input objects: failed to run defaulting and validation on ClusterClasses: failed validation of cluster.x-k8s.io/v1beta1, Kind=ClusterClass default/basic-001: ClusterClass.cluster.x-k8s.io "basic-001" is invalid: spec.workers.machinePools[0].template.infrastructure.ref.kind: Invalid value: "AzureMachinePool": template kind must be of form "<name>Template"
```

I'm aware that alpha topology plan is deprecated and can't really be relied upon. However, from reading the code, I believe the same code is used for the defaulting/validating webhook for the ClusterClass CRD. 

The issue is that CAPZ does not have a AzureMachinePoolTemplate and neither does e.g. have CAPA one. 

My question is therefore:
1. is this a bug with the validator or does it *need* a `<name>Template` for all those infra refs?
2. if this is a bug with CAPZ/CAPA: do all MachinePool implementations need a `<Infra>MachinePoolTemplate`accompanying the `<Infra>MachinePool` CRD itself? Is there a missing guideline for implementations somewhere?

### What did you expect to happen?

It doesn't report an error since AzureMachinePool is a valid type and there is no AzureMachinePoolTemplate

### Cluster API version

v1.7.3

### Kubernetes version

v1.28.7

### Label(s) to be applied

/kind bug
/area clusterclass
/area machinepool
