### ISSUE TITLE
Adding Patch Option to the patch helper to ignore patching the status

### ISSUE THREAD

**Issue by mcbenjemaa** [kubernetes-sigs/cluster-api#10786]
### What would you like to be added (User Story)?

As a developer, I want to have the option to ignore patching the status when patching CAPI resources.

### Detailed Description

In certain cases, we would like to patch the resources without patching the status.

For example, In the deletion reconciliation loop, we have to make sure all cloud resources gets deleted, and then we delete the finalizer.
But If we patch the resource with a diff in the status and in the metadata (finalizer).
The metadata will be patched first, so the garbage collector will clean up the resource.

Therefore, the patch helper will return an error, resource not found when trying to patch the status

https://github.com/kubernetes-sigs/cluster-api/blob/54c8e46eeb4861746d6fadd9847bdea913797231/util/patch/patch.go#L148-L150

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: FooMachine
metadata:
  finalizers:
  - foomachine.infrastructure.cluster.x-k8s.io
```

### Anything else you would like to add?

It would be great to have a Patch Option to tell the helper to ignore the status sub-resource.

```go
 patchHelper.Patch(ctx, fooMachine, patch.WithIgnoreStatus())
```

### Label(s) to be applied

/kind feature
/area util
