### ISSUE TITLE
Add e2e test job for main branch that uses Kubernetes latest

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#10955]
Let's add a new e2e test job for the main branch (presubmit & periodics) with runs all e2e tests against Kubernetes latest

Based on current versions this should roughly use this config

```yaml
  KUBERNETES_VERSION_MANAGEMENT: "ci/latest-1.31"
  KUBERNETES_VERSION: "ci/latest-1.31"
  KUBERNETES_VERSION_UPGRADE_FROM: "v1.30.2"
  KUBERNETES_VERSION_UPGRADE_TO: "ci/latest-1.31"
```

(variables should be overwritten via env vars in k/test-infra)
