### ISSUE TITLE
Allow Clusterctl upgrade plan/apply to use --config to upgrade to specific version

### ISSUE THREAD

**Issue by robinAwallace** [kubernetes-sigs/cluster-api#11080]
### What would you like to be added (User Story)?

Hello, Im not sure if this is a bug or a feature. But as a operator I would like to control which version to upgrade to using the `--config` flag, as you can do with init. 

I know I can use arguments to control this behavior, but as there is a flag `--config` it would be nice to use it for `upgrade plan/apply` as well.

### Detailed Description

When I run the plan command today with `--config` and with the debug flag I see that the config is picked up, but after fetching latest versions upstream. 

```
Checking new release availability...
Potential override file SearchFile="/home/robin/.config/cluster-api/overrides/cluster-api/v1.8.1/metadata.yaml" Provider="cluster-api" Version="v1.8.1"
Fetching File="metadata.yaml" Provider="cluster-api" Type="CoreProvider" Version="v1.8.1"
Potential override file SearchFile="/home/robin/.config/cluster-api/overrides/bootstrap-kubeadm/v1.8.1/metadata.yaml" Provider="bootstrap-kubeadm" Version="v1.8.1"
Fetching File="metadata.yaml" Provider="kubeadm" Type="BootstrapProvider" Version="v1.8.1"
Potential override file SearchFile="/home/robin/.config/cluster-api/overrides/control-plane-kubeadm/v1.8.1/metadata.yaml" Provider="control-plane-kubeadm" Version="v1.8.1"
Fetching File="metadata.yaml" Provider="kubeadm" Type="ControlPlaneProvider" Version="v1.8.1"
Potential override file SearchFile="/home/robin/.config/cluster-api/overrides/cluster-api/v1.8.1/metadata.yaml" Provider="cluster-api" Version="v1.8.1"
Fetching File="metadata.yaml" Provider="cluster-api" Type="CoreProvider" Version="v1.8.1"
Potential override file SearchFile="/home/robin/.config/cluster-api/overrides/infrastructure-openstack/v0.10.4/metadata.yaml" Provider="infrastructure-openstack" Version="v0.10.4"
Fetching File="metadata.yaml" Provider="openstack" Type="InfrastructureProvider" Version="v0.10.4"

Latest release available for the v1beta1 API Version of Cluster API (contract):

NAME                       NAMESPACE                           TYPE                     CURRENT VERSION   NEXT VERSION
bootstrap-kubeadm          capi-kubeadm-bootstrap-system       BootstrapProvider        v1.7.4            v1.8.1
control-plane-kubeadm      capi-kubeadm-control-plane-system   ControlPlaneProvider     v1.7.4            v1.8.1
cluster-api                capi-system                         CoreProvider             v1.7.4            v1.8.1
infrastructure-openstack   capo-system                         InfrastructureProvider   v0.10.4           Already up to date

You can now apply the upgrade by executing the following command:

clusterctl upgrade apply --contract v1beta1

Using configuration File="/home/robin/Documents/capi/clusterctl-config.yaml"
```

`/home/robin/Documents/capi/clusterctl-config.yaml:`
```
providers:
  - name: "openstack"
    url: "https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/v0.10.4/infrastructure-components.yaml"
    type: "InfrastructureProvider"
  - name: "cluster-api"
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/v1.7.4/core-components.yaml"
    type: "CoreProvider"
  - name: "kubeadm"
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/v1.7.4/bootstrap-components.yaml"
    type: "BootstrapProvider"
  - name: "kubeadm"
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/v1.7.4/control-plane-components.yaml"
    type: ControlPlaneProvider
```

What I expect is that the version should be held back depending on my config file.

### Anything else you would like to add?

```
clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"53f0c5375dbd0ba307db2b92d3e5fff6e3ee6d63", GitTreeState:"clean", BuildDate:"2024-07-09T15:58:50Z", GoVersion:"go1.22.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
