### ISSUE TITLE
MachineDeployment treats machineTemplate as different ones when first time providing resourceVersion 

### ISSUE THREAD

**Issue by YichunLu** [kubernetes-sigs/cluster-api#11311]
### What steps did you take and what happened?

When applying machineDeployment and machineTemplate CRs, found a strange behavior.
The machineDeployment we're using is referring to the machineTemplate, in the way as not specifying the detailed resourceVersion but using name, apiVersion and type to pick the template - 
```
        infrastructureRef:
        name: {{ nodepool_name }}
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: {{ some_cloudVender_type_machineTemplate }}
```
This works fine when generating all CRs and actual resources.

However, while trying to patch the existing machineDeployment by adding the detailed resourceVersion for that machineTemplate CR, the machineDeployment will treat this as a new infrastructureRef and trigger a full rollout for the machines and machinsets, even though the machineTemplate not changed(use the resourceVersion get from the existing machineTemplate).  It sounds weird to me as not specifying then specify, would be counted as two different ref, given that the ref is exactly the same.

### What did you expect to happen?

Should add the identical check on the infrastructureRef updating check. If the Refs are the same, the update should not be triggered.

### Cluster API version

v1.5.2

### Kubernetes version

General

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
Do you mean apiVersion instead of resourceVersion? Can you share the ref before and after your patch please?

**Comment by YichunLu** [comment]
No. What I meant is resourceVersion. Originally, while we apply the machineDeployment, we do not have the explicit declaration for resourceVersion, e.g.

```
        infrastructureRef:
        name: {{ nodepool_name }}
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: {{ some_cloudVender_type_machineTemplate }}
```

We'd like to patch the machineDeployment by adding the resourceVersion for the infrastructureRef, e.g.

```
        infrastructureRef:
        name: {{ nodepool_name }}
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: {{ some_cloudVender_type_machineTemplate }}
        resourceVersion: {{someNumber got from the machineTemplate CR just created and associated}}
```

While at the very first time, we apply machineTemplate and machineDeployment at the same time. We don't include the explicit declaration in the resourceVersion. Then we tried to get the machineTemplate's resourceVersion and add it to the MD, though it was identical, the full roll-out was still triggered.
