### ISSUE TITLE
v1beta2: Class Namespace API change

### ISSUE THREAD

**Issue by Danil-Grigorev** [kubernetes-sigs/cluster-api#11500]
We need to implement update to the API definitions of the `Cluster` object in order to properly leverage cross-namespace `ClusterClass` references.

Proposed design change:
```yaml
topology:
  class:
    name: ...
    namespace: ...
```

which will deprecate introduced addition of the `classNamespace` field:
```yaml
topology:
  class: …
  classNamespace: ...
```

/kind api-change
