### ISSUE TITLE
ClusterClass: controlplane MHC setting bad selector labels

### ISSUE THREAD

**Issue by swarren83** [kubernetes-sigs/cluster-api#11549]
### What steps did you take and what happened?

Specifying a machineHealthCheck in `spec.controlPlane` sets the following selector labels up on the MHC resource:

```yaml
  selector:
    matchLabels:
      cluster.x-k8s.io/control-plane: ''
      topology.cluster.x-k8s.io/owned: ''
```

While the control plane machines are getting the following labels set:

```yaml
  labels:
    cluster.x-k8s.io/cluster-name: my-awesome-cluster
    cluster.x-k8s.io/control-plane: ''
```

Example mhc configuration
---------------------------
```yaml
spec:
  controlPlane:
    machineHealthCheck:
      maxUnhealthy: 33%
      nodeStartupTimeout: 10m0s
      unhealthyConditions:
        - status: Unknown
          timeout: 5m0s
          type: Ready
        - status: 'False'
          timeout: 5m0s
          type: Ready
```

### What did you expect to happen?

The MHC resource `spec.selector.matchLabels` should be such that they match labels applied to the control plane `Machine`.

### Cluster API version

v1.8.4

### Kubernetes version

v1.27.14

### Anything else you would like to add?

CAPI is running on a Rancher cluster, v2.7.9

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by sbueringer** [comment]
@swarren83 Are you sure about the labels on the CP Machines?

Example from e2e tests: (MD also for completeness) (https://gcsweb.k8s.io/gcs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-main/1872618404024684544/artifacts/clusters/bootstrap/resources/clusterclass-rollout-a5v7q9/)

CP: MHC + Machine
```yaml
# CP MHC
  clusterName: clusterclass-rollout-rpjw07
  selector:
    matchLabels:
      cluster.x-k8s.io/control-plane: ""
      topology.cluster.x-k8s.io/owned: ""
# CP Machine
  labels:
    cluster.x-k8s.io/cluster-name: clusterclass-rollout-rpjw07
    cluster.x-k8s.io/control-plane: ""
    cluster.x-k8s.io/control-plane-name: clusterclass-rollout-rpjw07-5wm7c
    topology.cluster.x-k8s.io/owned: ""
```


MD: MHC + Machine
```
# MD MHC
  clusterName: clusterclass-rollout-rpjw07
  selector:
    matchLabels:
      topology.cluster.x-k8s.io/deployment-name: md-0
      topology.cluster.x-k8s.io/owned: ""
# MD Machine
  labels:
    cluster.x-k8s.io/cluster-name: clusterclass-rollout-rpjw07
    cluster.x-k8s.io/deployment-name: clusterclass-rollout-rpjw07-md-0-w5v9l
    cluster.x-k8s.io/set-name: clusterclass-rollout-rpjw07-md-0-w5v9l-nqqkj
    machine-template-hash: 1319028294-nqqkj
    topology.cluster.x-k8s.io/deployment-name: md-0
    topology.cluster.x-k8s.io/owned: ""
```

**Comment by sbueringer** [comment]
cc @alexander-demicev

**Comment by swarren83** [comment]
Is `spec.controlplane.metadata` required in order to apply the `topology.cluster.x-k8s.io/` labels and annotations?

```
    metadata:
      annotations:
        ClusterClass.controlPlane.annotation: ClusterClass.controlPlane.annotationValue
      labels:
        ClusterClass.controlPlane.label: ClusterClass.controlPlane.labelValue
```
