### ISSUE TITLE
K8S Cluster deployed with kubeadm / docker cluster api provider reverts state from Ready to NotReady after 5minutes

### ISSUE THREAD

**Issue by ader1990** [kubernetes-sigs/cluster-api#11766]
### What steps did you take and what happened?

Hello,

I have followed the exact instructions from https://cluster-api.sigs.k8s.io/user/quick-start.html on 28.01.2025 (today), to deploy a Kubeadm based Kubernetes Cluster using a Docker infrastructure provider.

Steps followed on an Ubuntu 24.04 vanilla:

 * Install Docker CE as per https://docs.docker.com/engine/install/ubuntu/
 * Download the kubectl, kind, helm, clusterctl binaries and added them to PATH
 * Deployed a Kubeadm based Kubernetes Cluster using a Docker infrastructure provider
 
```bash
kind create cluster --config kind-cluster-with-extramounts.yaml
export SERVICE_CIDR=["10.96.0.0/12"]
export POD_CIDR=["192.168.0.0/16"]
export SERVICE_DOMAIN="k8s.test"
clusterctl init --infrastructure docker
clusterctl generate cluster capi-quickstart --flavor development   --kubernetes-version v1.32.0   --control-plane-machine-count=1   --worker-machine-count=0   > capi-quickstart.yaml
kubectl apply -f capi-quickstart.yaml
```

Then, right after deployment, I could check the cluster state and all the resources were fine (all resources Ready) after a period of 1-2 minutes:

```bash
clusterctl describe cluster capi-quickstart
```

![Image](https://github.com/user-attachments/assets/70e60a05-0e75-435d-aec8-7142c19e991d)

But after 5 minutes more, the cluster state was not Ready anymore because of some of the dependent resources started reverting the state because the Kubernetes cluster deployed had no CNI installed.

```bash
clusterctl describe cluster capi-quickstart
```

![Image](https://github.com/user-attachments/assets/d08bf370-51db-48b2-b9c6-bff0ea237fba)

### What did you expect to happen?

I expect for the deployed cluster resources to not revert state to NotReady after 5 minutes, either to be in the NotReady state for all the lifecycle or to not revert state.

### Cluster API version

Latest.

```
$> clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"79e6731b0d20a0ca2dad5e4f96d2a532aa82b54b", GitTreeState:"clean", BuildDate:"2025-01-21T17:01:32Z", GoVersion:"go1.22.10", Compiler:"gc", Platform:"linux/amd64"}

$> kubectl get pods -A -o yaml |grep -i image |grep -i cluster | sort -u
      image: gcr.io/k8s-staging-cluster-api/capd-manager:v1.9.4
      image: registry.k8s.io/cluster-api/cluster-api-controller:v1.9.4
      image: registry.k8s.io/cluster-api/kubeadm-bootstrap-controller:v1.9.4
      image: registry.k8s.io/cluster-api/kubeadm-control-plane-controller:v1.9.4
      imageID: gcr.io/k8s-staging-cluster-api/capd-manager@sha256:2c1893640f5f60d07a17fefff0221103dcd4a5e43efe74a626b052afbd483db5
      imageID: registry.k8s.io/cluster-api/cluster-api-controller@sha256:e9b098114c1369f3f35a55c1a7962c8e82d3c2a82f36e4a6601f8e34bd1629ea
      imageID: registry.k8s.io/cluster-api/kubeadm-bootstrap-controller@sha256:67487452ea3a128d74e2d324aa6e45e4ef55c21de6454d0d4899c3c8f92fa364
      imageID: registry.k8s.io/cluster-api/kubeadm-control-plane-controller@sha256:d7dbffc844febfc5b54c05890c559a17ffd6a7479836c17a6a7e07bdc5b601a1
```

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by ader1990** [comment]
Status of the Cluster after 5 minutes:

```bash
kubectl get Cluster -A -o yaml
```  

```yaml
status:
    conditions:
    - lastTransitionTime: "2025-01-28T13:09:46Z"
      message: 0 of 1 completed
      reason: UnhealthyNode @ Machine/capi-quickstart-xd7zh-xb2fw
      severity: Warning
      status: "False"
      type: Ready
    - lastTransitionTime: "2025-01-28T13:05:10Z"
      status: "True"
      type: ControlPlaneInitialized
    - lastTransitionTime: "2025-01-28T13:09:46Z"
      message: 0 of 1 completed
      reason: UnhealthyNode @ Machine/capi-quickstart-xd7zh-xb2fw
      severity: Warning
      status: "False"
      type: ControlPlaneReady
    - lastTransitionTime: "2025-01-28T13:04:04Z"
      status: "True"
      type: InfrastructureReady
    - lastTransitionTime: "2025-01-28T13:04:02Z"
      status: "True"
      type: TopologyReconciled
...
      - lastTransitionTime: "2025-01-28T13:04:06Z"
        message: |-
          * Machine capi-quickstart-xd7zh-xb2fw:
            * NodeHealthy:
              * Node.Ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
            * HealthCheckSucceeded: Health check failed: Condition Ready on Node is reporting status False for more than 5m0s
        observedGeneration: 3

```
