### ISSUE TITLE
Regression: Cluster can no longer resolve infrastructureRef without namespace

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api#11853]
### What steps did you take and what happened?

After upgrading from CAPI v1.8.x to v1.9.4, CAPI is no longer able to see my infracluster. The logs are full of:

```
I0214 16:42:37.533752       1 cluster_controller_phases.go:192] "Could not find OpenStackCluster, requeuing" controller="cluster" controllerGroup="cluster.x-k8s.io" controllerKind="Cluster" Cluster="openshift-cluster-api/mbooth-capi-test-cvb7b" namespace="openshift-cluster-api" name="mbooth-capi-test-cvb7b" reconcileID="f7f50bd4-ddfa-4e36-8b2b-32d6593ac7b6"
```

The cluster spec is:
```yaml
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OpenStackCluster
    name: mbooth-capi-test-cvb7b
```

This worked on v1.8.x. The regression appears to have been introduced by https://github.com/kubernetes-sigs/cluster-api/pull/11361. This change appears to remove the defaulting behaviour.

### What did you expect to happen?

namespace should continue to default to the cluster namespace when not set.

### Cluster API version

v1.9.4

### Kubernetes version

v1.31.3

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
