### ISSUE TITLE
The proper way to modify kubelet configuration

### ISSUE THREAD

**Issue by vkokarovtsev** [kubernetes-sigs/cluster-api#12244]
Hi!
We are using **ClusterClass** for managing k8s clusters parameters.
Inside it we also have kubelet configuration. Something like this:
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: clusterclass-example
...
spec:
  patches:
    - name: KubeadmControlPlanePatch
      definitions:
        - selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: KubeadmControlPlaneTemplate
            matchResources:
              controlPlane: true
          jsonPatches:
            - op: add
              path: /spec/template/spec/kubeadmConfigSpec/files/-
              valueFrom:
                template: |
                  path: /etc/kubelet-config.yaml
                  owner: root:root
                  permissions: "0600"
                  content: |
                    ---
                    apiVersion: kubelet.config.k8s.io/v1beta1
                    kind: KubeletConfiguration
                    address: "192.168.0.8"
                    port: 20250
                    serializeImagePulls: false
                    evictionHard:
                        memory.available:  "100Mi"
                        nodefs.available:  "10%"
                        nodefs.inodesFree: "5%"
                        imagefs.available: "15%"
                        imagefs.inodesFree: "5%"
...
```
It may seem that changing kubelet parameters would require only changing a piece of code in the ClusterClass resource and updating its version in the cluster. However, in reality, all nodes continue to operate with the old configuration. It probably happens because of the `kubeadm join` command, which doesn't include an upload-config step unlike `kubeadm init`. Therefore, initial generation of the kubelet config occurs during cluster setup process.

I would like to understand the most proper and effective way to modify kubelet settings in a running Kubernetes cluster.

P.S. I've read the documentation about kubelet configuration , but couldn't find any information about ClusterClass: https://cluster-api.sigs.k8s.io/tasks/bootstrap/kubeadm-bootstrap/kubelet-config
