### ISSUE TITLE
topologymutation.createJSONPatch should use the decoded original runtime.Object to calculate jsonpatch

### ISSUE THREAD

**Issue by wyike** [kubernetes-sigs/cluster-api#12258]
### What steps did you take and what happened?

1. I defines a cluster object A, using clusterclass B.  B uses vspheremachinetemplate C as machineInfrastructure ref.
2. base vspheremachinetemplate C:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  annotations:
   ....
spec:
  template:
    spec:
      cloneMode: fullClone
      datacenter: /dc0
      datastore: /dc0/datastore/sharedVmfs-0
      diskGiB: 40
      folder: /dc0/vm/folder0
      memoryMiB: 16384
      network:
        devices:
        - networkName: /dc0/network/VM Network
      numCPUs: 4
      numCoresPerSocket: 0
      powerOffMode: hard
      resourcePool: /dc0/host/cluster0/Resources/rp0
      server: 10.162.251.181
      storagePolicyName: ""
      template: ' '
```
3.  clusterclass B will hook runtime extension defined in ClusterClass B to generate jsonpatches and create vspheremachinetemplate for each new cluster. With CAPI 1.7.4, based on A, B, C, assuming we create a cluster dev, the vspheremachinetemplate for dev is created, like:
```
~# kubectl get vspheremachinetemplate  tkg-mgmt-vc-sz6zn -n tkg-system -oyaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  ...
spec:
  template:
    spec:
      cloneMode: fullClone
      datacenter: /dc0
      datastore: /dc0/datastore/sharedVmfs-0
      diskGiB: 40
      folder: /dc0/vm/folder0
      memoryMiB: 16384
      network:
        devices:
        - dhcp4: true
          networkName: /dc0/network/VM Network
      numCPUs: 4
      numCoresPerSocket: 0
      powerOffMode: hard
      resourcePool: /dc0/host/cluster0/Resources/rp0
      server: 10.162.251.181
      storagePolicyName: ""
      template: /dc0/vm/ubuntu-2204-kube-v1.29.13+vmware.3-tkg.1-c6934
```
4. After upgrading to CAPI 1.9.4,  because of https://github.com/kubernetes-sigs/cluster-api/pull/10912, the generated patch has 3 more ops:
```
I0520 07:48:04.329694       1 walker.go:170] "Generated patch" template="infrastructure.cluster.x-k8s.io/v1beta1/VSphereMachineTemplate" holder="controlplane.cluster.x-k8s.io/v1beta1/KubeadmControlPlane/tkg-system/tkg-mgmt-vc-controlplane-99grl" uid="ad6eb52a-21d4-401d-8347-4eabfa8e80aa" patch="[{"op":"add","path":"/spec/template/metadata","value":{}},{"op":"add","path":"/spec/template/spec/network/devices/0/dhcp4","value":true},{"op":"replace","path":"/spec/template/spec/template","value":"/dc0/vm/ubuntu-2204-kube-v1.29.13+vmware.3-tkg.1-c6934"},{"op":"remove","path":"/spec/template/spec/numCoresPerSocket"},{"op":"remove","path":"/spec/template/spec/storagePolicyName"}]"
```
{"op":"add","path":"/spec/template/metadata","value":{}}
{"op":"remove","path":"/spec/template/spec/numCoresPerSocket"}
{"op":"remove","path":"/spec/template/spec/storagePolicyName"}

As a result, the new cluster machine template would be thing like:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
 ...
spec:
  template:
    spec:
      cloneMode: fullClone
      datacenter: /dc0
      datastore: /dc0/datastore/sharedVmfs-0
      diskGiB: 40
      folder: /dc0/vm/folder0
      memoryMiB: 16384
      network:
        devices:
        - dhcp4: true
          networkName: /dc0/network/VM Network
      numCPUs: 4
      powerOffMode: hard
      resourcePool: /dc0/host/cluster0/Resources/rp0
      server: 10.162.251.181
      template: /dc0/vm/ubuntu-2204-kube-v1.29.13+vmware.3-tkg.1-c6934
```
the VSphereMachineTemplate for dev gets changed with numCoresPerSocket and storagePolicyName removed. So the cluster machines gets rollout. 

This rollout is not what we want. Especially when this dev cluster is management cluster, it will update VSphereMachineTemplate for all the workload clusters and all the machines starts rollout automatically.

### What did you expect to happen?

Additional ops shouldn't be generated by topologymutation.createJSONPatch.
```
{"op":"add","path":"/spec/template/metadata","value":{}}
{"op":"remove","path":"/spec/template/spec/numCoresPerSocket"}
{"op":"remove","path":"/spec/template/spec/storagePolicyName"}
```

So that CAPI upgrade won't break existing management and workload clusters.

This breaking change is introduced by root cause:
https://github.com/kubernetes-sigs/cluster-api/pull/10912 

raw object in byte  --> decoded --> original runtime.Object ---> marshal ---> marshalledOriginal in byte
                                                                       
original runtime.Object----> deepcopy to ---> modified runtime.Object --> set some properties in modified 
----> marshal ---> marshalledModified

To me, **it looks a right thing to use `original` runtime.Object and  `modified` runtime.Object as source of truth to compare the diff, since `modified` is deep copied from original, and user operations are all against `modified`**

While raw in byte may have something we cannot predict since it is using decoder with some magic, which is not just unmarshal. We shouldn't use it to compare diff with `modified` runtime.Object, which is also a breaking change on common workflow and may impact other people.

In our case, storagePolicyName and numCoresPerSocket are `omityempty` https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/apis/v1beta1/types.go#L149. So the marshalling result of of their `original` and `modified` objects are not containing the two fields. Although the raw in byte contains these two fields.

Regarding the issue mentioned in pull 10912, I think it's worth to try marking `host` and `port` as `omitempy` https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/apis/v1beta1/types.go#L272-L275 which looks a right direction. If these two fields are required always, I am not sure why we can have case like in 10912
```
{
  "apiVersion": "vmware.infrastructure.cluster.x-k8s.io/v1beta1",
  "kind": "VSphereClusterTemplate",
 ...
  "spec": {
    "template": {
      "spec": {}
    }
  }
}
```
I may lack context of CAPV user case and API definition rules, just sharing above findings for more discussions.
 

### Cluster API version

CAPI 1.7.4 without the problem
Upgrade to CAPI 1.8.x+ has the problem

### Kubernetes version

1.28, 1.29, 1.30

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
