### ISSUE TITLE
Define required provider-specific metadata location and format

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api#1373]
/kind feature

**Describe the solution you'd like**
Currently we don't have any way to determine which provider versions are compatible with which versions of cluster-api, which bootstrap providers they support, or even what the latest versions of each are. I propose that we formalize a location and format for metadata that can be used for this purpose.

We should also formalize the process of releasing pre-generated "provider components" for each "type" of provider as part of a release, so that those can be more easily referenced by other providers and/or higher level cluster-api oriented tooling.

proposed metadata file name: <repo root>/metadata.yaml
proposed format (v1alpha1 used only for example purposes to show multiple defined versions, and bootstrap provider info would only be required for an "infrastructure" provider):

```yaml
---
providerType: infrastructure
apiSupport:
  v1alpha1:
    releaseSeries: ["v0.2", "v0.3"]
  v1alpha2:
    releaseSeries: ["v0.4"]
releaseSeries:
  "v0.2":
    clusterApiCompatibleSeries: ["v0.1"]
	latestRelease: "v0.2.3"
  "v0.3":
    clusterApiCompatibleSeries: ["v0.1"]
	latestRelease: "v0.3.9"
  "v0.4":
    clusterApiCompatibleSeries: ["v0.2"]
	bootstrapProvidersSupported:
	- name: "cluster-api-bootstrap-provider-kubeadm"
	  supportedVersionSeries: ["v0.1"]
	latestRelease: "v0.4.0"
```

For the published "provider components", my proposal is to name the file "bootstrap-components.yaml" for bootstrap providers, "infrastructure-components.yaml" for infrastructure providers, and "cluster-api-components.yaml" for the core cluster-api components.
