### ISSUE TITLE
cluster creation with numeric number name fails

### ISSUE THREAD

**Issue by sirao** [kubernetes-sigs/cluster-api#1702]
**What steps did you take and what happened:**
1. create the KIND cluster and deploy CRDs
2. Set the AWS credentials
3. Install infrastructure CRDs
4. Create cluster with below configuration
```
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: 1947
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: AWSCluster
    name: 1947
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AWSCluster
metadata:
  name: 1947
spec:
  # Change this value to the region you want to deploy the cluster in.
  region: us-east-2
  # Change this value to a valid SSH Key Pair present in your AWS Account.
  sshKeyName: default
```

**What did you expect to happen:**
If the name is not following the naming convention it should give the suggestion rather than error message as below
```
error when retrieving current configuration of:
Resource: "cluster.x-k8s.io/v1alpha2, Resource=clusters", GroupVersionKind: "cluster.x-k8s.io/v1alpha2, Kind=Cluster"
Name: "", Namespace: "default"
Object: &{map["apiVersion":"cluster.x-k8s.io/v1alpha2" "kind":"Cluster" "metadata":map["namespace":"default" "annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "name":'\u079b'] "spec":map["clusterNetwork":map["pods":map["cidrBlocks":["192.168.0.0/16"]]] "infrastructureRef":map["apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha2" "kind":"AWSCluster" "name":'\u079b']]]}
from server for: "../docs/cluster-numeric-name.yaml": resource name may not be empty
error when retrieving current configuration of:
Resource: "infrastructure.cluster.x-k8s.io/v1alpha2, Resource=awsclusters", GroupVersionKind: "infrastructure.cluster.x-k8s.io/v1alpha2, Kind=AWSCluster"
Name: "", Namespace: "default"
Object: &{map["apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha2" "kind":"AWSCluster" "metadata":map["name":'\u079b' "namespace":"default" "annotations":map["kubectl.kubernetes.io/last-applied-configuration":""]] "spec":map["region":"us-east-2" "sshKeyName":"default"]]}
from server for: "../docs/cluster-numeric-name.yaml": resource name may not be empty
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.4.3
- Minikube/KIND version: v0.5.1
- Kubernetes version: (use `kubectl version`): v1.13.3(client) v.1.15.3(server)
- OS (e.g. from `/etc/os-release`): Darwin x64

/kind bug

**Comment by detiber** [comment]
We should probably add openapi validation to the CRDs to ensure that names are conformant with kubernetes naming requirements: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names

/priority important-soon
/milestone v0.3.0

**Comment by nader-ziada** [comment]
Should this be done by enabling webhook validation?

**Comment by detiber** [comment]
@nader-ziada my preference for validations would be to first do everything we can as openapi validations (kubebuilder controller-tools annotations), then via validating webhook, and then finally in the code if the others are not possible.

**Comment by nader-ziada** [comment]
@detiber ok, will work on that issue. Thanks

/assign

**Comment by nader-ziada** [comment]
The name of the cluster is coming from the `metadata.Name` which I don't think we can put the kubebuilder validation annotation on since its a common kubernetes object, 
@detiber does it make sense to use a webhook in this case, or did I misunderstand?

**Comment by detiber** [comment]
@nader-ziada ah, that's a good point. It would be really nice if there was automated support for this (either in controller-tools or the Kubernetes built in CRD support).

+1 to webhook for validation.

**Comment by nader-ziada** [comment]
@sirao The problem mentioned above is because kubectl parses the value `1947` as an integer and the name field is expected to be a string. So even though we are adding the webhook validation on the name, you would still get this error message because the crd validation happens first before the webhook is invoked. 

The webhook validation (in a PR coming soon) will validate the validity if the name used according to kubernetes names standards https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names 

cc @wfernandes

**Comment by nader-ziada** [comment]
I actually don't think we need to add a webhook anymore, we are getting the same name validation I'm adding by default. Once I changed the name in the above example to a string and made it invalid as shown here:

```yaml
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: "-1947"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: AWSCluster
    name: "1947"
```

I got the following error
```
The Cluster "-1947" is invalid: metadata.name: Invalid value: "-1947": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

and if the name is valid as just a string without the `-` in the beginning it works.


@detiber @wfernandes what do you think?
