### ISSUE TITLE
Can't apply node-role.kubernetes.io at bootstrap time

### ISSUE THREAD

**Issue by de13** [kubernetes-sigs/cluster-api#1719]
**User Story**

As an operator, I would like to be able to put `node-role.kubernetes.io` label at creation time through `kubeadm`

**Detailed Description**

I would like to be able to give a `role` to my nodes (eg master, worker) at bootstrap. Unfortunately, I got an error with `kubeadm` when I try to apply such label through the config file:

```
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: ""
    token: ""
    unsafeSkipCAVerification: true
nodeRegistration:
  kubeletExtraArgs:
    node-labels: node-role.kubernetes.io/worker=""
```

```
Nov  2 06:56:02 dday-instance-2 kubelet[6823]: --node-labels in the 'kubernetes.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io) or be in the specifically allowed set (beta.kubernetes.io/arch, beta.kubernetes.io/instance-type, beta.kubernetes.io/os, failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone, failure-domain.kubernetes.io/region, failure-domain.kubernetes.io/zone, kubernetes.io/arch, kubernetes.io/hostname, kubernetes.io/instance-type, kubernetes.io/os)
```

**Anything else you would like to add:**

It should be great to add node-role in proposal in this list: https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/0000-20170814-bounding-self-labeling-kubelets.md#proposal

/kind feature
