### ISSUE TITLE
Document stance on static IP addresses

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api#1740]
**User Story**

As a user/operator, I would like to understand Cluster API's stance on static IP addresses so that I can understand if it will affect my ability to use Cluster API in my environment.

**Detailed Description**

We should document that individual infrastructure providers _may_, at their discretion, add support for static IP address assignment at the individual machine level, **but**, when you move up to higher-level abstractions such as MachineSet, MachineDeployment, KubeadmControlPlane, there is no support for customizing each replica. If someone wanted to use static IPs with these abstractions, there would need to be a coordinated effort between the infrastructure provider and some sort of IPAM controller (outside the scope of Cluster API itself).

/kind documentation
/priority important-soon
/milestone v0.3.0

cc @akutz

**Comment by akutz** [comment]
While it may be inferred, it also (I think) bears explicit mention in such documentation that the upgrade capabilities for `MachineDeployments` and the upcoming control plane upgrades won't work without DHCP or some sort of IPAM (as @ncdc mentioned above).

**Comment by ncdc** [comment]
cc @rosskukulinski

**Comment by sheriefhammam** [comment]
A relevant observation
I haven't debugged it yet but for some reason i can assign static IPs to worker nodes but it affects somehow the control plane

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: VSphereMachineTemplate
metadata:
  name: workload-cluster-02-md-0
  namespace: default
spec:
  template:
    spec:
      datacenter: NIC-Darmstadt
      diskGiB: 20
      memoryMiB: 2048
      network:
        devices:
        - dhcp4: false
          dhcp6: false
          gateway4: 10.100.146.1
          ipAddrs:
          - 10.100.146.50/24
          networkName: ds146
      numCPUs: 2
      template: T_centos-7-kube-v1.16.3.a4
```

```
kubectl get nodes -o wide
NAME                                        STATUS   ROLES    AGE   VERSION   INTERNAL-IP     EXTERNAL-IP     OS-IMAGE                KERNEL-VERSION               CONTAINER-RUNTIME
workload-cluster-02-controlplane-0          Ready    master   36m   v1.16.3   10.100.146.50   10.100.146.50   CentOS Linux 7 (Core)   3.10.0-1062.9.1.el7.x86_64   containerd://1.3.0
workload-cluster-02-md-0-5b7df745f6-bgs2z   Ready    <none>   35m   v1.16.3   10.100.146.84   10.100.146.84   CentOS Linux 7 (Core)   3.10.0-1062.9.1.el7.x86_64   containerd://1.3.0
```
