### ISSUE TITLE
bootstrap-provider: allow the content of a file to come from a configmap or secret

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api#1846]
**User Story**

As an operator I would like to be able to be able to get the contents of a file from a configmap or secret so that i don't have to embed the contents directly within the `KubeadmConfig`. This is especially useful for custom configuration using PreKubeadmCommands and PostKubeadmCommands.

**Detailed Description**

I would like to see [`Contents`](https://github.com/kubernetes-sigs/cluster-api/blob/master/bootstrap/kubeadm/api/v1alpha3/kubeadmbootstrapconfig_types.go#L141) changed with the `File` struct so that you can specify the contents in 3 ways:

- Explicit value (how you currently do it)
- Reference a config map and get the contents from there when creating the bootstrap data
- Reference a secret and get the contents from the secret when creating the bootstrap data

This is the current situation:
```yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  name: capi-quickstart-controlplane-0
spec:
  clusterConfiguration:
    apiServer:
      extraArgs:
        cloud-config: /etc/kubernetes/azure.json
        cloud-provider: azure
      extraVolumes:
      - hostPath: /etc/kubernetes/azure.json
        mountPath: /etc/kubernetes/azure.json
        name: cloud-config
        readOnly: true
      timeoutForControlPlane: 20m
    controllerManager:
      extraArgs:
        allocate-node-cidrs: "false"
        cloud-config: /etc/kubernetes/azure.json
        cloud-provider: azure
      extraVolumes:
      - hostPath: /etc/kubernetes/azure.json
        mountPath: /etc/kubernetes/azure.json
        name: cloud-config
        readOnly: true
  files:
  - content: |
      {
        "cloud": "AzurePublicCloud",
        "tenantId": "${AZURE_TENANT_ID}",
        "subscriptionId": "${AZURE_SUBSCRIPTION_ID}",
        "aadClientId": "${AZURE_CLIENT_ID}",
        "aadClientSecret": "${AZURE_CLIENT_SECRET}",
        ....
      }
    owner: root:root
    path: /etc/kubernetes/azure.json
    permissions: "0644"
``` 

And it could be changed to something like this:

```yaml
  files:
  - content
        valueFrom:
            secretKeyRef:
                   name: azurecreds
                   key: azure.json
    owner: root:root
    path: /etc/kubernetes/azure.json
    permissions: "0644"
```

Or using an ObjectReference

**Anything else you would like to add:**

/kind feature
