### ISSUE TITLE
KubeadmControlPlane web hook service name is wrong after kustomize build

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#1966]
**What steps did you take and what happened:**
1. Clone this repo
2. Run `kustomize build config/default`

Here is the (very heavily reduced) output:

<summary>
<details>

```
*snip*
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: capi-webhook-service
      namespace: capi-system
      path: /validate-cluster-x-k8s-io-v1alpha3-cluster
- clientConfig:
    caBundle: Cg==
    service:
      name: capi-webhook-service
      namespace: capi-system
      path: /validate-cluster-x-k8s-io-v1alpha3-machine
- clientConfig:
    caBundle: Cg==
    service:
      name: capi-webhook-service
      namespace: capi-system
      path: /validate-cluster-x-k8s-io-v1alpha3-machinedeployment
- clientConfig:
    caBundle: Cg==
    service:
      name: capi-webhook-service
      namespace: capi-system
      path: /validate-cluster-x-k8s-io-v1alpha3-machinepool
- clientConfig:
    caBundle: Cg==
    service:
      name: capi-webhook-service
      namespace: capi-system
      path: /validate-cluster-x-k8s-io-v1alpha3-machineset
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: controlplane-validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: capi-system
      path: /validate-controlplane-cluster-x-k8s-io-v1alpha3-kubeadmcontrolplane
```

</details>
</summary>

**What did you expect to happen:**
I then saw an issue creating kubeadm control planes. The web hook service "webhook-service" could not be found.

**Anything else you would like to add:**

/kind bug
