### ISSUE TITLE
kubeadm bootstrap v1alpha2 having trouble with secrets

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api#2108]
**What steps did you take and what happened:**
This is reported from the field. The thread in slack can be found here: https://kubernetes.slack.com/archives/C8TSNPY4T/p1579617647045800

To summarize the thread: Spinning up a cluster with a v1alpha2 bootstrap config. Seeing errors from kubeadm config controller spinning trying to create a secret and failing because the secret already exists. Because of this, CAPI is waiting and not creating anything.

This is running components from master from January 20th, 2020.

/kind bug

/cc @johnharris85 
/assign
/milestone v0.3.0
/lifecycle active

**Comment by vincepri** [comment]
I'm wondering if the logic to check the `configOwner` DataSecretName is the actual problem here. Does the Machine have the `DataSecretName`?

**Comment by chuckha** [comment]
> I'm wondering if the logic to check the `configOwner` DataSecretName is the actual problem here. Does the Machine have the `DataSecretName`?

Working on repro at the moment

**Comment by chuckha** [comment]
Going to wait to get the manifests and things to repro a bit easier

/remove-lifecycle active

**Comment by johnharris85** [comment]
```
---
# Source: helm-capa/templates/existing-vpc-cluster.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AWSCluster
metadata:
  name: jh-k8s-capa1
spec:
  region: us-west-2
  sshKeyName: kubeadm-ec2
  networkSpec:
    subnets:
    - id: subnet-0af15475944666f27
    - id: subnet-03020e9f994321962
    vpc:
      id: vpc-0d521fde2dee78fbd
  # controlPlaneLoadBalancer:
  #   scheme: "internal"
---
# Source: helm-capa/templates/existing-vpc-cluster.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AWSMachine
metadata:
  name: jh-k8s-capa1-controlplane-0
spec:
  iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
  instanceType: t3.medium
  rootDeviceSize: 20
  sshKeyName: kubeadm-ec2
  subnet:
    id: subnet-0af15475944666f27
  additionalSecurityGroups:
  - id: sg-08d60857ffd602fbd
---
# Source: helm-capa/templates/existing-vpc-cluster.yaml
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: jh-k8s-capa1
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: AWSCluster
    name: jh-k8s-capa1
---
# Source: helm-capa/templates/existing-vpc-cluster.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  name: jh-k8s-capa1-controlplane-0
spec:
  files:
  - content: |
      apiVersion: audit.k8s.io/v1beta1
      kind: Policy
      rules:
        # The following requests were manually identified as high-volume and low-risk,
        # so drop them.
        - level: None
          resources:
            - group: ""
              resources:
                - endpoints
                - services
                - services/status
          users:
            - 'system:kube-proxy'
          verbs:
            - watch
        - level: None
          resources:
            - group: ""
              resources:
                - nodes
                - nodes/status
          userGroups:
            - 'system:nodes'
          verbs:
            - get
        - level: None
          namespaces:
            - kube-system
          resources:
            - group: ""
              resources:
                - endpoints
          users:
            - 'system:kube-controller-manager'
            - 'system:kube-scheduler'
            - 'system:serviceaccount:kube-system:endpoint-controller'
          verbs:
            - get
            - update
        - level: None
          resources:
            - group: ""
              resources:
                - namespaces
                - namespaces/status
                - namespaces/finalize
          users:
            - 'system:apiserver'
          verbs:
            - get
        # Don't log HPA fetching metrics.
        - level: None
          resources:
            - group: metrics.k8s.io
          users:
            - 'system:kube-controller-manager'
          verbs:
            - get
            - list
        # Don't log these read-only URLs.
        - level: None
          nonResourceURLs:
            - '/healthz*'
            - /version
            - '/swagger*'
        # Don't log events requests.
        - level: None
          resources:
            - group: ""
              resources:
                - events
        # node and pod status calls from nodes are high-volume and can be large, don't log responses for expected updates from nodes
        - level: Request
          omitStages:
            - RequestReceived
          resources:
            - group: ""
              resources:
                - nodes/status
                - pods/status
          users:
            - kubelet
            - 'system:node-problem-detector'
            - 'system:serviceaccount:kube-system:node-problem-detector'
          verbs:
            - update
            - patch
        - level: Request
          omitStages:
            - RequestReceived
          resources:
            - group: ""
              resources:
                - nodes/status
                - pods/status
          userGroups:
            - 'system:nodes'
          verbs:
            - update
            - patch
        # deletecollection calls can be large, don't log responses for expected namespace deletions
        - level: Request
          omitStages:
            - RequestReceived
          users:
            - 'system:serviceaccount:kube-system:namespace-controller'
          verbs:
            - deletecollection
        # Secrets, ConfigMaps, and TokenReviews can contain sensitive & binary data,
        # so only log at the Metadata level.
        - level: Metadata
          omitStages:
            - RequestReceived
          resources:
            - group: ""
              resources:
                - secrets
                - configmaps
            - group: authentication.k8s.io
              resources:
                - tokenreviews
        # Get repsonses can be large; skip them.
        - level: Request
          omitStages:
            - RequestReceived
          resources:
            - group: ""
            - group: admissionregistration.k8s.io
            - group: apiextensions.k8s.io
            - group: apiregistration.k8s.io
            - group: apps
            - group: authentication.k8s.io
            - group: authorization.k8s.io
            - group: autoscaling
            - group: batch
            - group: certificates.k8s.io
            - group: extensions
            - group: metrics.k8s.io
            - group: networking.k8s.io
            - group: policy
            - group: rbac.authorization.k8s.io
            - group: scheduling.k8s.io
            - group: settings.k8s.io
            - group: storage.k8s.io
          verbs:
            - get
            - list
            - watch
        # Default level for known APIs
        - level: RequestResponse
          omitStages:
            - RequestReceived
          resources:
            - group: ""
            - group: admissionregistration.k8s.io
            - group: apiextensions.k8s.io
            - group: apiregistration.k8s.io
            - group: apps
            - group: authentication.k8s.io
            - group: authorization.k8s.io
            - group: autoscaling
            - group: batch
            - group: certificates.k8s.io
            - group: extensions
            - group: metrics.k8s.io
            - group: networking.k8s.io
            - group: policy
            - group: rbac.authorization.k8s.io
            - group: scheduling.k8s.io
            - group: settings.k8s.io
            - group: storage.k8s.io
            
        # Default level for all other requests.
        - level: Metadata
          omitStages:
            - RequestReceived
      
    owner: "root:root"
    path: "/srv/kubernetes/audit.yaml"
    permissions: "0644"
  clusterConfiguration:
    apiServer:
      extraVolumes:
      # Audit Logging
      - name: "audit-policies"
        hostPath: "/srv/kubernetes"
        mountPath: "/srv/kubernetes"
        readOnly: true
        pathType: DirectoryOrCreate
      - name: "audit-logs"
        hostPath: "/var/log/kubernetes"
        mountPath: "/var/log/kubernetes"
        readOnly: false
        pathType: DirectoryOrCreate
      # Etcd Secret Encryption
      - name: "etcd-encryption"
        hostPath: "/etc/kubernetes/etcd-encryption"
        mountPath: "/etc/kubernetes/etcd-encryption"
        readOnly: false
        pathType: DirectoryOrCreate
      extraArgs:
        audit-log-path: /var/log/kubernetes/kube-apiserver-audit.log
        audit-log-maxage: "10" # num days
        audit-log-maxbackup: "1" # the num of audit logs to retain
        audit-log-maxsize: "100" # the max size in MB to retain
        audit-policy-file: /srv/kubernetes/audit.yaml
        cloud-provider: aws
        oidc-issuer-url: https://dex-pw.someurl.info/dex
        oidc-client-id: kube-login
        oidc-username-claim: name
        oidc-username-prefix: "-"
        oidc-groups-claim: groups
        # enable-admission-plugins: PodSecurityPolicy
    controllerManager:
      extraArgs:
        allocate-node-cidrs: "true"
        cluster-cidr: "192.168.0.0/16"
        cloud-provider: aws
  initConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: aws
      name: "{{ ds.meta_data.hostname }}"
---
# Source: helm-capa/templates/existing-vpc-cluster.yaml
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: jh-k8s-capa1
    cluster.x-k8s.io/control-plane: "true"
  name: jh-k8s-capa1-controlplane-0
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: jh-k8s-capa1-controlplane-0
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: AWSMachine
    name: jh-k8s-capa1-controlplane-0
  version: v1.16.2
```
