### ISSUE TITLE
KubeadmControlPlane generates more machines than spec.Replicas

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api#2176]
**What steps did you take and what happened:**

while running CAPV's e2e tests locally, the `kubeadm_control_plane_controller` generated two control planes machines instead of one:

```
NAME                     PROVIDERID                                       PHASE
test-bd8afd6-kcp-6cnn9   vsphere://4230c843-d304-b684-b16e-b70e24a223be   Provisioning
test-bd8afd6-kcp-8npf7   vsphere://4230356e-ac11-8e81-a656-620b84c2453a   Provisioning
```

the specified number of replicas in my KCP:

```
    replicas: 1
    version: v1.16.2
  status:
    replicas: 2
    selector: cluster.x-k8s.io/cluster-name=test-bd8afd6,cluster.x-k8s.io/control-plane=
    unavailableReplicas: 2
```
**What did you expect to happen:**
I'd expect to have only control plane machine

**Anything else you would like to add:**

I'm not able to reproduce it again

cc @ncdc @detiber 

**Environment:**

- Cluster-api version: master
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
