### ISSUE TITLE
Proposal: Store Network Addresses on MachineStatus

### ISSUE THREAD

**Issue by dgoodwin** [kubernetes-sigs/cluster-api#234]
Would the concepts of public and private IP + DNS be universal enough to justify placing directly on the MachineStatus, rather than each cloud provider nesting within their providerConfig.

This information could theoretically be obtained by following the node reference, however there are a couple situations where that may not be possible:

- Adding machines may involve a period of time between when the machine is created, and the node joins the cluster. Controllers may even need to access that machine to get it to join the cluster in some implementations.
- In deployments involving a root cluster managing other clusters, machine records will exist but the node information is only in the remote cluster.

Despite the naming, re-use of an array of NodeAddress seems like it would be a consistent way to model the info as we do on Nodes: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L3514

**Comment by mrIncompetent** [comment]
Plus:
- In environments where the Instance would have more addresses than the Node actually reflects & the controller has no access to the addresses reflected by the kubelet (Thinking of NAT here).
- Debugging would be easier - in case the kubelet does not come up at all. 


> In deployments involving a root cluster managing other clusters, machine records will exist but the node information is only in the remote cluster.

Wouldn't it be cleaner if the Controller would have access to both - the "master" - for machines & the "minion" cluster for nodes?

**Comment by dgoodwin** [comment]
For our use case we do have access to both master+minion clusters in the controllers, but external tooling that wanted to drive off the cluster API machines may not.

**Comment by dgoodwin** [comment]
Proposal for MachineStatus.Addresses would look just like Node.Addresses, set if and when the actuator can resolve them.

```yaml
  status:                                              
    lastUpdated: 2018-05-30T12:28:46Z                                                                                                                         
    addresses:                                                                                                                             
    - address: 192.168.86.101                            
      type: InternalIP                      
    - address: 24.222.0.94                                                                                                               
      type: ExternalIP     
    - address: internal.com
      type: InternalDNS
    - address: external.example.com
      type: ExternalDNS     
```

@maisem regarding the idea to also allow these on the spec as requested addresses, if the MachineSpec can originate from MachineSets and MachineDeployments, is it acceptable to have the option to set Addresses on higher level multi-machine specs? Or would we perhaps validate that the MachineTemplateSpec on a MachineSet or MachineDeployment does not include Addresses, but you can use this field if creating an individual machine?
