### ISSUE TITLE
machineAutoscaler CRD

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/cluster-api#2369]
> ⚠️ Cluster API maintainers can ask to turn an issue-proposal into a [CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/YYYYMMDD-template.md) when necessary, this is to be expected for large changes that impact multiple components, breaking changes, or new large features.

***Goals***
1. Provide operators with an opt in mechanism for scalable resources i.e machineSet/machineDeployment to be considered for autoscaling.

***Non-Goals/Future Work***
1. Discuss cluster-api autoscaler provider logic.

**User Story**

1. As a user I want my cluster to be cost effective so I need my node groups to grow and shrink automatically according to the existing workload at anytime.

2. As an operator I want an opt in mechanism so I can choose which of the scalable resources i.e machineSet/machineDeployment in my cluster I want to be considered for autoscaling.

**Detailed Description**

If we add support for a cluster-api provider for the autoscaler we'll need an automated mechanism to let the autoscaler know which scalable resources it should take into consideration for autoscaling purposes.

This is to propose a new CRD `machineAutoscaler` along with a controller which targets individual scalable resources and annotates them appropriately so they can be recognised by a cluster-api autoscaler provider and taken into consideration for autoscaling.

```
nodeGroupMinSizeAnnotationKey = "cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size"

nodeGroupMaxSizeAnnotationKey = "cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size"
```
Aside from this concise RFE but dependent we'd like to find consensus to revive the PRs below, merge a cluster-api autoscaler provider which would support the >= v1alpha2 types and commit to its maintenance.
https://github.com/openshift/kubernetes-autoscaler/pull/118
https://github.com/kubernetes/autoscaler/pull/1866
https://github.com/kubernetes/enhancements/issues/609

**Contract changes [optional]**

[Describe contract changes between Cluster API controllers, if applicable.]

**Data model changes [optional]**
```
apiVersion: "cluster.x-k8s.io"
kind: "MachineAutoscaler"
metadata:
  name: "worker-us-east-1a" 
  namespace: "cluster-api"
spec:
  minReplicas: 1 
  maxReplicas: 12 
  scaleTargetRef: 
    apiVersion: cluster.x-k8s.io
    kind: MachineSet 
    name: worker-us-east-1a
```

/kind proposal
