### ISSUE TITLE
Validation/conversion malformed data testing plan

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#2437]
- Test v1alpha2 object with bogus json
- Test v1alpha2 object with valid json, but types that don't marshal into expected types
- Test v1alpha2 object with valid json, but failing openapi validation
- Test v1alpha2 object with valid json, but failing webhook validation

The goal is to make sure all of these are rejected and not valid. Most important thing is to make sure that invalid data isn't persisted in etcd.

/kind cleanup
/area testing
/milestone v0.3.0
/priority important-soon

**Comment by vincepri** [comment]
cc @liggitt

**Comment by sedefsavas** [comment]
Tested the following scenarios:

**Comment by ncdc** [comment]
@sedefsavas re the bogus json test, could you paste the yaml you tested? Thanks!

**Comment by sedefsavas** [comment]
@ncdc 
An example of bogus yaml that fails:
```
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: management-clusterx
  namespace: default
spec:
  clusterNetwork:
	pods:
      cidrBlocks:
      - 100.96.0.0/11
```
"pods" indentation is wrong.
```
error: error parsing v1alpha2.yml: error converting YAML to JSON: yaml: line 8: found character that cannot start any token
```

**Comment by ncdc** [comment]
@sedefsavas thanks. The first test case (bogus json) is not quite this. Instead, it's to have a resource where the `cluster.x-k8s.io/conversion-data` has invalid json, but the rest of the data is correct. We are trying to trigger an error e.g. here: https://github.com/kubernetes-sigs/cluster-api/blob/25a933a307b1495edc13f6bf7186c9d3328415e8/api/v1alpha2/conversion.go#L46-L47

**Comment by sedefsavas** [comment]
Ah, I see. Thanks!

Okay tested the following bogus json and it throws conversion error as expected:

```
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  annotations:
    cluster.x-k8s.io/conversion-data: "{\"metadata\":\"name\":\"test-1\",\"creationTimestamp\":null}"
  name: management-clusterx-controlplane-0
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: management-clusterx-controlplane-0
      namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: VSphereMachine
    name: management-clusterx-controlplane-0
    namespace: default
  version: 1.16.2
```
```
Error from server (InternalError): error when creating "v1alpha2yml": Internal error occurred: conversion webhook for cluster.x-k8s.io/v1alpha2, Kind=Machine failed: invalid character ':' after object key:value pair 
```
