### ISSUE TITLE
MachineDeployment phase and rolling update fails

### ISSUE THREAD

**Issue by jan-est** [kubernetes-sigs/cluster-api#2446]
**What steps did you take and what happened:**
This is similar to [#1049](https://github.com/kubernetes-sigs/cluster-api/issues/1049) but I still getting the issues with rolling update and also the phase of machinedeployment is not getting into **running** state. I can't find anywhere is this fixed of not.

While using following MachineDeployment the PHASE of the deployment never gets into running state. 

```
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: capi-quickstart-worker
  labels:
    cluster.x-k8s.io/cluster-name: capi-quickstart
    # Labels beyond this point are for example purposes,
    # feel free to add more or change with something more meaningful.
    # Sync these values with spec.selector.matchLabels and spec.template.metadata.labels.
    nodepool: nodepool-0
spec:
  clusterName: my-cluster
  replicas: 3
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: capi-quickstart
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: capi-quickstart
        nodepool: nodepool-0
    spec:
      clusterName: my-cluster
      version: v1.15.3
      bootstrap:
        configRef:
          name: capi-quickstart-worker
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: capi-quickstart-worker
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: DockerMachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: DockerMachineTemplate
metadata:
  name: capi-quickstart-worker
spec:
  template:
    spec: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: capi-quickstart-worker
spec:
  template:
    spec:
      # For more information about these values,
      # refer to the Kubeadm Bootstrap Provider documentation.
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
      clusterConfiguration:
        controllerManager:
          extraArgs:
            enable-hostpath-provisioner: "true"

```
After running machinedeployment list of ```machines``` looks as following:
```
kubectl get machines
NAME                                      PROVIDERID                                                      PHASE
capi-quickstart-controlplane-0            docker:////my-cluster-capi-quickstart-controlplane-0            Running
capi-quickstart-worker-6785bcbcbf-d2bpv   docker:////my-cluster-capi-quickstart-worker-6785bcbcbf-d2bpv   Running
capi-quickstart-worker-6785bcbcbf-jmrl8   docker:////my-cluster-capi-quickstart-worker-6785bcbcbf-jmrl8   Running
capi-quickstart-worker-6785bcbcbf-xksfz   docker:////my-cluster-capi-quickstart-worker-6785bcbcbf-xksfz   Running
```
And the status field of machinedeployment:
```
kubectl describe machinedeployment capi-quickstart-worker
Status:
  Observed Generation:   1
  Phase:                 ScalingUp
  Replicas:              3
  Selector:              cluster.x-k8s.io/cluster-name=my-cluster,nodepool=nodepool-0
  Unavailable Replicas:  3
  Updated Replicas:      3
```
After that I edit ```spec.version: v1.15.3 => v1.15.7``` and rolling update starts. 

**What did you expect to happen:**

After rolling update, expectation is to have a new replicaset with 3 running replicas with  ```spec.version: v1.15.7```. But after edit of machinedeployment this is what was detected:

```
kubectl get machines
NAME                                      PROVIDERID                                                      PHASE
capi-quickstart-controlplane-0            docker:////my-cluster-capi-quickstart-controlplane-0            Running
capi-quickstart-worker-6785bcbcbf-d2bpv   docker:////my-cluster-capi-quickstart-worker-6785bcbcbf-d2bpv   Running
capi-quickstart-worker-6785bcbcbf-jmrl8   docker:////my-cluster-capi-quickstart-worker-6785bcbcbf-jmrl8   Running
capi-quickstart-worker-6785bcbcbf-xksfz   docker:////my-cluster-capi-quickstart-worker-6785bcbcbf-xksfz   Running
capi-quickstart-worker-bb74bd4d9-x562p    docker:////my-cluster-capi-quickstart-worker-bb74bd4d9-x562p    Running
```
Only one new machine was created.

```
kubectl get machinedeployments
NAME                     PHASE       REPLICAS   AVAILABLE   READY
capi-quickstart-worker   ScalingUp   4 
```
machinedeployment PHASE status still in ScalingUp and replica count is the count of all replicas. 

```
kubectl describe machinedeployment capi-quickstart-worker
Status:
  Observed Generation:   2
  Phase:                 ScalingUp
  Replicas:              4
  Selector:              cluster.x-k8s.io/cluster-name=my-cluster,nodepool=nodepool-0
  Unavailable Replicas:  4
  Updated Replicas:      1
```
```
kubectl get machinesets
NAME                                AGE
capi-quickstart-worker-6785bcbcbf   15m
capi-quickstart-worker-bb74bd4d9    3m56s
```
New replicaset have only 1 replica:
```
kubectl describe machineset capi-quickstart-worker-bb74bd4d9
Name:         capi-quickstart-worker-bb74bd4d9
Namespace:    default
Labels:       cluster.x-k8s.io/cluster-name=my-cluster
              machine-template-hash=663068085
              nodepool=nodepool-0
Annotations:  machinedeployment.clusters.x-k8s.io/desired-replicas: 3
              machinedeployment.clusters.x-k8s.io/max-replicas: 4
              machinedeployment.clusters.x-k8s.io/revision: 2
API Version:  cluster.x-k8s.io/v1alpha3
Kind:         MachineSet
Metadata:
  Creation Timestamp:  2020-02-26T07:02:13Z
  Generation:          1
  Owner References:
    API Version:           cluster.x-k8s.io/v1alpha3
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  MachineDeployment
    Name:                  capi-quickstart-worker
    UID:                   dd75b777-ec6c-4c90-a07e-ecb27fcbdedf
  Resource Version:        278597
  Self Link:               /apis/cluster.x-k8s.io/v1alpha3/namespaces/default/machinesets/capi-quickstart-worker-bb74bd4d9
  UID:                     ce140253-ccb9-44e9-87c4-e1424fc5f5c2
Spec:
  Cluster Name:   my-cluster
  Delete Policy:  Random
  Replicas:       1
  Selector:
    Match Labels:
      cluster.x-k8s.io/cluster-name:  my-cluster
      Machine - Template - Hash:      663068085
      Nodepool:                       nodepool-0
  Template:
    Metadata:
      Labels:
        cluster.x-k8s.io/cluster-name:  my-cluster
        Machine - Template - Hash:      663068085
        Nodepool:                       nodepool-0
    Spec:
      Bootstrap:
        Config Ref:
          API Version:  bootstrap.cluster.x-k8s.io/v1alpha3
          Kind:         KubeadmConfigTemplate
          Name:         capi-quickstart-worker
      Cluster Name:     my-cluster
      Infrastructure Ref:
        API Version:  infrastructure.cluster.x-k8s.io/v1alpha3
        Kind:         DockerMachineTemplate
        Name:         capi-quickstart-worker
      Version:        v1.15.7
Status:
  Fully Labeled Replicas:  1
  Observed Generation:     1
  Replicas:                1
  Selector:                cluster.x-k8s.io/cluster-name=my-cluster,machine-template-hash=663068085,nodepool=nodepool-0
Events:
  Type    Reason            Age   From                   Message
  ----    ------            ----  ----                   -------
  Normal  SuccessfulCreate  26m   machineset-controller  Created machine "capi-quickstart-worker-bb74bd4d9-x562p"
```
**Environment:**

- Cluster-api version: ```current master```
- Minikube/KIND version: ```kind v0.6.1 go1.13.4 linux/amd64```
- Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-12-04T07:23:47Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- OS:
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)
```

/kind bug

**Comment by vincepri** [comment]
/assign 

I'll look into this today, one thing that I immediately noticed is that your MD status doesn't have AvailableReplicas

**Comment by vincepri** [comment]
@chuckha could this be a docker-related issue? I just tested CAPA and it seems to be working fine

```
$ k get machinedeployments
NAME         PHASE     REPLICAS   AVAILABLE   READY
test1-md-0   Running   2          2           2
```

/milestone v0.3.0
/priority awaiting-more-evidence

**Comment by jan-est** [comment]
Problem might be of using CAPD? @vincepri When you tested with CAPA did you have any problems with rolling update? I have a plan to start testing rolling update on baremetal, but first I would like to know if machinedeployment is running properly on CAPI level.

**Comment by chuckha** [comment]
It might be, I can look into it and see if this can be closed or not

/assign

**Comment by chuckha** [comment]
@jan-est You have to install a CNI to make machine deployment scaling work appropriately. It uses node Ready as a marker and that only ever becomes Ready AFTER CNI is installed.

**Comment by jan-est** [comment]
@chuckha thank you that shorted out the the State issue. Still have problems after changing spec.version and rolling update is started. I add following field on my machinedeployment:

```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
```
Before update my machinesets looks as follows:
```
kubectl get machinesets
NAME                                REPLICAS   AVAILABLE   READY
capi-quickstart-worker-6785bcbcbf   3          3           3
```
After update 
```
kubectl get machinesets
NAME                                REPLICAS   AVAILABLE   READY
capi-quickstart-worker-6785bcbcbf   2          2           2
capi-quickstart-worker-85b8bdc56    1 

```
I think this is not the state the cluster should stay after update. Update is only update 1 replica and leave two replicas running with old version?
