### ISSUE TITLE
Able to create a v1alpha3 machine without ClusterName by using v1alpha2 yaml

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#2518]
**What steps did you take and what happened:**
Applied the following v1alpha2 yaml to v1alpha3 controller. This yaml does not have a "cluster.x-k8s.io/cluster-name" label and "cluster.x-k8s.io/conversion-data" annotation which is supposed to hold v1alpha3 data is missing ClusterName too and it has an additional field that v1alpha3 Machine Spec does not have. Machine is created with clusterName: "".

```
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/control-plane: "true"
  annotations:
    cluster.x-k8s.io/conversion-data: "{\"metadata\":{\"name\":\"test-1\",\"creationTimestamp\":null,\"labels\":{\"label1\":\"\"}},\"spec\":{\"notClusterName\":\"cname\",\"bootstrap\":{},\"infrastructureRef\":{}},\"status\":{\"bootstrapReady\":true,\"infrastructureReady\":true}}"
  name: management-clusterx-controlplane-0
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: management-clusterx-controlplane-0
      namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: VSphereMachine
    name: management-clusterx-controlplane-0
    namespace: default
  version: 1.16.2
```

**What did you expect to happen:**
I expected it to be failed during creation.

**Environment:**

- Cluster-api version:  v0.3.0-rc.2

/kind bug
