### ISSUE TITLE
clusterctl: Allow set ImageRepository and ImageTag for certmanager

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#2555]
**User Story**

As an operator I would like to use my own image repository for the cert-manager

**Detailed Description**
The cert-manager manifest is embedded in clusterctl so it cannot be easily changed like e.g. provider manifests. So configuration flags are required to allow to set imageRepository/ImageTag (similar to ImageMeta for etcd/CoreDns in kubeadm)

**Anything else you would like to add:**
I prefer to use the config file vs flags because it makes the configuration persistent and it ensures consistency between init and upgrades. 
The configuration can be something similar (only the image overrides part): 
```
# custom providers
providers:
  - name: docker
    url: /Users/fpandini/.cluster-api/overrides/infrastructure-docker/latest/infrastructure-components.yaml
    type: InfrastructureProvider

# Values for env variables substitutes in provider assets
AWS_B64ENCODED_CREDENTIALS: xxxx

# image overrides
images:
  cert-manager:
    repository: us.gcr.io/myRepo/cluster-api
    tag: v0.13.5 
```

This can easily evolve into
```
images:
  all:
    repository: us.gcr.io/myRepo/cluster-api
  cert-manager:
    tag: v0.13.5 
```
Supporting overrides for all the components or into supporting more granular type of images mutation if the needs arise

/kind feature
/cc @vincepri 
/cc @ncdc
