### ISSUE TITLE
clusterctl local repository mode does not handle windows paths

### ISSUE THREAD

**Issue by vuil** [kubernetes-sigs/cluster-api#2658]
What steps did you take and what happened:
When setting up a local repository provider on windows and using windows style paths like so
```
providers:
  - name: cluster-api
    url: c:\Users\foo\.tkg\providers\cluster-api\v0.3.0\core-components.yaml
    type: CoreProvider
  - name: aws
    url: c:\Users\foo\.tkg\providers\infrastructure-aws\v0.5.0\infrastructure-components.yaml
    type: InfrastructureProvider
...
```

When using GetClusterTemplate to obtain a cluster template, an error is reported by clusterctl:
```
invalid provider url. there are no provider implementation for "c" schema"
```
because the url parsing library is interpreting c: as start of a url scheme

When using the file:/// scheme on windows like so

```
providers:
  - name: cluster-api
    url: file:///c:/Users/foo/.tkg/providers/cluster-api/v0.3.0/core-components.yaml
    type: CoreProvider
  - name: aws
    url: file:///c:/Users/foo/.tkg/providers/infrastructure-aws/v0.5.0/infrastructure-components.yaml
    type: InfrastructureProvider
```

we encounter another error from clusterctl library 
```
"file:///c:/Users/foo/.tkg/providers/infrastructure-vsphere/v0.6.0/infrastructure-components.yaml" must be an absolute path
```

What did you expect to happen:
clusterctl library should be able to process some path format that works for windows file systems.

Anything else you would like to add:
no
Environment:

Cluster-api version: 
/kind bug
/area clusterctl
/cc @fabriziopandini
