### ISSUE TITLE
KCP: defaulting webhooks add unspecified fields

### ISSUE THREAD

**Issue by sethp-nr** [kubernetes-sigs/cluster-api#2693]
Currently, when creating a KCP with a bare-bones spec, the defaulting webhook adds some fields not specified by the user:

```
   kubeadmConfigSpec:
      clusterConfiguration:
        apiServer: {}
        certificatesDir: ""
        controlPlaneEndpoint: ""
        controllerManager: {}
        dns: {}
        etcd: {}
        imageRepository: ""
        kubernetesVersion: ""
        networking:
          podSubnet: ""
        scheduler: {}
      initConfiguration:
        localAPIEndpoint:
          advertiseAddress: ""
          bindPort: 0
        nodeRegistration:
          kubeletExtraArgs:
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
```

This behavior appears to be occurring because the `encoding/json` package doesn't know how to omit empty structs, like `nodeRegistrationOptions`. We didn't like the ergonomics of custom json serialization, but changing the struct fields to be pointers breaks go clients, so this issue is on hold until work starts on a 0.4.x series.

This issue is a follow-up from #1941 and #2678.

**Comment by vincepri** [comment]
/assign @fabriziopandini 
/priority backlog
To look into.

**Comment by vincepri** [comment]
@fabriziopandini to take a look or remove from milestone if something else takes precendence

**Comment by fabriziopandini** [comment]
@vincepri @CecileRobertMichon I have checked this issue and I'm +1 to remove release blocking / punt to a next release.

As of today almost all the fields defaulting to empty string are not showing up anymore, but however we have have still empty struct still showing up (here an example):

```
kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
      dns: {}
      etcd: {}
      networking: {}
      scheduler: {}
    initConfiguration:
      localAPIEndpoint:
        advertiseAddress: ""
        bindPort: 0
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    joinConfiguration:
      discovery: {}
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
```

I'm going to check the latest empty string showing up (advertiseAddress) as well as `bindPort: 0`; instead for the empty struct in order to get rid of them we have to convert all current fields to pointers, but I'm not sure we want really to do so (or when).
