### ISSUE TITLE
CACPK and machine deployments modify the infrastructure version

### ISSUE THREAD

**Issue by maelk** [kubernetes-sigs/cluster-api#2774]
**What steps did you take and what happened:**
In a setup where two versions of the Infrastructure provider are matching the contract for v1alpha4, namely v1alpha3 and v1alpha4, if the Infrastructure template is given with v1alpha4, the machineDeployment will create a machineset referencing the infrastructure template with v1alpha3. A similar issue is observed with CACPK, even though it is not a machineDeployment.

**What did you expect to happen:**
I would expect the infrastructure template to still be referred as v1alpha4.

**Anything else you would like to add:**

```yaml
  apiVersion: cluster.x-k8s.io/v1alpha3
  kind: MachineDeployment
  metadata:
    name: test1-md-0
    namespace: default
  spec:
    template:
      spec:
        infrastructureRef:
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
          kind: Metal3MachineTemplate
          name: test1-md-0
          namespace: default
        version: v1.16.0
```

and the machine set:

```yaml
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineSet
metadata:
  name: test1-md-0-657dd6cfbc
  namespace: default
spec:
  template:
    spec:
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: Metal3MachineTemplate
        name: test1-md-0
        namespace: default
      version: v1.16.0
```

**Environment:**

- Cluster-api version: v0.3.2
- Minikube/KIND version: Kind 0.7.0
- Kubernetes version: (use `kubectl version`): 1.17.0
- OS (e.g. from `/etc/os-release`):

/kind bug
