### ISSUE TITLE
Expand test framework to include upstream k8s testing

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api#2826]
> ⚠️ Cluster API maintainers can ask to turn an issue-proposal into a [CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/YYYYMMDD-template.md) when necessary, this is to be expected for large changes that impact multiple components, breaking changes, or new large features.

ie. Use CAPI to test Kubernetes

***Goals***
1. Use CAPX as deployer to test upstream k/k changes
2. Use CAPX as deployer to test k8s-sigs projects such as out-of-tree cloud providers
3. Run upstream k8s conformance tests against CAPI  
4. Encourage reuse across different infra providers instead of maintaining bash scripts in each in provider repo (right now there are scripts in [CAPG](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/master/hack/ci/e2e-conformance.sh), [CAPA](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/hack/ci/e2e-conformance.sh), and [CAPZ](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/3514be2ef30d6f3d1473507c3f0065a68c5f921e/scripts/ci-conformance.sh), with significant overlap). We intend to extend the current test/framework to allow this proposal to be implemented there.

***Non-Goals/Future Work***
1. Add a [kubetest](https://github.com/kubernetes/test-infra/tree/master/kubetest) deployer for CAPI. 
2. Run the tests as PR gates on k/k.

**User Story**

As a developer I would like to run k/k E2E tests on a CAPI cluster to test changes made to a k8s component.

**Detailed Description**

**NOTE** : this is a very rough draft based on working group meeting (recording [here](https://zoom.us/rec/share/5cUqHbSr-EdOerPzy2TSdLMzNd3veaa8gSgf_6VemUmSgjgL32P1a3qukohCdU96?startTime=1585600340000)). Will evolve this as we continue the discussion with the wider community and come up with implementation details. Just hoping to get the discussion started with this issue.

1. Build k/k binaries (e2e.test, kubectl, ginkgo)
2. (optionally) build k8s component images from private SHA (if the images aren't already available on a registry)
3. Create a cluster with custom k8s binaries & container images
      In order to use a custom k8s build (example k/k master), there are a few different options:
- Build a custom image with image-builder as part of CI and use that image in the cluster
    - pros: can reuse the image for multiple nodes
    - cons: time consuming, building a VM image with packer takes ~20 minutes
- Use an existing image (possibly with a different k8s version) and in the KubeadmConfig pass in a PreKubeadmCommand script to replace the k8s version with the one we want.
    - pros: doesn't require building an image, faster
    - cons:  we have to do this for every vm, hacky (bash script might be error prone), different from user experience with capi (with images)
- Modify capi infra providers to take custom k8s component images
     - pros: can be reused more easily by users not familiar with the project and CI, doesn't require the preKubeadm "hack" script, or reusing a VM image.
    - cons: more work and changes involved.

4. Run tests suite: k/k E2E, cloud provider E2E, other k8s-sigs E2E, etc.

related to #2141, which might overlap in implementation details but has different objectives: #2141 aims to test if capi/capz/capa/capv/capg/etc passes k8s conformance whereas this proposal would be to use CAPI as a dev tool to test k8s and k8s-sigs changes.

/kind proposal

cc @dims @vincepri @alexeldeib @fabriziopandini @ritazh @chewong  @randomvariable @rbitia

**Comment by vincepri** [comment]
Thanks for the write-up Cecile!

I'd expand the 4th goal mentioning we intend to extend the current `test/framework` to allow this proposal to be implemented there.

 > Modify capi infra providers to take custom k8s component images

Would this entail changes to image-builder to take some custom scripts that can setup images in a custom fashion? We should probably tackle this separately, it's a really interesting idea and would make the images generic, although I assume folks will probably need internet access so it might not work in every environment.

**Comment by timothysc** [comment]
> Modify capi infra providers to take custom k8s component images
pros: can be reused more easily by users not familiar with the project and CI, doesn't require the preKubeadm "hack" script, or reusing a VM image. 

+1 ^ this is generally more useful for testing, but I still see a problem with the kubelet.  You can override almost everything else, but the kubelet running on the base OS built by the image builder is not easily replaced unless you combined a rpm/deb update/install on cloud-init.

**Comment by CecileRobertMichon** [comment]
@vincepri @timothysc what I meant by 
> Modify capi infra providers to take custom k8s component images

Is that instead of using `preKubeadmCommand` to pass in the [script](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/471/files#diff-99798beff3df309ff795d5258279b0a3R15) that overrides the k8s version, we add a new property, maybe under a feature gate, to pass in a "custom"  k8s version (what we call `CI_VERSION` in the script above, or custom k8s components images, and run a script to install that version on the VMs before running the bootstrap script or as part of the bootstrap script. 

A better place for this might actually be the bootstrap provider, not the infra providers now that I think about it. @vincepri I don't think this entails changes to image builder as I'm not talking about building any new images but rather using cloud init to install k8s components during provisioning. This does require internet access but so does our current `preKubeadmCommand` solution. The advantage here is that it would be more reusable and we could use it with a combination of a user  `preKubeadmCommand`. 

@timothysc for kubelet we'd need to do a `systemctl restart kubelet` after installing the desire kubelet binary, just like we do it in the preKubeadmCommand [right now](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/release-0.4/hack/ci/ci-bootstrap.yaml#L73).

The other possibility is to change kubeadm to allow passing in custom component images (if it's not already supported, I don't think it is from what I've seen). So your kubeadm config would look something like:

```
kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data["local_hostname"] }}'
        customKubeletVersion: v1.19.0-alpha.1.175+7b1a531976be0d
        kubeletExtraArgs:
          cloud-provider: azure
          cloud-config: /etc/kubernetes/azure.json
    joinConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data["local_hostname"] }}'
        kubeletExtraArgs:
        customKubeletVersion: v1.19.0-alpha.1.175+7b1a531976be0d
          cloud-provider: azure
          cloud-config: /etc/kubernetes/azure.json
    clusterConfiguration:
      apiServer:
        timeoutForControlPlane: 20m
        customImage: myDockerHubUser/custom-api-server-build:v1.19.0-dirty
        extraArgs:
          cloud-provider: azure
          cloud-config: /etc/kubernetes/azure.json
        extraVolumes:
           - [...]
      controllerManager:
        customImage: myDockerHubUser/custom-controller-manager-build:v1.19.0-dirty
        extraArgs:
          cloud-provider: azure
          cloud-config: /etc/kubernetes/azure.json
          allocate-node-cidrs: "false"
        extraVolumes:
          - [...]
```

And have kubeadm pull the right images / components before init/join in cloud init. Basically I'm just trying to think of ways we can build a k8s cluster with custom builds of various k8s components installed without having to build VM images in every test.
