### ISSUE TITLE
provider implementers guide needs to be updated for apply the contract version label

### ISSUE THREAD

**Issue by yongxiu** [kubernetes-sigs/cluster-api#3039]
**What steps did you take and what happened:**
I followed the steps in https://github.com/kubernetes-sigs/cluster-api/tree/master/docs/book/src/developer/providers/implementers-guide

source code: https://github.com/liztio/cluster-api-provider-mailgun

**What did you expect to happen:**
mailgun email received.

**Anything else you would like to add:**

I met error in capi-system\capi-controller-manager-6d7b58b889-5mbfg pod:

`
E0509 03:06:56.435811       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to find a CustomResourceDefinition for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=MailgunCluster with contract \"cluster.x-k8s.io/v1alpha3\""  "controller"="cluster" "request"={"Namespace":"default","Name":"hello-mailgun"}
`

And in pod cluster-api-provider-mailgun-system\cluster-api-provider-mailgun-controller-manager-79c644b8975dnzc , the error is:
`
ERROR   controller-runtime.controller   Reconciler error        {"controller": "mailguncluster", "request": "default/hello-mailgun", "error": "failed to retrieve cluster: {Name:hello-mailgun GenerateName: Namespace:default SelfLink:/apis/infrastructure.cluster.x-k8s.io/v1alpha3/namespaces/default/mailgunclusters/hello-mailgun UID:e5684416-9d10-47ec-84fe-b96a236f2dde ResourceVersion:116159 Generation:1 CreationTimestamp:2020-05-09 00:31:45 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"infrastructure.cluster.x-k8s.io/v1alpha3\",\"kind\":\"MailgunCluster\",\"metadata\":{\"annotations\":{},\"name\":\"hello-mailgun\",\"namespace\":\"default\"},\"spec\":{\"priority\":\"ExtremelyUrgent\",\"request\":\"Please make me a cluster, with sugar on top?\",\"requester\":\"cluster-admin@example.com\"}}\n] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName: ManagedFields:[{Manager:kubectl Operation:Update APIVersion:infrastructure.cluster.x-k8s.io/v1alpha3 Time:2020-05-09 00:31:45 +0000 UTC Fields:nil}]}"}
`

The cluster yaml file is the example

```
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: hello-mailgun
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MailgunCluster
    name: hello-mailgun
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MailgunCluster
metadata:
  name: hello-mailgun
spec:
  priority: "ExtremelyUrgent"
  request: "Please make me a cluster, with sugar on top?"
  requester: "cluster-admin@example.com"
```

**Environment:**

- Cluster-api version: v0.3.5
- Minikube/KIND version: kind v0.8.0 go1.14.2 linux/amd64
- Kubernetes version: (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): Debian 10

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
