### ISSUE TITLE
Cluster API fails to propagate network setting into the KubeadmConfig

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3149]
**What steps did you take and what happened:**
from [slack](https://kubernetes.slack.com/archives/C8TSNPY4T/p1591319828427800)

Here is my cluster spec:
```
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 172.20.0.0/16
      - fd03:beef:beef:beef::/120
    services:
      cidrBlocks:
      - 192.20.0.0/16
      - fd02:beef:beef:beef::/110
```
But master provisioning is failing. Here is error message from /var/log/cloud-init-output.log
```
[serviceSubnet: Invalid value: "192.20.0.0/16fd02:beef:beef:beef::/110": failed to parse cidr value:"192.20.0.0/16fd02:beef:beef:beef::/110" with error:invalid CIDR address: 192.20.0.0/16fd02:beef:beef:beef::/110, podSubnet: Invalid value: "172.20.0.0/16fd03:beef:beef:beef::/120": failed to parse cidr value:"172.20.0.0/16fd03:beef:beef:beef::/120" with error:invalid CIDR address: 172.20.0.0/16fd03:beef:beef:beef::/120]
```

**What did you expect to happen:**
The kubeadm config get properly generate and kubeadm init to complete

**Anything else you would like to add:**
Most probably the error is due to 
https://github.com/kubernetes-sigs/cluster-api/blob/256bfc03ae58495e5ac6d48ab5a20b6af2369cb4/api/v1alpha3/cluster_types.go#L98
(this should produce a comma-separated list)
However, before doing the change, we should verify if this function is used elsewhere.

As a workaround, it is possible to set the network setting in the kubeadm config (this will take precedence on the values from cluster)

/kind bug
