### ISSUE TITLE
[ClusterResourceSet] Use slices instead of maps in CRSBinding

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api#3297]
Currently, to represent ClusterRecourcesetBinding,  a map of maps are being used:
```
clusterresourcesetmap:
 clusterResourceSet1:
    resources:
      Secret/secret1:
        hash: _IcfqGpJWlhS5Az06XX4A6BXcTA=
        lastAppliedTime: "2020-05-28T08:51:06Z"
        successful: true
  clusterResourceSet1:
    resources:
      Configmap/cm1:
        hash: _IcfqGpJWlhS5Az06XX4A6BXcTA=
        lastAppliedTime: "2020-05-28T08:51:06Z"
        successful: false
```

The initial reason of using maps was because CRSBinding was auto-generated and at each reconcile, we are checking if a resource is applied to a cluster or not by looking at its CRSBinding. To avoid slice iteration, we used maps but we can use slices instead to be inline with api conventions https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#lists-of-named-subobjects-preferred-over-maps

Another benefit of using slices is we can avoid creating new naming conventions such as ` Secret/secret1`.

/milestone v0.3.7
