### ISSUE TITLE
Allow latest in local provider

### ISSUE THREAD

**Issue by andrewrynhard** [kubernetes-sigs/cluster-api#3494]
**User Story**

As a developer I would like to use the tag "`latest`" when developing with a local `components.yaml`.

**Detailed Description**
With the following config  (`~/.cluster-api/clusterctl.yaml`):

```yaml
providers:
  - name: "sidero"
    url: "file:///home/andrewrynhard/sidero/_out/infrastructure-sidero/latest/infrastructure-components.yaml"
    type: "InfrastructureProvider"
```

I would like to run `clusterctl init` like so:

```bash
clusterctl --kubeconfig kubeconfig init -i "sidero" -b "talos" -c "talos"
```
but this seems to be invalid. I am seeing this error https://github.com/kubernetes-sigs/cluster-api/blob/32899ad267dbb89208aec074c412d8f2055bd159/cmd/clusterctl/client/repository/repository_local.go#L222
This makes local development a bit easier.

/kind feature

**Comment by fabriziopandini** [comment]
@andrewrynhard I'm using latest locally and it works
```
providers:
  - name: docker
    url: /Users/fpandini/.cluster-api/local-repo/infrastructure-docker/latest/infrastructure-components.yaml
    type: InfrastructureProvider
```
My only suggestion is to check if under //home/andrewrynhard/sidero/_out/infrastructure-sidero/ there is a folder with a semantic version number as a name

/priority awaiting-more-evidence
