### ISSUE TITLE
GetClusterTemplate can not parse the cluster template when the value of kind CR property has a special character

### ISSUE THREAD

**Issue by luniHw** [kubernetes-sigs/cluster-api#3807]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Define a kind CR, it has a folder property. When the folder values is K8 VM's, the interface GetClusterTemplate returns error

**What did you expect to happen:**
1. Can GetClusterTemplate support the special characters, eg: ' & * !, etc
2. For template parse, are there some constraints about expression on the value of properties.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The error as below:
failed to parse yaml: failed to unmarshal the 2nd yaml document: "apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3\nkind: HAProxyLoadBalancer\nmetadata:\n  labels:\n    cluster.x-k8s.io/cluster-name: 'mgmt-tkg113'\n  name: 'mgmt-tkg113-tkg-system'\n  namespace: 'tkg-system'\nspec:\n  user:\n    authorizedKeys:\n    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Wxt43NVeYRceM+zLJhb0M9L0JoFoswXJbw1v9MxL/y72aKWQs7MTCUgJHzcReOFzQyetLRar/HDPAarXmjXMuaDQfXN+P2D1x6VKY3UpempeewH4x8v6DlPkvlP/BciYyXw5HauxLj2bSxSzDlvsWnemXz7cEuSb7KLI8/3pcVtWZCcnyU5oUuWV0acrBa64ZHsKim/PXD1f2kajQ5AuJX61WGfP9TyIsU1BbBx18448WL3RKV5hnjbC3axOD1o3HDI9LVO3R4GGyDoZ2KvxXE4AYVaosGCjiwWx9TAZ+1+kaUo7pfpxP1qGDptcUFmk9j/NzI/ZL5e03SiCfwsL root@bootstrapper\n'\n    name: capv\n  virtualMachineConfiguration:\n    cloneMode: fullClone\n    datacenter: 'os-test-dc'\n    datastore: 'sharedVmfs-0'\n    diskGiB: 20\n    folder: 'K8 VM's'\n    memoryMiB: 4096\n    network:\n      devices:\n      - dhcp4: true\n        networkName: 'VM Network'\n    numCPUs: 2\n    resourcePool: 'tkg113'\n    server: '192.168.111.107'\n    template: 'photon-3-haproxy-v1.2.4+vmware.1'\n": error converting YAML to JSON: yaml: line 18: did not find expected key

**Environment:**

- Cluster-api version: v0.3.9
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by fabriziopandini** [comment]
cc @wfernandes 
/priority important-soon
/milestone v0.3.11

**Comment by wfernandes** [comment]
/assign
I'll take a look into this.

**Comment by wfernandes** [comment]
So after looking into this, I don't believe this to be a problem in our parsing but rather the way the original yaml is formatted.

From the example above we have,
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: HAProxyLoadBalancer
...
 folder: 'K8 VM's'
...
```
This property `folder: 'K8 VM's'` should technically be wrapped in double quotes.

I wrote a test to reproduce this problem described above. When I replaced the single quotes to double as shown below, we were able to parse the yaml correctly.

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: HAProxyLoadBalancer
metadata:
 labels:
 cluster.x-k8s.io/cluster-name: "mgmt-113"
 name: "mgmt-113-foo-system"
 namespace: "foo-system"
spec:
 user:
 authorizedKeys:
 - "stuff\n "
 name: capv
 virtualMachineConfiguration:
 cloneMode: fullClone
 datacenter: "os-test-dc"
 datastore: "sharedVmfs-0"
 diskGiB: 20
 folder: "K8 VM's"
 memoryMiB: 4096
 network:
 devices:
 - dhcp4: true
 networkName: "VM Network"
 numCPUs: 2
 resourcePool: "tkg113"
 server: "0.0.0.0"
 template: "photon-3-haproxy-v1.2.4"
```
