### ISSUE TITLE
Image tag is not considered during clusterctl upgrade

### ISSUE THREAD

**Issue by jan-est** [kubernetes-sigs/cluster-api#3834]
**What steps did you take and what happened:**
I was testing clusterctl ability to upgrade cert-manager. Purpose was to find out if user could use own cert-manager images from private repository. 

My assumption was that in given config.yaml the image tag and repository should be considered during both `clusterctl init` and `clusterctl upgrade`, but the image tag and repository is currently ignored during clusterctl upgrade (plan and apply).

```
providers:
- name: "docker"
  type: "InfrastructureProvider"
  url: "/home/jan/.cluster-api/dev-repository/infrastructure-docker/v0.3.8/infrastructure-components.yaml"
overridesFolder: "/home/jan/.cluster-api/dev-repository/overrides"
images:
  cert-manager:
    tag: v0.15.2
    repository: quay.io/jetstack
```
Here is the steps I did while testing:

- I used known image` tag: v0.15.2` and repo `repository: quay.io/jetstack` for the test.  
- After `clusterctl init` cert-manager was using version `v0.15.2`
- I changed `tag: v0.15.2 `to `v1.0.3`
- When running `clusterctl upgrade plan` got:
```
  Checking cert-manager version...
  Cert-Manager is already up to date
```

**What did you expect to happen:**

I expect clusterctl upgrade to check the given cert-manager version from config.yaml and upgrade if version is different than one running in the cluster.  

**Environment:**

- Cluster-api version: 
v0.3.10

- Minikube/KIND version: 
kind v0.9.0 go1.15.2 linux/amd64

- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):
18.04.5 LTS (Bionic Beaver)
/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
