### ISSUE TITLE
Integrate kubeconfig with “ArgoCD cluster” configuration

### ISSUE THREAD

**Issue by MPV** [kubernetes-sigs/cluster-api#3866]
**User Story**

- As a operator I would like to be able to smoothly integrate Cluster-API with ArgoCD, so that: 
   - ...when a new cluster is created as part of ArgoCD deploying the CAPx manifests for creating my target cluster, it could automatically be added as a new "ArgoCD cluster" (a Kube secret with certain annotations/fields), so that:
      - ...I could subsequently automatically deploy applications into my new target cluster from ArgoCD.

**Detailed Description**

Today I can configure a new cluster in ArgoCD like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mycluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: mycluster.com
  server: https://mycluster.com
  config: |
    {
      "bearerToken": "<authentication token>",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64 encoded certificate>"
      }
    }
```

But I would like to deploy both my cluster and it's target apps using the same git commit, and let ArgoCDs reconcile loop eventually give me a cluster with the desired apps deployed into it. 

But since ArgoCDs cluster definition contains kubeconfig details that aren't known until the cluster is created, something might need to change to make this possible. 

I've asked for the equivalent over at ArgoCD: https://github.com/argoproj/argo-cd/issues/4651

**Anything else you would like to add:**

Would you be open for a collaboration with ArgoCD devs around this, as they suggested here: https://github.com/argoproj/argo-cd/issues/4651#issuecomment-715616247

I'm looking for something like what is shown in this video (which I already have working), but with the addition of automatically deploying apps (in my case using ArgoCD) into the newly created cluster, just after its creation:

https://youtu.be/9pFBgxDa7Aw

/kind feature
