### ISSUE TITLE
Wrong etcd listen-metrics-urls customization for second and further controlPlane nodes

### ISSUE THREAD

**Issue by maximsnezhkov** [kubernetes-sigs/cluster-api#4024]
**What steps did you take and what happened:**
I use local managment cluster based on minukube. Trying to customize `listen-metrics-urls` for etcd with following kcp config
```yaml
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: maxim-test
  namespace: default
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: VSphereMachineTemplate
    name: maxim-test
  kubeadmConfigSpec:
    clusterConfiguration:
      etcd:
        local:
          imageTag: "3.4.13-0"
          extraArgs:
            listen-metrics-urls: "http://{{ ds.meta_data.local_ipv4 }}:2381"
```
The problem is that `ds.meta_data.local_ipv4` is expanded the same for second and further nodes. And has the ip address of the first node.

first node:
```bash
$ ssh 10.10.10.2
$ sudo grep listen-metrics-urls /etc/kubernetes/manifests/etcd.yaml
    - --listen-metrics-urls=http://10.10.10.2:2381
$
Connection to 10.10.10.2 closed.
```
second node:
```bash
$ ssh 10.10.10.3
$ sudo grep listen-metrics-urls /etc/kubernetes/manifests/etcd.yaml
    - --listen-metrics-urls=http://10.10.10.2:2381
$
Connection to 10.10.10.3 closed.
```

**What did you expect to happen:**
I expect that `ds.meta_data.local_ipv4` will be expanded in a different ip address on second and further nodes.

**Anything else you would like to add:**
As a workaround now I set
```yaml
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: maxim-test
  namespace: default
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: VSphereMachineTemplate
    name: maxim-test
  kubeadmConfigSpec:
    clusterConfiguration:
      etcd:
        local:
          imageTag: "3.4.13-0"
          extraArgs:
            listen-metrics-urls: 'http://0.0.0.0:2381'
```

**Environment:**
Management cluster:
- Cluster-api version: 0.3.12
- Minikube/KIND version: v1.15.1
- Kubernetes version: (use `kubectl version`): v1.19.4
- OS (e.g. from `/etc/os-release`): official CAPV OVA image - ubuntu-1804-kube-v1.19.1

/kind bug

**Comment by maximsnezhkov** [comment]
The same way wrong customization for liveness/startup probe for second node.
`10.10.10.2` instead of `10.10.10.3`:

```yaml
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 10.10.10.2
        path: /health
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
...
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 10.10.10.2
        path: /health
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
```
