### ISSUE TITLE
why machinedeployment is not described in cluster spec

### ISSUE THREAD

**Issue by lojies** [kubernetes-sigs/cluster-api#4134]
**User Story**

I'm a fresher of cluster api. Now i'm a little uncertainty about cluster definition.Why machinedeployment is not described in cluster spec.I think adding this to cluster info can make a cluster info more complete.Now machinedeployment is more likely not a part of the whole cluster.

**Detailed Description**
```yaml
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: capi-mycluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: capi-mycluster-control-plane
  nodeRef:
     apiVersion: cluster.x-k8s.io/v1alpha3
     kind: MachineDeployment
     name: capi-mycluster-md-0
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: OpenStackCluster
    name: capi-mycluster
```

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature
