### ISSUE TITLE
controller-runtime/manager/controller/cluster "msg"="Reconciler error" "error"="cannot find any versions matching contract \"cluster.x-k8s.io/v1alpha4\" for CRD 

### ISSUE THREAD

**Issue by binchenX** [kubernetes-sigs/cluster-api#4263]
Disclaimer:  I'm not entirely sure if this is a bug or it is me miss something. I was following the [guide](https://cluster-api.sigs.k8s.io/developer/providers/implementers-guide/overview.html) to create a customer infrastructure provider (using `zks` as prefix for the resources and the controller as you will see in the detail report). I was able to get the crd installed, customer resource created and the controller running *mostly* correct but failed at the stage trying to get the owner of the cluster - which involves the specific behaviour of the capi-controller. 

the tldr version of the issue is I saw this error and I think it prevented the capi controller doing its job.

>➜    ✗ k logs -f capi-controller-manager-568c45f94d-5l9hp manager --namespace capi-system
E0308 07:53:27.352172       1 controller.go:301] controller-runtime/manager/controller/cluster "msg"="Reconciler error" "error"="cannot find any versions matching contract \"cluster.x-k8s.io/v1alpha4\" for CRD zksclusters.infrastructure.cluster.x-k8s.io" "name"="work-cluster-zks" "namespace"="default" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster" 

I'm thinking I must miss something obviously as someone novice on this and an expert may be able to pointed out issue right away :)  Appreciate any help on this.

## Problem

In the provider(zks) cluster controller, it failed to get the "owner" cluster.

## Details 

1. from zkscluster_controller, it can't get the "owner" cluster

```
2021-03-08T18:49:20.713+1100    INFO    controllers.ZksCluster  get zksCluster  {"number of control plane nodes": 2}                              │t, metadata.Name)
2021-03-08T18:49:20.713+1100    INFO    controllers.ZksCluster  Waiting for Cluster Controller to set OwnerRef on ZksCluster 
```
The zkscluster_controller Reconcile function is as simple as:

```
func (r *ZksClusterReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
	ctx := context.Background()
	_ = r.Log.WithValues("zkscluster", req.NamespacedName)

	// get the zkscluster and thus all its nodes
	zksCluster := &infrastructurev1alpha4.ZksCluster{}
	if err := r.Client.Get(ctx, req.NamespacedName, zksCluster); err != nil {
		if apierrors.IsNotFound(err) {
			return ctrl.Result{}, nil
		}
		return ctrl.Result{}, err
	}

	// print out the machine
	r.Log.Info("get zksCluster", "number of control plane nodes", len(zksCluster.Spec.ControlPlaneMachines))

	// get the Cluster.
	cluster, err := util.GetOwnerCluster(ctx, r.Client, zksCluster.ObjectMeta)
	if err != nil {
		return ctrl.Result{}, err
	}
	if cluster == nil {
		r.Log.Info("Waiting for Cluster Controller to set OwnerRef on ZksCluster")
		return ctrl.Result{}, nil
	}

	r.Log.Info("get Cluster", "controlPlaneEndpoint", cluster.Spec.ControlPlaneEndpoint.Host)
	// get the cluster and the controlplane config embedded

	return ctrl.Result{}, nil
}
```

My understanding is it is the `capi-controller`s ["responsiblity to make it happen"](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/cluster.html):

>Setting an OwnerReference on the infrastructure object referenced in Cluster.Spec.InfrastructureRef.

And in the `cluster` resouce, we do set the `infrastructureRef` as below:

```
 apiVersion: cluster.x-k8s.io/v1alpha4
  kind: Cluster
  metadata:
    name: work-cluster-zks
    namespace: default
  spec:
    controlPlaneEndpoint:
      host: dev.k8s.cba.com
      port: 443
    clusterNetwork:
      pods:
        cidrBlocks:
        - 192.168.0.0/16
      serviceDomain: cluster.local
      services:
        cidrBlocks:
        - 10.128.0.0/12
    controlPlaneRef:
      apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
      kind: KubeadmControlPlane
      name: work-cluster-zks-control-plane
      namespace: default
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
      kind: ZksCluster
      name: work-cluster-zks
      namespace: default
```

And the "corresponding" `Zkscluster` resource:

```
 apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
  kind: ZksCluster
  metadata:
    name: work-cluster-zks
    namespace: default
  spec:
    controlPlaneMachines:
      - name: global
        ip: 10.81.1.1
        flavor: baremetal
        imageId: hostos-node-v0.1.0
        ironicId: "ironic-id-global"
        userdata: "userdata"
      
```
see also:

```
➜  cluster-api-provider-zks git:(master) ✗ k get zkscluster --namespace default
NAME               AGE
work-cluster-zks   112s
➜  cluster-api-provider-zks git:(master) ✗ k get cluster --namespace default   
NAME               PHASE
work-cluster-zks   Provisioning
```
2. in the `capi-controller`, I saw following errors:

```
➜  dev-repository git:(zks) ✗ k logs -f capi-controller-manager-568c45f94d-5l9hp manager --namespace capi-system
E0308 07:53:27.352172       1 controller.go:301] controller-runtime/manager/controller/cluster "msg"="Reconciler error" "error"="cannot find any versions matching contract \"cluster.x-k8s.io/v1alpha4\" for CRD zksclusters.infrastructure.cluster.x-k8s.io" "name"="work-cluster-zks" "namespace"="default" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster" 
```

I'm not sure how I should interpret this - I'm quite new to the crd but I think this is something related version conversion? I also followed the [instruction](https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html#upgrade-to-crd-v1) of upgrading the crd version to v1 but didn't help.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: master 
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
