### ISSUE TITLE
MachinePool reporting `Ready` as true if infrastructure ref isn't found

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api#4311]
**What steps did you take and what happened:**
I have a typo for the **infrastructureRef** on a **MachinePool** so:

1. Created a `MachinePool` using an infrastructure ref for CAPA:

```
apiVersion: exp.cluster.x-k8s.io/v1alpha3
kind: MachinePool
metadata:
  name: "wkp-mgmt01-pool-0"
spec:
  clusterName: "wkp-mgmt01"
  replicas: 2
  failureDomains:
    - eu-west-2c
  template:
    spec:
      clusterName: "wkp-mgmt01"
      bootstrap:
        dataSecretName: ""
      infrastructureRef:
        name: "wpk-mgmt01-pool-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSManagedMachinePoolyaml
```
2.  Due to a typo the infrastructure ref name (`wpk-mgmt01-pool-0`) is incorrect and there is no match
3. If i have a wait on the `Ready` condition of the `MachinePool` is showing ready is true:
![image](https://user-images.githubusercontent.com/198425/111148068-1b4a5b80-8583-11eb-8fb6-2d71d81b7cd2.png)
4. And then if i describe the MachinePool you set the ready condition is true and the phase is provisioning:
![image](https://user-images.githubusercontent.com/198425/111148206-43d25580-8583-11eb-848f-22073d90b2b2.png)

**What did you expect to happen:**
I would expect the ready condition on the MachinePool to be false and an event written indicating that infrastructure ref can't be found.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 0.3.14
- Minikube/KIND version: 0.10.0
- Kubernetes version: (use `kubectl version`): 1.18
- OS (e.g. from `/etc/os-release`): Linux

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
