### ISSUE TITLE
'conditions.InfrastructureReady' doesn't match 'status.Infrastructure Ready' during cluster deletion

### ISSUE THREAD

**Issue by lubronzhan** [kubernetes-sigs/cluster-api#4364]
**What steps did you take and what happened:**
Hard to reproduce, when deleting 200 clusters, only 4 of them ran into this issue.

When deleting cluster, I have a finalizer on the cluster that blocks deleting. And a controller should remove that finalizer if cluster is in `conditions.Ready = true` state, however I checked the cluster status, even though the cluster status is `Infrastructure Ready:  true`, but inside `status.conditions.InfrastructureReady` is false, thus making the `condition.ready` false. So the deletion was stuck.

```
  Conditions:
    Last Transition Time:     2021-03-18T11:32:49Z
    Reason:                   Deleting
    Severity:                 Info
    Status:                   False
    Type:                     Ready
    Last Transition Time:     2021-03-17T08:18:06Z
    Status:                   True
    Type:                     ControlPlaneReady
    Last Transition Time:     2021-03-18T11:32:49Z
    Reason:                   Deleting
    Severity:                 Info
    Status:                   False
    Type:                     InfrastructureReady
  Control Plane Initialized:  true
  Control Plane Ready:        true
  Infrastructure Ready:       true
  Observed Generation:        3
  Phase:                      Deleting
Events:                       <none>

```

In the underlying infra object, the readiness is also true
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: VSphereCluster
...
status:
  conditions:
  - lastTransitionTime: "2021-03-18T11:32:49Z"
    reason: Deleting
    severity: Info
    status: "False"
    type: Ready
  - lastTransitionTime: "2021-03-18T11:32:49Z"
    reason: Deleting
    severity: Info
    status: "False"
    type: CCMAvailable
  - lastTransitionTime: "2021-03-18T11:32:49Z"
    reason: Deleting
    severity: Info
    status: "False"
    type: CSIAvailable
  - lastTransitionTime: "2021-03-17T08:01:25Z"
    status: "True"
    type: LoadBalancerAvailable
  ready: true
```

**What did you expect to happen:**
The `condition.InfrastructureReady` match `status.infrastructureReady`

**Anything else you would like to add:**

The CAPI log was rotated so not sure how it got to this stage at the first place. But I checked the recent log it's stuck at descendant checking [here](https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/cluster_controller.go#L245-L250), that's why it can't [update](https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/cluster_controller.go#L293-L310) `condition.infrastructure` even now `status.infra` is ready

**Environment:**

- K8S version: `v1.20.4`
- IAAS: `vSphere`
- CAPI version: `0.3.14`
- OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=foca
```

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
