### ISSUE TITLE
Docs should warn about KubeadmControlPlane secrets when switching to a new machine template

### ISSUE THREAD

**Issue by fiunchinho** [kubernetes-sigs/cluster-api#4377]
**What steps did you take and what happened:**

I was trying to upgrade a workload cluster control plane to a new k8s version (from `v1.18.2` to `v1.18.14`), using a new machine image, so I followed [the steps described in the docs](https://cluster-api.sigs.k8s.io/tasks/upgrading-clusters.html).

I used these manifests that are really similar to those that one would get using

```
$ clusterctl config cluster capi-quickstart \                                                                                                                                           
  --kubernetes-version v1.18.2 \
  --control-plane-machine-count=1 \
  --worker-machine-count=3
```

Notice how the `KubeadmControlPlane.spec.kubeadmConfigSpec.files` contains a reference to a `Secret` named `capi-quickstart-control-plane-1-18-2-azure-json`.

<details>
  <summary>Cluster and Control Plane manifests</summary>

```
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  labels:
    cni: calico
    cluster.x-k8s.io/cluster-name: capi-quickstart
  name: capi-quickstart
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: capi-quickstart-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureCluster
    name: capi-quickstart
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureCluster
metadata:
  name: capi-quickstart
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: capi-quickstart
spec:
  location: westeurope
  networkSpec:
    vnet:
      name: capi-quickstart-vnet
  resourceGroup: capi-quickstart
  subscriptionID: 1be3b2e6-497b-45b9-915f-eb35cae23c6a
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: capi-quickstart-control-plane
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: capi-quickstart
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureMachineTemplate
    name: capi-quickstart-control-plane-1-18-2
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: azure
        extraVolumes:
        - hostPath: /etc/kubernetes/azure.json
          mountPath: /etc/kubernetes/azure.json
          name: cloud-config
          readOnly: true
        timeoutForControlPlane: 20m
      controllerManager:
        extraArgs:
          allocate-node-cidrs: "false"
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: azure
          cluster-name: capi-quickstart
        extraVolumes:
        - hostPath: /etc/kubernetes/azure.json
          mountPath: /etc/kubernetes/azure.json
          name: cloud-config
          readOnly: true
      etcd:
        local:
          dataDir: /var/lib/etcddisk/etcd
    diskSetup:
      filesystems:
      - device: /dev/disk/azure/scsi1/lun0
        extraOpts:
        - -E
        - lazy_itable_init=1,lazy_journal_init=1
        filesystem: ext4
        label: etcd_disk
      - device: ephemeral0.1
        filesystem: ext4
        label: ephemeral0
        replaceFS: ntfs
      partitions:
      - device: /dev/disk/azure/scsi1/lun0
        layout: true
        overwrite: false
        tableType: gpt
    files:
    - contentFrom:
        secret:
          key: control-plane-azure.json
          name: capi-quickstart-control-plane-1-18-2-azure-json
      owner: root:root
      path: /etc/kubernetes/azure.json
      permissions: "0644"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: azure
        name: '{{ ds.meta_data["local_hostname"] }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: azure
        name: '{{ ds.meta_data["local_hostname"] }}'
    mounts:
    - - LABEL=etcd_disk
      - /var/lib/etcddisk
    useExperimentalRetryJoin: true
  replicas: 1
  version: v1.18.2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureMachineTemplate
metadata:
  name: capi-quickstart-control-plane-1-18-2
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: capi-quickstart
spec:
  template:
    spec:
      dataDisks:
      - diskSizeGB: 256
        lun: 0
        nameSuffix: etcddisk
      location: westeurope
      image:
        marketplace:
          publisher: cncf-upstream
          offer: capi
          sku: k8s-1dot18dot2-ubuntu-1804
          version: latest
      osDisk:
        diskSizeGB: 128
        managedDisk:
          storageAccountType: Premium_LRS
        osType: Linux
      sshPublicKey: ""
      vmSize: Standard_D4s_v3
```
</details>

Following the steps in the docs, I cloned the existing `AzureMachineTemplate` called `capi-quickstart-control-plane-1-18-2` to a new `AzureMachineTemplate` changing the machine image called `capi-quickstart-control-plane-1-18-14`. Then I modified the `KubeadmControlPlane` to point to the new `AzureMachineTemplate`, and updated the `Version` field to use the right k8s version.

These are the manifests now

<details>
  <summary>Cluster and Control Plane manifests now</summary>

```
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  labels:
    cni: calico
    cluster.x-k8s.io/cluster-name: capi-quickstart
  name: capi-quickstart
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: capi-quickstart-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureCluster
    name: capi-quickstart
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureCluster
metadata:
  name: capi-quickstart
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: capi-quickstart
spec:
  location: westeurope
  networkSpec:
    vnet:
      name: capi-quickstart-vnet
  resourceGroup: capi-quickstart
  subscriptionID: 1be3b2e6-497b-45b9-915f-eb35cae23c6a
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: capi-quickstart-control-plane
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: capi-quickstart
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureMachineTemplate
    name: capi-quickstart-control-plane-1-18-14
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: azure
        extraVolumes:
        - hostPath: /etc/kubernetes/azure.json
          mountPath: /etc/kubernetes/azure.json
          name: cloud-config
          readOnly: true
        timeoutForControlPlane: 20m
      controllerManager:
        extraArgs:
          allocate-node-cidrs: "false"
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: azure
          cluster-name: capi-quickstart
        extraVolumes:
        - hostPath: /etc/kubernetes/azure.json
          mountPath: /etc/kubernetes/azure.json
          name: cloud-config
          readOnly: true
      etcd:
        local:
          dataDir: /var/lib/etcddisk/etcd
    diskSetup:
      filesystems:
      - device: /dev/disk/azure/scsi1/lun0
        extraOpts:
        - -E
        - lazy_itable_init=1,lazy_journal_init=1
        filesystem: ext4
        label: etcd_disk
      - device: ephemeral0.1
        filesystem: ext4
        label: ephemeral0
        replaceFS: ntfs
      partitions:
      - device: /dev/disk/azure/scsi1/lun0
        layout: true
        overwrite: false
        tableType: gpt
    files:
    - contentFrom:
        secret:
          key: control-plane-azure.json
          name: capi-quickstart-control-plane-1-18-2-azure-json
      owner: root:root
      path: /etc/kubernetes/azure.json
      permissions: "0644"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: azure
        name: '{{ ds.meta_data["local_hostname"] }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: azure
        name: '{{ ds.meta_data["local_hostname"] }}'
    mounts:
    - - LABEL=etcd_disk
      - /var/lib/etcddisk
    useExperimentalRetryJoin: true
  replicas: 1
  version: v1.18.14
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureMachineTemplate
metadata:
  name: capi-quickstart-control-plane-1-18-14
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: capi-quickstart
spec:
  template:
    spec:
      dataDisks:
      - diskSizeGB: 256
        lun: 0
        nameSuffix: etcddisk
      location: westeurope
      image:
        marketplace:
          publisher: cncf-upstream
          offer: capi
          sku: k8s-1dot18dot14-ubuntu-1804
          version: latest
      osDisk:
        diskSizeGB: 128
        managedDisk:
          storageAccountType: Premium_LRS
        osType: Linux
      sshPublicKey: ""
      vmSize: Standard_D4s_v3
```
</details>

Everything works just fine. 

The problem here is that the `Secret` referenced from the `KubeadmControlPlane` object is still pointing to a secret called `capi-quickstart-control-plane-1-18-2-azure-json`, which was created for the previous `AzureMachineTemplate`. If I list the secrets, I can see that a new secret is there, it's just not referenced from the `KubeadmControlPlane` object.

```
$ k get secrets | grep capi-quickstart-control-plane-1                                                                                                                                  
capi-quickstart-control-plane-1-18-14-azure-json   Opaque                                2      2m35s
capi-quickstart-control-plane-1-18-2-azure-json    Opaque                                2      18m
```

It doesn't seem right to use the `Secret` generated from an object (`AzureMachineTemplate` called `capi-quickstart-control-plane-1-18-2`) that I might as well delete at this point. Actually, when I delete the `AzureMachineTemplate` that is no longer referenced by the `KubeadmControlPlane` object, the `Secret` gets deleted as well. Not sure what the behavior would be from now on.

**What did you expect to happen:**

Documentation should clarify that when changing the referenced machine template, the secret used should be changed as well.

**Environment:**

- Cluster-api version: `v0.3.14`
- Minikube/KIND version: v0.8.1
- Kubernetes version: (use `kubectl version`): v1.18.2
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
