### ISSUE TITLE
ClusterClass and managed topologies

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api#4430]
In the past few months we've been talking at community meetings about the possibility of adding two new concepts to our APIs: ClusterClass and a more useful Cluster object that lets folks describe a fully functional cluster.

## ClusterClass

A ClusterClass CRD would be introduced to provide easy stamping of clusters of similar shapes. The early version of this Class would be containing an immutable set of references to templating objects, for example:

```yaml
apiVersion: cluster.x-k8s.io/v1alpha4
kind: ClusterClass
metadata:
  name: example-1
spec:
  infrastructure:
    clusterRef:
  controlPlaneRef:
  machines:
    <name of the role>: reference ## This might be un-necessary, we'd have to see if we want to include it or not.
```

The above is mostly an example, details of how the reference system should work are left to the proposal. 

## Cluster

The Cluster object has been used to this day mostly to tie things up together in a logical composition of resources. In this proposal we want to improve the day zero user experience by providing new capabilities as part of the Cluster object. More details are left to the proposal itself, although we'd like to allow a Cluster to be created with a resource that looks as simple as the example below:

```yaml
  kind: Cluster
  metadata:
    name: azure-1
    namespace: eng
  spec:
    class: "dev-azure-simple-small"
    version: v1.19.1
    managed:
      controlPlane:
        replicas: 3
      workers:
        - role: Worker1
           replicas: 10
```

In the example above, the Cluster controller is expected to take all the information present in the ClusterClass associated (in `spec.class`) and create managed resources: a control plane with 3 replicas and one pool of worker nodes with 10 replicas.

The other bit important in here is the `spec.version` field. This new field, for the first iteration, is managing the Kubernetes version for a managed cluster topology. When the version changes, for example in the event of an upgrade, the controller is in charge of declaring the new versions for both control planes and worker pools.

/kind proposal
/area api
/milestone v0.4

**Comment by timothysc** [comment]
I'm not hip with the latest on cluster auto-scalar, but it would seem natural for me to declare intent and limits at this level.  Feel free to argue with me, I'm just spitballing.

**Comment by vivgoyal** [comment]
Couple of questions here:
1. What is meant by `clusters of similar shapes`? If it is what I think of, wouldn't it be provider specific?
2. What value does adding the extra fields to Cluster CRD add here? Pretty much seems like we are moving few fields from machine CRD to cluster CRD or may be even just copying them.

**Comment by srm09** [comment]
The primary idea behind this proposal is to improve the UX and reusability aspect around cluster creation. Currently the Cluster CRD has too much detail around the ControlPlane and Infra definition for the cluster. Thus the cluster CRD cannot be reused to create multiple clusters of the same type (which is basically what it means by creating clusters of similar shapes)
To enable this use case, ClusterClass would be a construct which can be defined once, and used multiple times to create similar clusters with different k8s versions and/or different CP/worker node setup. 

Around enhancing the UX out, the `Cluster` object can be used to answer simpler/frequent questions around size of the cluster, k8s version and so on which currently are harder to answer at this point in time.

**Comment by nickperry** [comment]
As an end-user, I think this looks like it could be helpful for us. We would need each role to be able to have its own infrastructure machine template and KubeadmConfigTemplate.

**Comment by frapposelli** [comment]
I like the idea proposed, looking forward to seeing the proposal 👍🏻

One thing that comes to mind is whether the `version:` and `class:` properties in the revised `Cluster` object should be scoped under `controlplane` and each `workers` section.

**Comment by timothysc** [comment]
> One thing that comes to mind is whether the version: and class: properties in the revised Cluster object should be scoped under controlplane and each workers section. 

I'd expect at this level of consumption the user should not care.  They simply want to change the version and the cluster just upgrades.

**Comment by vincepri** [comment]
> I'd expect at this level of consumption the user should not care. They simply want to change the version and the cluster just upgrades.

+1 — The expectation is that MachineDeployment classes are already there in the form of infra and bootstrap templates. The `version` field instead is a way to declare the Kubernetes version for the whole cluster managed topology.

**Comment by shysank** [comment]
Is ClusterClass itself immutable? As in, if I want to change a parameter in cc, should I just clone a new one and update that parameter?

**Comment by vincepri** [comment]
That was my initial thinking, at least to start with. As soon as we get into mutable territory, things are much get much complicated. Each template reference would have to stay the same, although folks might want to mutate the templates themselves (which could be the next logical step right after the initial version)

**Comment by yastij** [comment]
I think that from a UX perspective there two things we might want to figure out:

- corner case behaviours, e.g. if someone upgrades KCP instead of using the cluster object
- status reporting: we need to select which conditions we need to report, otherwise we'll overload users with info

**Comment by CecileRobertMichon** [comment]
Does this proposal also aim to solve https://github.com/kubernetes-sigs/cluster-api/issues/3203? If so, how would we handle updates to the OS image in the InfraMachine template required for k8s version upgrades in a lot of scenarios?

cc @fiunchinho

**Comment by elmiko** [comment]
> I'm not hip with the latest on cluster auto-scalar, but it would seem natural for me to declare intent and limits at this level. Feel free to argue with me, I'm just spitballing.

assuming you are talking about the total cluster limits (eg mem, cpu, nodes, etc), i agree and i think it pushes us towards the notion of having some sort of controller (or similar) that could automate deployment of the cluster autoscaler.

**Comment by srm09** [comment]
Following the discussion we had during the office hours today, handling the version directly in the `Cluster` object would greatly improve the UX around handling cluster k8s version upgrades.
To enable that we would need to pass a template to be used by the KCP (for the Control Plane nodes) and the MachineDeployments(for the various worker nodes)

**Comment by frapposelli** [comment]
> > I'd expect at this level of consumption the user should not care. They simply want to change the version and the cluster just upgrades.
> 
> +1 — The expectation is that MachineDeployment classes are already there in the form of infra and bootstrap templates. The `version` field instead is a way to declare the Kubernetes version for the whole cluster managed topology.

Makes sense for `version`, even though you might want to handle patches rollout in a staggered fashion per each set of workers (like in large clusters) I understand that it's not a common use case that should be served by this approach.

With regards to `class`, I'm particularly thinking about situations where you might have a heterogeneous set of workers (like Linux workers + Windows workers), which will probably require a different set of infra and bootstrap templates. But maybe I'm overthinking it.

**Comment by srm09** [comment]
```yaml
apiVersion: cluster.x-k8s.io/v1alpha4
kind: ClusterClass
metadata:
  name: example-1
  namespace: blah
spec:
  infrastructure:
    clusterRef:
    workerNodeTypes:
      - type: worker-linux
        # optional
        infrasturctureRef: linux-template-1
      - type: worker-windows
         # optional
         infrasturctureRef: windows-template-1
  controlPlaneRef:
    # optional
    infrastructureRef: linux-template-cp
```

`Cluster` would look like:
```yaml
 kind: Cluster
  metadata:
    name: azure-1
    namespace: eng
  spec:
    class: 
      name: "example-1"
      namespace: "blah"
      version: v1.19.1
      template: linux-template-1
    managed:
      controlPlane:
        replicas: 3
      workers:
        - role: worker-linux
           replicas: 10
        - role: worker-windows
           replicas: 10
           template: windows-template-1
```

The idea here is that the `spec.class.template` will be used as the infra-template when nothin is specified.

**Comment by frapposelli** [comment]
Thanks @srm09 that makes a lot of sense

**Comment by sbueringer** [comment]
@srm09 When are the `spec.infrastructure.workerNodeTypes[].infrastructureRef` used in your example? Sounded like they are either explicitly specified in the workers array in the CLuster resource or `spec.class.template` is used?

But I think it's okay for now. The idea overall is clear and we can specify the details in a proposal.

**Comment by enxebre** [comment]
This is interesting. Some questions to better understand goals and benefits:
What's the additional value of a clusterClass over what we have abstracted already with the `infraTemplate`? 
What's the additional value of having a new abstraction over having new fields/controllers e.g in the existing cluster resource?
How is having the proposed semantics for the cluster topology e.g
```
    managed:
      controlPlane:
        replicas: 3
      workers:
        - role: Worker1
           replicas: 10
```
related to extracting the infra and controlPlane ref into a different CRD?
