### ISSUE TITLE
KCP webhooks for rolloutStrategy block Kubernetes version upgrade when upgrading from v0.3.x to v0.3.15

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api#4437]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**
Given a KubeadmControlPlane with spec applied on a cluster running CAPI v0.3.14:

```
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSMachineTemplate
    name: k8s-cluster-control-plane
    namespace: k8s-cluster
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: aws
      controllerManager:
        extraArgs:
          cloud-provider: aws
      dns: {}
      etcd: {}
      networking: {}
      scheduler: {}
    initConfiguration:
      localAPIEndpoint:
        advertiseAddress: ""
        bindPort: 0
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
    joinConfiguration:
      discovery: {}
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
  replicas: 1
  version: v1.19.7
```

Should be able to apply a revision with the version set to v1.20.4 after upgrading to CAPI v0.3.15, however, kubectl errors with:

```
[spec.rolloutStrategy.rollingUpdate.maxSurge: Forbidden: cannot be modified, spec.rolloutStrategy.type: Forbidden: cannot be modified]
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Chatting with @CecileRobertMichon and @vincepri , this appears to be caused by the webhook defaulting the pre v0.3.15 `rolloutStrategy` and then failing to update as the field isn't mutable.

**Environment:**

- Cluster-api version: v0.3.15, when upgraded from v0.3.14
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
