### ISSUE TITLE
Need proxy support in air-gapped environment

### ISSUE THREAD

**Issue by hanlins** [kubernetes-sigs/cluster-api#4585]
**User Story**

As an operator, I would like to add proxy setting configurations to capi providers for the air-gapped environments.

**Detailed Description**

In air-gapped environment, cluster API provider pods might be deployed in air-gapped environment, and thus cannot talk to the infrastructure provider directly. In this scenario, a proxy server is typically deployed to enable the connectivity and audit the traffic that bypasses the firewall. It would be ideal if we can have a mechanism to plumb the proxy server configurations to the cluster API provider pods, so that they can be able to communicate with the infrastructure.

**Anything else you would like to add:**
One approach I think think of is to have something like this:
```
HTTP_PROXY=xxx clusterctl init
```
The implementation should be similar to https://github.com/kubernetes/kubernetes/pull/84559.

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by enxebre** [comment]
For such scenario we would also want the ability to configure https_proxy and no_proxy.

We'd need to flesh out details here, define and agree on what an air gapped env is and what scenarios and behaviour exactly we want to support end to end, e.g would this be a one shot thing? or would we want capi components to watch a "proxy config" and react to changes there?
I think this will probably deserve a proposal having all the details.

**Comment by fabriziopandini** [comment]
@hanlins I'm starting to think about this use case, and my main concern is that adding proxy settings can't be achieved by simple variable substitution, which is the only for of templating supported in clusterctl as of today.
So the only two options I can see here are:
- to rely on different templating solutions injected in the clusterctl library
- use mutating web hooks

Also, the ongoing work on ManagedCluster might provide some help here, but this is still TBD

**Comment by joejulian** [comment]
/reopen

We just encountered a customer that needs this, too.

It could be done through templating in [cmd/clusterctl/client/repository.NewComponents](https://github.com/kubernetes-sigs/cluster-api/blob/5756be13affef606b6683c2c413f0987c1f0e451/cmd/clusterctl/client/repository/components.go#L195) with an option that contains the values for https_proxy, http_proxy, and no_proxy.

**Comment by sbueringer** [comment]
/assign @ykakarap 
Can you please assess if it would be possible to extend clusterctl to inject http proxy env vars in the provider manifests.

**Comment by ykakarap** [comment]
Catching up on the issue. Will get back soon. :) 

@faiq I will take a look at this and post my findings here.

**Comment by fabriziopandini** [comment]
/triage accepted
/unassign @ykakarap 

@joejulian could you share how you fixed this problem as per https://github.com/kubernetes-sigs/cluster-api/issues/4585#issuecomment-1027310851 so someone can pick up the work in CAPI
/help

**Comment by faiq** [comment]
@fabriziopandini we modify the core-components.yaml file with this `kustomization` overlay

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: NA
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: HTTP_PROXY
              value: ${HTTP_PROXY:=""}
            - name: HTTPS_PROXY
              value: ${HTTPS_PROXY:=""}
            - name: NO_PROXY
              value: ${NO_PROXY:=""}
```
