### ISSUE TITLE
Rename failure domains to Topology.zone 

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api#4618]
**Detailed Description**

After the zone and region node labels were graduated to GA in k/k, the key was renamed:

```
failure-domain.beta.kubernetes.io/zone -> topology.kubernetes.io/zone
failure-domain.beta.kubernetes.io/region -> topology.kubernetes.io/region
```

This issue is to kick-off discussion around renaming failure domain to something like:
```
status:
  ....
  topology:
     zones: 
```

This should help us align terminologies and avoid confusion for folks

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by yastij** [comment]
cc @vincepri @CecileRobertMichon @randomvariable @fabriziopandini

**Comment by vincepri** [comment]
It might be a little late right now to rename and change the contract for providers for v0.4

**Comment by vincepri** [comment]
Is it ok to tackle this in the next iteration?

**Comment by akutz** [comment]
Given Kubernetes primitives use labels to express topology information such as zones and regions, does it make sense to continue to use first-class fields as the transport mechanism for assignment to machines? Please note this is not suggesting to alter the way the infrastructure provider currently advertises the topology. Rather, instead of KCP assigning the FD to `spec.failureDomain` (https://github.com/kubernetes-sigs/cluster-api/blob/686aef6a95613cfe87631e92a11cb55349da4725/controlplane/kubeadm/controllers/helpers.go#L281), why set a label on the machine resource? For example:

```yaml
apiVersion: clusterapi
kind: Machine
metadata:
  name: hello
  namespace: world
  labels:
    topology.kubernetes.io/zone: milky-way
```
