### ISSUE TITLE
confusion about Quick Start

### ISSUE THREAD

**Issue by huchen2021** [kubernetes-sigs/cluster-api#4817]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
```
I am the new guy of cluster api, and tried to use kind+clusterctl to create my first workload cluster with 
docker provider.

When I use kubectl apply -f capi-quickstart.yaml, it seems fine.

# kubectl apply -f capi-quickstart.yaml
cluster.cluster.x-k8s.io/capi-quickstart created
dockercluster.infrastructure.cluster.x-k8s.io/capi-quickstart unchanged
dockermachinetemplate.infrastructure.cluster.x-k8s.io/capi-quickstart-control-plane created
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/capi-quickstart-control-plane created
dockermachinetemplate.infrastructure.cluster.x-k8s.io/capi-quickstart-md-0 created
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/capi-quickstart-md-0 unchanged

The status of capi-quickstart  is always provisioning.
# kubectl get cluster --all-namespaces
NAMESPACE   NAME              PHASE
default     capi-quickstart   Provisioning

From the following output, it seems that cluster capi-quickstart is waiting for control plane to ready.
# clusterctl describe cluster capi-quickstart
NAME                                                                READY  SEVERITY  REASON                           SINCE  MESSAGE
/capi-quickstart                                                    False  Warning   ScalingUp                        23s    Scaling up control plane to 3 replicas (actual 0)
├─ClusterInfrastructure - DockerCluster/capi-quickstart             True                                              24s
├─ControlPlane - KubeadmControlPlane/capi-quickstart-control-plane  False  Warning   ScalingUp                        23s    Scaling up control plane to 3 replicas (actual 0)
└─Workers
  └─MachineDeployment/capi-quickstart-md-0
    └─3 Machines...                                                 False  Info      WaitingForControlPlaneAvailable  24s    See capi-quickstart-md-0-7cc765486-d9bnh, capi-quickstart-md-0-7cc765486-xz4fc, ...

New clusterctl version available: v0.3.17 -> v0.3.19
https://github.com/kubernetes-sigs/cluster-api/releases/tag/v0.3.19

Is this control plane? It seems not ready.
# kubectl get kubeadmcontrolplane --all-namespaces
NAMESPACE   NAME                            INITIALIZED   API SERVER AVAILABLE   VERSION    REPLICAS   READY   UPDATED   UNAVAILABLE
default     capi-quickstart-control-plane                                        v1.18.16

From https://cluster-api.sigs.k8s.io/user/quick-start.html, The control planes won’t be Ready until 
we install a CNI in the next step. But when I tried to install CNI first, 
it needs to run "kubectl --kubeconfig=./capi-quickstart.kubeconfig apply -f https://docs.projectcalico.org/v3.15/manifests/calico.yaml",
  that means it need to generate capi-quickstart.kubeconfig first. But when I tried to generate it, 
it reporting the following error:
# clusterctl get kubeconfig capi-quickstart > capi-quickstart.kubeconfig
Error: "capi-quickstart-kubeconfig" not found in namespace "default": secrets "capi-quickstart-kubeconfig" not found

```

**Comment by fabriziopandini** [comment]
It seems the machine are not starting and this can happen due to several reasons
- Lack of docker socket mount in kind (see https://cluster-api.sigs.k8s.io/user/quick-start.html#install-andor-configure-a-kubernetes-cluster)
- Kind version older than 0.8 
- Low resources for docker daemon (I suggest 6GB)
- A couple of docker related issues https://master.cluster-api.sigs.k8s.io/user/troubleshooting.html#cluster-api-with-docker

If none of the above helps, please attach the CAPD logs

**Comment by huchen2021** [comment]
> It seems the machine are not starting and this can happen due to several reasons
> 
>     * Lack of docker socket mount in kind (see https://cluster-api.sigs.k8s.io/user/quick-start.html#install-andor-configure-a-kubernetes-cluster)
```
I pretty sure I was create the manager cluster by the following command:
$ cat > kind-cluster-with-extramounts.yaml <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
EOF

$ export KIND_EXPERIMENTAL_DOCKER_NETWORK=bridge
$ kind create cluster --config kind-cluster-with-extramounts.yaml

But this issues is for workload cluster, I create it follow the quick start.

$ clusterctl config cluster capi-quickstart --flavor development \
  --kubernetes-version v1.18.16 \
  --control-plane-machine-count=3 \
  --worker-machine-count=3 \
  > capi-quickstart.yaml

$ kubectl apply -f capi-quickstart.yaml

I checked capi-quickstart.yaml, there is no  extraMounts field, do I need to add it?

```
> 
>     * Kind version older than 0.8

```
# kind --version
kind version 0.11.0
```

> 
>     * Low resources for docker daemon (I suggest 6GB)
> 
```
# docker system df
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              15                  2                   2.131 GB            988.8 MB (46%)
Containers          2                   1                   101.8 MB            0 B (0%)
Local Volumes       2                   2                   4.233 GB            0 B (0%)

# docker stats
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
3b5915590595        20.29%              4.203 GiB / 7.545 GiB   55.71%              244 MB / 26.5 MB    32.8 kB / 30.1 MB   577
```
>     * A couple of docker related issues https://master.cluster-api.sigs.k8s.io/user/troubleshooting.html#cluster-api-with-docker

```
I checked it, mine is fine.
```
> 
> 
> If none of the above helps, please attach the CAPD logs

```
[capd-controller-manager-84cb4b79-grkcx.log](https://github.com/kubernetes-sigs/cluster-api/files/6654434/capd-controller-manager-84cb4b79-grkcx.log)
[capi-controller-manager-5678dfd475-n9xqw.log](https://github.com/kubernetes-sigs/cluster-api/files/6654435/capi-controller-manager-5678dfd475-n9xqw.log)
[capi-controller-manager-d6c5f966b-mr8v5.log](https://github.com/kubernetes-sigs/cluster-api/files/6654437/capi-controller-manager-d6c5f966b-mr8v5.log)
[capi-kubeadm-bootstrap-controller-manager-6cdb7bfd75-xcdzb.log](https://github.com/kubernetes-sigs/cluster-api/files/6654438/capi-kubeadm-bootstrap-controller-manager-6cdb7bfd75-xcdzb.log)
[capi-kubeadm-bootstrap-controller-manager-5487bc848-w4k29.log](https://github.com/kubernetes-sigs/cluster-api/files/6654439/capi-kubeadm-bootstrap-controller-manager-5487bc848-w4k29.log)
[capi-kubeadm-control-plane-controller-manager-64b4687986-kjgd5.log](https://github.com/kubernetes-sigs/cluster-api/files/6654440/capi-kubeadm-control-plane-controller-manager-64b4687986-kjgd5.log)
[capi-kubeadm-control-plane-controller-manager-67f99b459-c5m7v.log](https://github.com/kubernetes-sigs/cluster-api/files/6654441/capi-kubeadm-control-plane-controller-manager-67f99b459-c5m7v.log)

```

**Comment by huchen2021** [comment]
```
Here are my capi-quickstart.yaml:
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: capi-quickstart
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: k8s.test
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: capi-quickstart-control-plane
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: DockerCluster
    name: capi-quickstart
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: DockerCluster
metadata:
  name: capi-quickstart
  namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: DockerMachineTemplate
metadata:
  name: capi-quickstart-control-plane
  namespace: default
spec:
  template:
    spec:
      extraMounts:
      - containerPath: /var/run/docker.sock
        hostPath: /var/run/docker.sock
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: capi-quickstart-control-plane
  namespace: default
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: DockerMachineTemplate
    name: capi-quickstart-control-plane
    namespace: default
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
  replicas: 3
  version: v1.18.16
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: DockerMachineTemplate
metadata:
  name: capi-quickstart-md-0
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: capi-quickstart-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: capi-quickstart-md-0
  namespace: default
spec:
  clusterName: capi-quickstart
  replicas: 3
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: capi-quickstart-md-0
          namespace: default
      clusterName: capi-quickstart
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: DockerMachineTemplate
        name: capi-quickstart-md-0
        namespace: default
      version: v1.18.16

```
