### ISSUE TITLE
KCP expansion failed from 1 to 3

### ISSUE THREAD

**Issue by chymy** [kubernetes-sigs/cluster-api#4886]
**What steps did you take and what happened:**
1. Deploy openstack workload cluster(one controlplane + one node).
2. Modify the controlplane replica from 1 to 3

KCP logs show:
```
I0707 00:32:51.445862       1 controller.go:350] controller-runtime/manager/controller/kubeadmcontrolplane "msg"="Scaling up control plane" "cluster"="innercluster" "name"="innercluster-control-plane" "namespace"="default" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="KubeadmControlPlane" "Desired"=3 "Existing"=1
I0707 00:32:51.445992       1 scale.go:205]  "msg"="Waiting for control plane to pass preflight checks" "cluster-name"="innercluster" "name"="innercluster-control-plane" "namespace"="default" "failures"="machine innercluster-control-plane-jmtjk reports EtcdMemberHealthy condition is unknown (Failed to connect to the etcd pod on the innercluster-control-plane-twpm8 node)"
```

kcp status:
```yaml
...
status:
    conditions:
    - lastTransitionTime: "2021-07-06T12:07:15Z"
      message: Scaling up control plane to 3 replicas (actual 1)
      reason: ScalingUp
      severity: Warning
      status: "False"
      type: Ready
    - lastTransitionTime: "2021-07-06T08:14:11Z"
      status: "True"
      type: Available
    - lastTransitionTime: "2021-07-06T08:08:21Z"
      status: "True"
      type: CertificatesAvailable
    - lastTransitionTime: "2021-07-06T08:14:12Z"
      status: "True"
      type: ControlPlaneComponentsHealthy
    - lastTransitionTime: "2021-07-06T08:14:14Z"
      message: 'Following machines are reporting unknown etcd member status: innercluster-control-plane-jmtjk'
      reason: EtcdClusterUnknown
      status: Unknown
      type: EtcdClusterHealthyCondition
    - lastTransitionTime: "2021-07-06T08:08:23Z"
      status: "True"
      type: MachinesCreated
    - lastTransitionTime: "2021-07-06T08:09:28Z"
      status: "True"
      type: MachinesReady
    - lastTransitionTime: "2021-07-06T12:07:15Z"
      message: Scaling up control plane to 3 replicas (actual 1)
      reason: ScalingUp
      severity: Warning
      status: "False"
      type: Resized
    initialized: true
    observedGeneration: 2
    ready: true
    readyReplicas: 1
    replicas: 1
    selector: cluster.x-k8s.io/cluster-name=innercluster,cluster.x-k8s.io/control-plane
    updatedReplicas: 1
...
```

controllpalne status conditions:
```yaml
...
conditions:
  - lastTransitionTime: "2021-07-06T08:08:48Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-07-06T08:14:12Z"
    status: "True"
    type: APIServerPodHealthy
  - lastTransitionTime: "2021-07-06T08:08:23Z"
    status: "True"
    type: BootstrapReady
  - lastTransitionTime: "2021-07-06T08:14:12Z"
    status: "True"
    type: ControllerManagerPodHealthy
  - lastTransitionTime: "2021-07-06T08:14:14Z"
    message: Failed to connect to the etcd pod on the innercluster-control-plane-twpm8
      node
    reason: MemberInspectionFailed
    status: Unknown
    type: EtcdMemberHealthy
  - lastTransitionTime: "2021-07-06T08:15:26Z"
    status: "True"
    type: EtcdPodHealthy
  - lastTransitionTime: "2021-07-06T08:08:48Z"
    status: "True"
    type: InfrastructureReady
  - lastTransitionTime: "2021-07-06T12:03:48Z"
    status: "True"
    type: NodeHealthy
  - lastTransitionTime: "2021-07-06T08:15:26Z"
    status: "True"
    type: SchedulerPodHealthy
...
```

wokercluster:
```sh
# kubectl get no
NAME                               STATUS   ROLES    AGE   VERSION
innercluster-control-plane-twpm8   Ready    master   17h   v1.19.4
innercluster-md-0-mxmtv            Ready    <none>   17h   v1.19.4

# kubectl get po -A
NAMESPACE     NAME                                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-7bb7bf448-g88m4                    1/1     Running   0          13h
kube-system   calico-node-6ljmz                                          1/1     Running   0          13h
kube-system   calico-node-f4dcw                                          1/1     Running   0          13h
kube-system   coredns-6cc9d46457-8qg88                                   1/1     Running   0          17h
kube-system   coredns-6cc9d46457-jsrfr                                   1/1     Running   0          17h
kube-system   etcd-innercluster-control-plane-twpm8                      1/1     Running   0          17h
kube-system   kube-apiserver-innercluster-control-plane-twpm8            1/1     Running   0          17h
kube-system   kube-controller-manager-innercluster-control-plane-twpm8   1/1     Running   0          17h
kube-system   kube-proxy-cggmv                                           1/1     Running   0          17h
kube-system   kube-proxy-pn947                                           1/1     Running   0          17h
kube-system   kube-scheduler-innercluster-control-plane-twpm8            1/1     Running   0          17h
```

In the controlpalne etcd logs:
```
2021-07-07 00:18:22.919594 I | embed: rejected connection from "127.0.0.1:48141" (error "remote error: tls: bad certificate", ServerName "etcd-innercluster-control-plane-twpm8")
2021-07-07 00:18:23.969817 I | embed: rejected connection from "127.0.0.1:48155" (error "remote error: tls: bad certificate", ServerName "etcd-innercluster-control-plane-twpm8")
2021-07-07 00:18:26.301411 I | etcdserver/api/etcdhttp: /health OK (status code 200)
2021-07-07 00:18:36.301451 I | etcdserver/api/etcdhttp: /health OK (status code 200)
2021-07-07 00:18:41.867121 I | embed: rejected connection from "127.0.0.1:48275" (error "remote error: tls: bad certificate", ServerName "etcd-innercluster-control-plane-twpm8")
2021-07-07 00:18:43.017143 I | embed: rejected connection from "127.0.0.1:48287" (error "remote error: tls: bad certificate", ServerName "etcd-innercluster-control-plane-twpm8")
2021-07-07 00:18:44.369349 I | mvcc: store.index: compact 132110
2021-07-07 00:18:44.371512 I | mvcc: finished scheduled compaction at 132110 (took 1.901392ms)
2021-07-07 00:18:44.377872 I | embed: rejected connection from "127.0.0.1:48303" (error "remote error: tls: bad certificate", ServerName "etcd-innercluster-control-plane-twpm8")
2021-07-07 00:18:45.426647 I | embed: rejected connection from "127.0.0.1:48313" (error "remote error: tls: bad certificate", ServerName "etcd-innercluster-control-plane-twpm8")
```

**What did you expect to happen:**
KCP successfully expanded to 3 replica.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.16
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): v1.19.4
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
