### ISSUE TITLE
capi-kubeadm-control-plane-manager-rolebinding no longer uses aggregated-manager-role 

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/cluster-api#4935]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
In [v0.3.20](https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.3.20/control-plane-components.yaml)
The `capi-kubeadm-control-plane-manager-rolebinding` used the `capi-kubeadm-control-plane-aggregated-manager-role` ClusterRole which allows the use of `kubeadm.controlplane.cluster.x-k8s.io/aggregate-to-manager: "true"` for the ` capi-kubeadm-control-plane-manager` deployment to have additional RBAC permissions.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
  name: capi-kubeadm-control-plane-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capi-kubeadm-control-plane-aggregated-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: capi-kubeadm-control-plane-system
```

In in [v0.4.0](https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.4.0/control-plane-components.yaml) the same `ClusterRoleBinding` is and `kubeadm.controlplane.cluster.x-k8s.io/aggregate-to-manager: "true"` no longer works:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
  name: capi-kubeadm-control-plane-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capi-kubeadm-control-plane-manager-role
subjects:
- kind: ServiceAccount
  name: capi-kubeadm-control-plane-manager
  namespace: capi-kubeadm-control-plane-system
```

**What did you expect to happen:**
The behavior should be the same in the new version [v0.4.0](https://github.com/kubernetes-sigs/cluster-api/releases/download/v0.4.0/control-plane-components.yaml).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Originally reported in https://kubernetes.slack.com/archives/C8TSNPY4T/p1625630307101000

---

Its possible to workaround this by creating an additional `ClusterRoleBinding`:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
  name: capi-kubeadm-control-plane-aggregated-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capi-kubeadm-control-plane-system-capi-kubeadm-control-plane-aggregated-manager-role
subjects:
  - kind: ServiceAccount
    name: capi-kubeadm-control-plane-manager
    namespace: capi-kubeadm-control-plane-system
```

**Environment:**

- Cluster-api version: `v0.4.0`
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
