### ISSUE TITLE
ControlPlaneInitialized condition is set before a control-plane Node is ready

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/cluster-api#4936]
**What steps did you take and what happened:**

1. Follow https://cluster-api.sigs.k8s.io/user/quick-start.html for Docker with:

```
clusterctl generate cluster capi-quickstart --flavor development \
  --kubernetes-version v1.19.11 \
  --control-plane-machine-count=1 \
  --worker-machine-count=1 \
  > capi-quickstart.yaml
```

2. Modify the `KubeadmControlPlane` to force a failure, something like:

```
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: KubeadmControlPlane
metadata:
  name: capi-quickstart-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "{{INVALID_LABELS}}"
``` 

---

The worker machine is in Provisioning, before a control-plane is up:
```
kubectl get machines
NAME                                    PROVIDERID   PHASE          VERSION
capi-quickstart-control-plane-gbcvx                  Provisioning   v1.19.11
capi-quickstart-md-0-644755b685-spjwc                Provisioning   v1.19.11
```

Its because the `cluster` has `ControlPlaneInitialized` status.
```
  status:
    conditions:
    - lastTransitionTime: "2021-07-13T17:59:21Z"
      message: Scaling up control plane to 1 replicas (actual 0)
      reason: ScalingUp
      severity: Warning
      status: "False"
      type: Ready
    - lastTransitionTime: "2021-07-13T18:00:03Z"
      status: "True"
      type: ControlPlaneInitialized
```

Even though there is no nodeRef
```
kubectl get machines capi-quickstart-control-plane-gbcvx -o yaml | grep nodeRef | wc -l
       0
``` 

**What did you expect to happen:**

According to the [API comment](https://github.com/kubernetes-sigs/cluster-api/blob/7f879be68d15737e335b6cb39d380d1d163e06e6/api/v1alpha4/condition_consts.go#L61-L65) `ControlPlaneInitializedCondition` should be marked True when:
>cluster's apiserver is reachable and at least one control-plane Machine has a node reference 

There is 1 controller that checks for the NodeRef
https://github.com/kubernetes-sigs/cluster-api/blob/7f879be68d15737e335b6cb39d380d1d163e06e6/controllers/cluster_controller.go#L477-L482 

But another one will set to True with only `KubeadmControlPlane.initialized = true`:
https://github.com/kubernetes-sigs/cluster-api/blob/bfc6f80add5c21b8dc2b704951f42bc14708ebc4/controllers/cluster_controller_phases.go#L238-L247

I _think_ both should check for a control-plane Machine to have a NodeRef.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

It most cases it may be undesirable to start bootstrapping worker machines before a control-plane (and API server) is up since it may cause a lot of churn as the workers will fail to start.

**Environment:**

- Cluster-api version: `v0.4.0`
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
