### ISSUE TITLE
"clusterctl upgrade" fails during retry

### ISSUE THREAD

**Issue by saimanoj01** [kubernetes-sigs/cluster-api#5015]
**What steps did you take and what happened:**
1. Created a kind bootstrap cluster.
2. Install clusterctl v0.3.12 and run "clusterctl init" with the below configuration.
```
release:
    version: ""
providers:  
    - name: cluster-api
      type: CoreProvider
      url: https://github.com/kubernetes-sigs/cluster-api/releases/v0.3.12/core-components.yaml
    - name: kubeadm
      type: BootstrapProvider
      url: https://github.com/kubernetes-sigs/cluster-api/releases/v0.3.12/bootstrap-components.yaml
    - name: kubeadm
      type: ControlPlaneProvider
      url: https://github.com/kubernetes-sigs/cluster-api/releases/v0.3.12/control-plane-components.yaml
    - name: azure
      type: InfrastructureProvider
      url: https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases/v0.4.10/infrastructure-components.yaml
```
3. Triggered upgrade and interrupted in-between
```
$clusterctl upgrade apply --management-group capi-system/cluster-api --contract v1alpha3
Checking cert-manager version...
Cert-manager is already up to date
Performing upgrade...
Deleting Provider="cluster-api" Version="v0.3.12" TargetNamespace="capi-system"
Installing Provider="cluster-api" Version="v0.3.22" TargetNamespace="capi-system"
^C
```

4. Retry upgrade is failing 
```
$clusterctl upgrade apply --management-group capi-system/cluster-api --contract v1alpha3  -v 10./clusterctl_0_3_12 upgrade apply --management-group capi-system/cluster-api --contract v1alpha3  -v 10
Using configuration File="/Users/saib/.cluster-api/clusterctl.yaml"
Checking cert-manager version...
Cert-manager is already up to datePerforming upgrade...
Error: Unable to identify management groups: provider capi-kubeadm-control-plane-system/control-plane-kubeadm 
can't be combined with any core provider
sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster.checkOverlappingProviders /workspace/cmd/clusterctl/client/cluster/inventory_managementgroup.go:131
sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster.deriveManagementGroups /workspace/cmd/clusterctl/client/cluster/inventory_managementgroup.go:72
sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster.(*inventoryClient).GetManagementGroups /workspace/cmd/clusterctl/client/cluster/inventory_managementgroup.go:153
sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster.(*providerUpgrader).getManagementGroup /workspace/cmd/clusterctl/client/cluster/upgrader.go:207sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster.(*providerUpgrader).ApplyPlan /workspace/cmd/clusterctl/client/cluster/upgrader.go:147
sigs.k8s.io/cluster-api/cmd/clusterctl/client.(*clusterctlClient).ApplyUpgrade /workspace/cmd/clusterctl/client/upgrade.go:168
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.runUpgradeApply /workspace/cmd/clusterctl/cmd/upgrade_apply.go:96
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.glob..func12 /workspace/cmd/clusterctl/cmd/upgrade_apply.go:57
github.com/spf13/cobra.(*Command).execute /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.Execute /workspace/cmd/clusterctl/cmd/root.go:91main.main /workspace/cmd/clusterctl/main.go:25
runtime.main /usr/local/go/src/runtime/proc.go:203runtime.goexit
```
**What did you expect to happen:**
Upgrade should have gone through

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.12
- Minikube/KIND version: kind v0.9.0 go1.15.2 darwin/amd64
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
