### ISSUE TITLE
MachineSet's Resized condition always report ScalingUp false

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#5433]
**What steps did you take and what happened:**
Create a Cluster with a MachineDeployment with replicas 3, wait for the cluster to provision

```
NAME                                                                READY  SEVERITY  REASON                       SINCE  MESSAGE
Cluster/capi-quickstart                                             True                                          42s
├─ClusterInfrastructure - DockerCluster/capi-quickstart             True                                          85s
├─ControlPlane - KubeadmControlPlane/capi-quickstart-control-plane  True                                          42s
│ └─Machine/capi-quickstart-control-plane-k6fnk                     True                                          44s
└─Workers
  └─MachineDeployment/capi-quickstart-md-0                          False  Warning   WaitingForAvailableMachines  86s    Minimum availability requires 3 replicas, current 0 available
    └─MachineSet/capi-quickstart-md-0-74f99f9d99                    False  Warning   ScalingUp                    86s    Scaling up MachineSet to 3 replicas (actual 0)
      └─3 Machines...                                               True                                          2s     See capi-quickstart-md-0-74f99f9d99-2wh5m, capi-quickstart-md-0-74f99f9d99-k577h, ...
```

However the MachineSet always remain in ScalingUp

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineSet
metadata:
  ...
spec:
  clusterName: capi-quickstart
  deletePolicy: Random
  replicas: 3
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: capi-quickstart
      cluster.x-k8s.io/deployment-name: capi-quickstart-md-0
      machine-template-hash: "3095595855"
  template:
    ...
status:
  conditions:
  - lastTransitionTime: "2021-10-17T08:27:01Z"
    message: Scaling up MachineSet to 3 replicas (actual 0)
    reason: ScalingUp
    severity: Warning
    status: "False"
    type: Ready
  - lastTransitionTime: "2021-10-17T08:27:01Z"
    status: "True"
    type: MachinesCreated
  - lastTransitionTime: "2021-10-17T08:28:26Z"
    status: "True"
    type: MachinesReady
  - lastTransitionTime: "2021-10-17T08:27:01Z"
    message: Scaling up MachineSet to 3 replicas (actual 0)
    reason: ScalingUp
    severity: Warning
    status: "False"
    type: Resized
  fullyLabeledReplicas: 3
  observedGeneration: 1
  replicas: 3
  selector: cluster.x-k8s.io/cluster-name=capi-quickstart,cluster.x-k8s.io/deployment-name=capi-quickstart-md-0,machine-template-hash=309559585
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
