### ISSUE TITLE
Modifying etcd's extraArgs with value prevents static manifest creation

### ISSUE THREAD

**Issue by kbreit** [kubernetes-sigs/cluster-api#5564]
**What steps did you take and what happened:**
I have a Helm chart which templates CAPV clusters. In this case I'm trying to enable etcd Prometheus metrics using the `listen-metrics-urls` value. When I have this enabled it doesn't create the `/etc/kubernetes/manifests/etcd` static pod manifest file on nodes.

```
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: KubeadmControlPlane
metadata:
  name: {{ .Values.cluster.fullName }}-kubeadm-control-plane
spec:
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
      kind: VSphereMachineTemplate
      name: {{ .Values.cluster.fullName }}-control-plane-machine-template-{{ .Values.cluster.version }}
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
          bind-address: 0.0.0.0
      controllerManager:
        extraArgs:
          cloud-provider: external
          bind-address: 0.0.0.0
      etcd:
        local:
          extraArgs:
            listen-metrics-urls: 'http://0.0.0.0:2381'
```

**What did you expect to happen:**
`/etc/kubernetes/manifests/etcd` should have been created with `--listen-metrics-urls=http://0.0.0.0:2381` as an argument.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 0.4.4
- Minikube/KIND version: n/a
- Kubernetes version: (use `kubectl version`): 1.20.2
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
