### ISSUE TITLE
Allow patches to be selectively applied

### ISSUE THREAD

**Issue by vuil** [kubernetes-sigs/cluster-api#5566]
**User Story**

As an operator I would like to create ClusterClass's with a rich set of customizations that can selectively applied by a user who chooses to use them. 

**Detailed Description**

This is a formal request for the feature that has been mentioned in the [ClusterClass and Managed Topologies](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/202105256-cluster-class-and-managed-topologies.md#behavior-with-patches)
```
Note: We are considering to add a field to allow defining optional patches. 
This would allow adding optional patches in the ClusterClass and then activating them on a per-cluster basis via opt-in.
```

Just like a optional fields and default values improves the reusability of a type definition (by giving flexibility to what and how much information need to be supplied to initialize an object of said type), providing control on which of the ClusterClass's patches are applied will allow the consolidation of said patches into a smaller number of reusable ClusterClass's.
Without this functionality, the number of actual ClusterClass's will grow exponentially as the number of patches associated with a ClusterClass's that may or may not be needed under actual usage scenarios increases.

One way to introduce this functionality without complicating the actual patching action would be to introduce an additional field in the ClusterClassPatch or PatchDefinition. At its simplest, the field can be optionally set with the name of a variable, the value of which will determine whether the associated patch will be applied.

Two main use cases I expect to come up quite often:

1. Apply patch only if variable(s) are set. Often patch is only required if certain variables are set ("if proxy setting is set, patch KCP"; "if autoscaler is enabled, patch MachineDeployment with scaling limits", etc) 
2. Using a boolean ClusterClassVariable, semantically opaque to the patch engine, to control if a patch is applied. This is a generalization of 1. and gives the client an additional level of control on whether a patch is relevant. (e.g Perhaps the computation of the value of this variable is not straightforward and the client is now free to introduce whatever logic to arrive at the this boolean value)

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature
/area topology

**Comment by sbueringer** [comment]
@vuil Thx for this feature request. I think it makes a lot of sense.

I think on a high level we have to decide how magical/implicit it should be for the user (e.g. the one who creates the Cluster and not necessarily the ClusterClass).

A few options

### Option 1:  Automatically only apply patches which have all corresponding variables set

The problem with this option is that it is very implicit and it could be error-prone as patches are just not applied if a variable is forgotten.

It also would make it impossible to have optional patches which only use variables with default values (based on the assumption that variables with default values will be automatically added with their default values, but that part is still TBD, and not discussed yet). 

But maybe those limitations are okay.

### Option 2: Declare patch as optional on some level in the ClusterClass, explicitly enable it in the Cluster

To enable it in the Cluster we have (at least) the following option:
* a) define a boolean ClusterClassVariable on the patch in the ClusterClass which can then be used in the Cluster to enable/disable the patch (as you suggested)
    * The nice thing here is that we don't have to add an additional field to the Cluster and that we could have opt-in and opt-out behavior depending on the default value of the ClusterClassVariable
    * In theory we could generalize the field on the patch to take a template which has to evaluate to true/false and we could do all kinds of dirty hacks with go templates (not sure if I really want this variant, just wanted to mention it :))

* b) we could add an additional `.spec.topology.optionalPatches` `[]string` field (or something similar) which can be used to explicitly enable ClusterClassPatches by name (we could come up with another structure if we also want to enable PatchDefinitions individually, but not sure if we need that)

Similarly we could also implement it with an opt-out semantic, but opt-in sounds better.


Another concern is how the concept of optional patches will apply to external patches. Depending on if the concept also exists for external patches we should make sure we add new fields for optional patches on the right level so we end up with a consistent UX.

**Comment by fabriziopandini** [comment]
+1 for a proposal
putting on the table a third option. Adding initGates (name TBD) to our API.

```
spec: 
   patches:
   - name: add proxy support
      initGates:
          variable: my-variable
      definitions:
      - ....
```

This will allow to reuse the same variables used for patching, and eventually in a second phase to add support for using go templates for transforming non boolean values into bool, e.g `{{if .http_proxy != "" }} true {{else}} false {{end}}` (not 100% sure about the syntax, but this should give the idea)

**Comment by sbueringer** [comment]
I would propose adding an `enabledIf` field to the `ClusterClassPatch` struct. It would looks like this

```yaml
  patches:
  - name: clusterName
    enabledIf:
      value: true
      valueFrom:
        variable: "patchHttpProxy"
        template: "{{ if eq .httpProxy "" }}false{{ else }} true {{ end }}"
    definitions:
    - selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: replace
        path: "/spec/template/spec/kubeadmConfigSpec/clusterConfiguration/controllerManager/extraArgs/cluster-name"
        valueFrom:
          variable: builtin.cluster.name
```

It would use ~ the same value/valueFrom structure as we have for JSONPatch values (I think it's nicely consistent that way)

**Comment by sbueringer** [comment]
@vuil @fabriziopandini @vincepri Thoughts?

**Comment by fabriziopandini** [comment]
+1 
I assume value, valueFrom.variable and valueFrom.Template are mutually exclusive

**Comment by sbueringer** [comment]
Hm we could also drastically simplify it if enabledIf is just a template:

hardcoded:
```yaml
  patches:
  - name: clusterName
    enabledIf: "true"
```

variable usage:
```yaml
  patches:
  - name: clusterName
     enabledIf: "{{ .httpProxyEnabled }}"
```

more advanced templating:
```yaml
  patches:
  - name: clusterName
     enabledIf: "{{ if eq "v1.21.2" .builtin.cluster.topology.version }}true{{end}}"
```
