### ISSUE TITLE
CAPI-managed CoreDNS deployment prevents cluster-autoscaler scale-down

### ISSUE THREAD

**Issue by itspngu** [kubernetes-sigs/cluster-api#5606]
**What steps did you take and what happened:**

Set up workload cluster, installed metrics-server, set up cluster-autoscaler with cluster-api provider as per docs.

Ran some tests for scaling up and down by adding a Deployment with an arbitrary number of replicas, everything went fine.
Currently, the `spec.replicas` field of the `coredns` deployment is set to 2 - I have a hunch this might be related to running a cluster version upgrade from 1.20 to 1.21 on friday.

Because CoreDNS is run as a Deployment in the kube-system namespace (rather than a DaemonSet) I now have one pod on the control plane node and one on a worker node, the latter satisfying cluster-autoscalers [conditions preventing node removal¹](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node).

¹: "Kube-system pods that [...] are not run on the node by default, [...] unless the pod has the following annotation [...]: cluster-autoscaler.kubernetes.io/safe-to-evict: true"

**What did you expect to happen:**

When removing the workload which triggered the scale-up, the cluster should be able to scale down again. The way in which KCP deploys CoreDNS and/or handles kubernetes version upgrades in that deployment prevents that.

**Anything else you would like to add:**

CoreDNS deployment info:

```yaml
# $ kubectl -n kube-system get deployments/coredns -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-11-04T13:51:08Z"
  generation: 1
  labels:
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system
# [...]
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-dns
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: kube-dns
    spec:
      containers:
      - args:
        - -conf
        - /etc/coredns/Corefile
        image: k8s.gcr.io/coredns:1.7.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: coredns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/coredns
          name: config-volume
          readOnly: true
      dnsPolicy: Default
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: coredns
      serviceAccountName: coredns
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: Corefile
            path: Corefile
          name: coredns
        name: config-volume
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2021-11-04T13:51:08Z"
    lastUpdateTime: "2021-11-04T13:51:52Z"
    message: ReplicaSet "coredns-74ff55c5b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-11-05T10:22:57Z"
    lastUpdateTime: "2021-11-05T10:22:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
```

Relevant excerpt from cluster-autoscaler's logs:

```shell_session
I1108 11:37:12.118398       1 cluster.go:148] Fast evaluation: playground-stage-md-0-q6cd9 for removal
I1108 11:37:12.118532       1 cluster.go:169] Fast evaluation: node playground-stage-md-0-q6cd9 cannot be removed: non-daemonset, non-mirrored, non-pdb-assigned kube-system pod present: coredns-74ff55c5b-664d5
```

**Environment:**

- Cluster-api version: v0.4.4
- Minikube/KIND version: n/a
- Kubernetes version: v1.21.6 (workload) & v1.21.5-gke.1802 (management)
- OS (e.g. from `/etc/os-release`): n/a

/kind bug

/area networking
/area upgrades
/area dependency
