### ISSUE TITLE
ClusterClass patches: Allow matching all MachineDeploymentClasses

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5648]
**User Story**

As a user I would like to be able to configure patches which apply to all MachineDeploymentClasses of a ClusterClass without listing them explicitly.

**Detailed Description**

Currently a PatchSelector only allows explicit matching:
```yaml
        matchResources:
          machineDeploymentClass:
            names:
            - linux-worker
            - windows-worker
```

It's cumbersome to be forced to list all MachineDeploymentClasses explicitly. Thus we want to allow the following:
```yaml
        matchResources:
          machineDeploymentClass:
            names:
            - '*'
```

This would be consistent with the way "match all" is implemented in ClusterRoles/Roles. Let's try to have the same semantics for edge cases like:
```yaml
        matchResources:
          machineDeploymentClass:
            names:
            - '*'
            - default-worker
```
(I assume it still matches all, but to be verified)

**Anything else you would like to add:**

Depends on https://github.com/kubernetes-sigs/cluster-api/pull/5583 being merged.

The change is to adjust the matching logic in the JSON patch generator (`templateMatchesSelector`), add corresponding unit tests and document the new semantic in the Go type.

[Miscellaneous information that will assist in solving the issue.]

/kind feature
