### ISSUE TITLE
Machine Controller FailureDomain handling is inconsistent with KCP

### ISSUE THREAD

**Issue by Arvinderpal** [kubernetes-sigs/cluster-api#5666]
KCP and Machine controller are inconsistent in their handling of FalureDomains (FDs). 

KCP [picks an FD](https://github.com/kubernetes-sigs/cluster-api/blob/fc480622663ae4117ad94a912c51e31df78591db/controlplane/kubeadm/internal/control_plane.go#L98) from Cluster.Status.FailureDomains and [puts it in](https://github.com/kubernetes-sigs/cluster-api/blob/58905fb5140a7844c3e24aa70d255fb8f9d0c491/controlplane/kubeadm/controllers/helpers.go#L286) Machine.Spec.FailureDomain. 
Machine Controller, on the other hand, is [looking for it](https://github.com/kubernetes-sigs/cluster-api/blob/58905fb5140a7844c3e24aa70d255fb8f9d0c491/controllers/machine_controller_phases.go#L302) in the ProviderMachine.Spec.FailureDomain. 

This seems like stale code that was never migrated to the new way of handling failuredomains. [See CAPI docs](https://cluster-api.sigs.k8s.io/developer/providers/machine-infrastructure.html?highlight=failuredomain#data-types).

**What steps did you take and what happened:**
I created a DockerCluster and specified the FDs below:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  failureDomains:
    fd1: 
      controlPlane: true
    fd2: 
      controlPlane: true
    fd3: 
      controlPlane: false
```

**What did you expect to happen:**

I expected the `Machine.Spec.FailureDomain` for both the KCP and MD machines to contain a selected FD. However, it was only present on the Machines associated with KCP. MD Machines never had the value set. 

**Anything else you would like to add:**

We should make machine-controller handling consistent with KCP: the machine-controller should pick a FD from the Cluster.Status.FailureDomains the same way KCP does. 

/kind bug
