### ISSUE TITLE
Deploy Provider CRs during tilt up

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5676]
**User Story**

As a developer I would like `tilt up` to result in a dev environment which is as compatible as possible with one set up via `clusterctl init`

**Detailed Description**

The biggest gap is that `tilt up` currently does not deploy the `Provider` CRDs and CRs.

The CRDs can be generated via: `kustomize build cmd/clusterctl/config/crd`

A `Provider` CR looks like this:
```yaml
apiVersion: clusterctl.cluster.x-k8s.io/v1alpha3
kind: Provider
metadata:
  labels:
    cluster.x-k8s.io/provider: bootstrap-kubeadm
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/core: inventory
  name: bootstrap-kubeadm
  namespace: capi-kubeadm-bootstrap-system
providerName: kubeadm
type: BootstrapProvider
version: v1.0.99
```

I think we have two options to get the values to be able to generate a `Provider` CR:
1. Add additional config to the tilt-settings.json
2. Calculate the CR based on the provider YAMLs (which is a bit hacky)

E.g. 2. could use the `Namespace` resource as basis:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    cluster.x-k8s.io/provider: bootstrap-kubeadm
    control-plane: controller-manager
  name: capi-kubeadm-bootstrap-system
```
I think everything except the version can be calculated based on the `Namespace`. We can (probably?) just hard-code the version like we do it in our e2e test config (`docker.yaml`), if not we can provide a field for it in tilt-settings.json.

P.S. I know 2 is hacky, but maybe it's good enough for the dev setup.

**Anything else you would like to add:**

My concrete use case is I want to be able to use a cluster setup with `tilt up` during e2e test (with `-e2e.use-existing-cluster=true`). It already works, but only with some manual effort.

/kind feature
