### ISSUE TITLE
ClusterClass: MachineDeployment variable overrides

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5927]
**User Story**

As a user I would like to be able to create MachineDeployments with different configurations using ClusterClass, without having to duplicate MachineDeploymentClasses in the ClusterClass.

**Detailed Description**

Context:
Today, variables in general allow customization of individual clusters. This means that the cluster as a whole can be customized by specifying variables when creating a cluster. For example, a ClusterClass can have a `region` variable and then it's possible to create clusters in different regions with the same ClusterClass by just setting the `region` variable on cluster creation.

Of course, we expect to be able to do the same with MachineDeploymentClasses. For example, we want to be able to define a MachineDeploymentClass once in a ClusterClass and then be able to use it multiple times with different configurations by specifying multiple MachineDeployment topologies in the cluster.

For example:
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: quick-start
spec:
  ...
  workers:
    machineDeployments:
    - class: default-worker
        ...
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: my-cluster
spec:
  ...
  topology:
    class: quick-start
    ...
    workers:
      machineDeployments:
      - class: "default-worker"
        name: "large-nodes"
        replicas: 1
      - class: "default-worker"
        name: "small-nodes"
        replicas: 1
```

We can now customize metadata, replicas and failureDomain for individual MachineDeployments. To be able to also customize the size of a worker machine, we would now introduce a variable called `workerMachineType`. Unfortunately, we cannot set the `workerMachineType` variable to different values for different MachineDeployments today. Our only option now with the current implementation is to duplicate the whole `MachineDeploymentClass` (including the `InfrastructureMachineTemplate`).

This means that users have to add new slightly different MachineDeploymentClasses to a ClusterClass whenever they need a new machine type. If additional configuration like e.g. disk size should differ n (# types) x m (# disk sizes) MachineDeploymentClasses are required. This escalates quickly if a few more configuration options are required.

This limits the re-usability of MachineDeploymentClasses in ClusterClass. We now want to make it possible to customize individual MachineDeploymentClasses, just like we can customize other parts of the cluster today. 

**Proposed solution:**

Given our current implementation, it would be easy to introduce variable overrides for MachineDeployments.
This would look like this:
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: my-cluster
spec:
  ...
  topology:
    class: quick-start
    ...
    workers:
      machineDeployments:
      - class: "default-worker"
        name: "large-nodes"
        replicas: 1
      - class: "default-worker"
        name: "small-nodes"
        replicas: 1
        variables:
          overrides:
          - name: workerMachineType
            value: t3.small
    variables:
    - name: workerMachineType
      value: t3.large
```

When reconciling the topology we would simply use the override value instead of the value of the top-level variable.

In the initial implementation we would use the entire override value instead of the top-level value. In the future, (based on feedback) we could implement more sophisticated merging strategies for overrides of complex variables.

With this small change we would allow ClusterClass to cover a lot of additional use cases and avoid duplication of MachineDeploymentClasses when writing ClusterClasses.

A POC can be found here: https://github.com/kubernetes-sigs/cluster-api/pull/5928

[Miscellaneous information that will assist in solving the issue.]

/kind feature

P.S. Thx to @vuil and @imikushin for the feedback!
