### ISSUE TITLE
ClusterClass: MHC reconciliation is not authoritative

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#5948]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**
I expect the MHC reconciliation to be authoritative (similar to the reconciliation of other resources).

Example:

I add one field after another to the MHC config in the ClusterClass:
```yaml
      maxUnhealthy: 50%
      unhealthyRange: "[1-2]"
      nodeStartupTimeout: "0"
      unhealthyConditions:
      - type: Ready
        status: Unknown
        timeout: 300s
      - type: Ready
        status: "False"
        timeout: 300s
      remediationTemplate:
        apiVersion: abc/v1beta1
        kind: ABCRemediation
        name: default
        namespace: default
```
The fields are correctly propagated/reconciled to the MHC.

Then I drop one of the fields (except unhealthyConditions). 
I now expect the topology controller to try to remove the field 
(and the webhook would set the default value again).

Instead the field just stays set to the value I previously had in the ClusterClass.

**Anything else you would like to add:**
In other cases this is implemented by tracking the managed fields.

**Environment:**

- Cluster-api version: main

/kind bug
/area topology
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
