### ISSUE TITLE
MachinePool workers support in ClusterClass

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api#5991]
**User Story**

As a user, I would like to create a ClusterClass-based Cluster where workers are managed using MachinePools instead of MachineDeployments. This allows me, for example, to use ClusterClass with an infrastructure provider "flavor" like Cluster API Azure Provider Managed AKS, which supports only MachinePools.

**Detailed Description**

I want to be able to define a ClusterClass where workers are managed using MachinePools instead of MachineDeployments.

```yaml
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: example
spec:
  controlPlane:
...
  workers:
    machinePools:
      - class: example
        template:
          spec:
            clusterName: example
            replicas: 10
            template:
              spec:
                bootstrap:
                  ref:
                    apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
                    kind: KubeadmConfigTemplate
                    name: example-pool-0
                clusterName: example
                infrastructureRef:
                  apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
                  kind: AzureManagedMachinePool
                  name: example-pool-0
                version: 1.22.4
  infrastructure:
...
```

**Anything else you would like to add:**

This issue follows up on a [slack conversation](https://kubernetes.slack.com/archives/C8TSNPY4T/p1638289221256300?thread_ts=1638288074.252700&cid=C8TSNPY4T).

## Tasks

[EDIT: by @sbueringer] After further discussion we would implement this with the following sub-tasks:

### APIs #8820 

* [x] Extend APIs (api/v1beta1)
  * Cluster
    * WorkersTopology: Add MachinePoolTopology slice
  * ClusterClass
    * WorkersClass: Add MachinePoolClass slice
    * PatchSelectorMatch: Add MachinePool
  * Note: excluding MachineHealthCheck fields

### Controllers, webhooks, ... #9016

* [x] Reconcile MachinePools in Cluster topology (internal/controllers/topology/cluster)
  * Basic reconcile
    * blueprint.go: also get MachinePool blueprint
    * current_state.go: also get MachinePool current state
    * desired_state.go: calculate desired MachinePool like MachineDeployment
    * reconcile_state.go: reconcile MachinePool like MachineDeployment
    * cluster_controller.go: also watch MachinePools
    * Surface MachinePool state like MachineDeployment state in conditions (conditions.go)
  * Support patching MachinePools:
    * Extend patch engine to also handle MachinePools
    * Extend json patch generator to handle MachinePools
    * Add MachinePool builtin variables
* [x] Add corresponding validation in internal/webhooks/
  * Includes additions in internal/topology/check/ & internal/topology/variables/{cluster_variable_defaulting.go, cluster_variable_validation.go}
* [x] Extend internal/controllers/ClusterClass
  * Add the same that we already have for MachineDeployments
* [x] Extend CAPD
  * Add DockerMachinePoolTemplate
* [x] Extend test/extension
  * Also patch DockerMachinePoolTemplate
* [x] Extend quickstart test to also cover MachinePools

### unit & integration tests

Take a look at the existing tests and the code added for MachinePools and add test coverage accordingly for MachinePools.

Cluster topology controller:
  * [x] internal/controllers/topology/cluster/blueprint_test.go #9348 @willie-yao 
  * [x] internal/controllers/topology/cluster/current_state_test.go #9348 @willie-yao 
  * [x] internal/controllers/topology/cluster/desired_state_test.go #9348 @willie-yao 
  * [x] internal/controllers/topology/cluster/reconcile_state_test.go #9380 @willie-yao 
  * [x] internal/controllers/topology/cluster/cluster_controller_test.go #9380 @willie-yao 
  * [x] internal/controllers/topology/cluster/conditions_test.go #9380 @willie-yao 
  * [x] internal/controllers/topology/cluster/scope/scope_test.go @razashahid107
  * [ ] internal/controllers/topology/cluster/scope/state_test.go
  * [ ] internal/controllers/topology/cluster/scope/upgradetracker_test.go

Inline patching:
  * [x] internal/controllers/topology/cluster/patches/inline/json_patch_generator_test.go #9474 @johannesfrey 
  * [x] internal/controllers/topology/cluster/patches/variables/variables_test.go #9372 @johannesfrey 
  * [x] internal/controllers/topology/cluster/patches/engine_test.go #9373 @johannesfrey 

Webhooks:
  * [ ] internal/topology/check/compatibility_test.go
  * [ ] internal/webhooks/cluster_test.go
  * [ ] internal/webhooks/clusterclass_test.go
  * [ ] internal/webhooks/patch_validation_test.go

ClusterClass controller:
  * [ ] internal/controllers/clusterclass/clusterclass_controller_test.go

External patching: test extension:
  * [ ] test/extension/handlers/topologymutation/handler_test.go

clusterctl alpha topology dry-run:
  * [ ] cmd/clusterctl/client/cluster/topology_test.go

Verification:
* [ ] Run unit & integration tests with coverage and check if we missed something

### e2e tests

* First wave:
  * [x] Quickstart (quick_start.go, flavor: "topology,topology-dualstack-.*") #9393 @willie-yao 
  * [x] Kubernetes upgrade (cluster_upgrade.go, flavors: "upgrades,topology,kcp-scale-in") https://github.com/kubernetes-sigs/cluster-api/pull/9502 @willie-yao 
    * The ClusterClass code path should use MPs via CC
* Afterwards:
  * [ ] ClusterClass changes & rollout (clusterclass_changes.go & clusterclass_rollout, flavor: "topology")
    * Ensure assert also verifies the labels/annotations (also in-place rollout of them)
  * [ ] clusterctl upgrade (clusterctl_upgrade.go, workload flavor: "topology")
  * [ ] Runtime SDK (cluster_upgrade_runtimesdk.go, flavor: "upgrades-runtimesdk")
  * [ ] Self-hosted (self_hosted.go, flavor: "topology")
  * [ ] Autoscaler (autoscaler.go, flavor: "topology-autoscaler")
  * [ ] Dualstack e2e tests
* [ ] Audit if there are any Cluster YAMLs left in the test folder which don't have a machinePool in Cluster.spec.topology

### Misc

* [ ] TBD: internal/controllers/topology/machinepool might be not needed as MachinePool.reconcileDelete deletes templates

### Documentation

* [ ] Update proposal
* [ ] Update docs (probably mostly book)
  * lifecycle hooks
  * builtin variables

### Later

* TBD: consider de-duplicating MD/MP code
  * [Stefan]: Did some deduplication. I personally would keep everything else separate, but open to discussions
* TBD: MachinePool upgrading use Node list instead of Node get
* MHC for MachinePools: depends on MachinePool Machines

/kind feature

**Comment by sbueringer** [comment]
Thx for filing this issue. 
As mentioned in the linked thread, +1 if we don't have any concerns about embedding support for an experimental feature in another experimental feature (which leaks into the non-experimental Cluster resource :)).

Nit regarding the YAML. I would imagine it to look ~ like this:
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: example
spec:
  controlPlane:
...
  workers:
    machinePools:
    - class: example
       template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: KubeadmConfigTemplate
              name: example-pool-0
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: AzureManagedMachinePool
              name: example-pool-0
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: example
  topology:
    class: example
    version: v1.22.4
    ...
    workers:
      machinePools:
      - class: "example"
        name: "mp-0"
        replicas: 10
```
