### ISSUE TITLE
Duplicate resources are created when template is used both as controlPlane ref and infrastructure ref in ClusterClass

### ISSUE THREAD

**Issue by pydctw** [kubernetes-sigs/cluster-api#6126]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

While doing a PoC of creating an EKS cluster using ClusterClass (CAPI + CAPA), I noticed that two AWSManangedControlPlane (awsmcp) are created from AWSManangedControlPlaneTemplate (awsmcpt) when there should be only one awsmcp. For context, EKS uses an AWS managed control plane so AWSManangedControlPlane in CAPA is the counterpart of KubeadmControlPlane in CAPI.

```
$ kubectl get cluster -n eks
NAME                PHASE         AGE     VERSION
my-eks-cluster-2    Provisioned   2d20h   v1.21.2
```

```
$ kubectl get awsmcp -n eks
NAME                              CLUSTER             READY   VPC                     BASTION IP
my-eks-cluster-2-84g7h            my-eks-cluster-2    true    vpc-0fd430763e64830ee
my-eks-cluster-2-c4vqb            my-eks-cluster-2    true    vpc-06b20d0d9d5eae93d
```

Further debugging suggests that this is due to the fact AWSManagedControlPlaneTemplate is used both as`spec.controlPlane.ref` and `spec.infrastructure.ref` in ClusterClass and CAPI controller clones them twice. FYI, there is no AWSManagedCluster type in CAPA.

ClusterClass used for EKS.
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: eks-clusterclass-v1
  namespace: eks
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: AWSManagedControlPlaneTemplate
      name: eks-clusterclass-v1-awsmcp
  infrastructure:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: AWSManagedControlPlaneTemplate
      name: eks-clusterclass-v1-awsmcp
  workers:
    machineDeployments:
      - class: default-worker
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: EKSConfigTemplate
              name: eks-clusterclass-v1-eksconfigtemplate
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: AWSMachineTemplate
              name: eks-clusterclass-v1-worker-machinetemplate
```

This is creating an extra EKS control plane and related infrastructure in AWS and causing panics in CAPA controller.

**What did you expect to happen:**
Only one AWSManangedControlPlane is created.

**Anything else you would like to add:**

**Environment:**

- Cluster-api version: v1.1.1
- Minikube/KIND version: v0.11.1
- Kubernetes version: (use `kubectl version`): v1.21.2
- OS (e.g. from `/etc/os-release`): MacOS

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
