### ISSUE TITLE
ClusterClass MachineHealthCheck should be patchable for individual clusters

### ISSUE THREAD

**Issue by tenczar** [kubernetes-sigs/cluster-api#6139]
**User Story**

As a user I would like to apply patches to machinehealthchecks on clusters derived from clusterclasses to customize health checks for my cluster. 

**Detailed Description**

At a minimum it would be useful as a user to enable/disable the machinehealthchecks defined on a cluster without needing separate clusterclass definitions for each. Being able to modify the timeouts defined by the machinehealthcheck in the clusterclass would be the next highest priority.
**Anything else you would like to add:**

Here is an example of how tanzu framework customizes machinehealthchecks today https://github.com/vmware-tanzu/tanzu-framework/blob/main/pkg/v1/providers/ytt/03_customizations/add_mhc.yaml

/kind feature

**Comment by killianmuldoon** [comment]
@tenczar Thanks for filing the issue - I'll take a look

**Comment by ykakarap** [comment]
We can do the following for topology based clusters to have cluster specific MHC:
With an example ClusterClass:
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: "demo"
spec:
  controlPlane:
    ref:
      ...
    machineInfrastructure:
      ...
    machineHealthCheck:
      unhealthyConditions:
        - type: Ready
          status: Unknown
          timeout: 300s
        - type: Ready
          status: "False"
          timeout: 300s
  ...
```
We can enabled/disable the control plane MHC for a Cluster using the above ClusterClass using a new `machineHealthCheck.disabled` field in cluster topology. Example:
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "example"
spec:
  ...
  topology:
    class: demo
    controlPlane:
      ...
      machineHealthCheck:
        disabled: true
```
By setting `disabled` to `true` no MHC for the control plane for this cluster will be created. If `unset` or set to `false` the `machineHealthCheck` definition from ClusterClass will be used to create an MHC for the control plane. A similar api will exist for MHC for machine deployments.

If a user wishes to have a Cluster specific MHC we can do it by defining it in Cluster topology. Example:
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "example"
spec:
  ...
  topology:
    class: demo
    controlPlane:
      ...
      machineHealthCheck:
        maxUnhealthy: 1
        unhealthyRange: 1
        nodeStartupTimeout: 12m
        unhealthyConditions:
        - type: Ready
          status: Unknown
          timeout: 300s
        - type: Ready
          status: "False"
          timeout: 302s
```
With this the MHC definition provided in the ClusterClass will be discarded and an MHC will be created using the definition from cluster topology. Note that the MHC definition here will be considered as atomic, meaning the full definition of the target MHC needs to be provided in Cluster topology if the user does not want to use the one defined in ClusterClass.

If MHC is enabled and a definition is not provided in Cluster topology then the definition provided in ClusterClass will be used.

**Comment by sbueringer** [comment]
As discussed, seems to be the best way to model the API given edge cases, so +1 from my side

**Comment by killianmuldoon** [comment]
One question (and a comment 🙂) - if we're doing implicit overriding of Cluster -> ClusterClass why do we need a boolean for enabling / disabling? We could set it to `nil` at this point and overwrite it that way. 

This gets rid of some confusing situations around `disabled` e.g. does it just disable the MHC at the ClusterClass level or also at the Cluster level. What happens if we set disabled=true and define MHC fields? If we go this direction we should definitely enforce this decision making in the webhook to make it really explicit.

If we're going to use a boolean I'd prefer `enabled` over `disabled` but absolutely not a blocker.

**Comment by sbueringer** [comment]
The problem is how you can differentiate between "disable" and "no override".

We would only allow combinations of fields that make sense (aka you can only set other fields if the MHC is not disabled).

> If we're going to use a boolean I'd prefer enabled over disabled but absolutely not a blocker.

The only problem with enabled is the zero value. If you set other fields to overwrite you also have to set enabled: true, because the go zero value is otherwise enabled: false.

**Comment by killianmuldoon** [comment]
> The problem is how you can differentiate between "disable" and "no override" (nil can't express both)

I understand the need for the `disable` field now, and I guess this is the simplest expression of it (even if it is a bit complex)

> If you set other fields to overwrite you also have to set enabled: true, because the go zero value is otherwise enabled: false.

We can default this value to true in e.g. the webhook so I don't see that as much of an issue if it's a better API, but whether it is is a matter of opinion 😄. I definitely think double negation at this level could be confusing for users.

**Comment by ykakarap** [comment]
Just to be clear: if `disabled` is set to `true` no MHC will be created irrespective of it being defined in the ClusterClass or Cluster (we can additionally add a check in the Cluster webhook so that MHC is not defined in a Cluster if `disabled` is true.)

The reason for going with `disabled` is to make opting out of MHC an explicit action. If `false` or nil (will probably be the more common way) an MHC will be created. 

>I definitely think double negation at this level could be confusing for users.

I think you are referring to `disabled: false` case to enable the MHC. I think most users will probably just not set `disabled` to create the MHC (based on either the ClusterClass or Cluster).
Example: 
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "example"
spec:
  ...
  topology:
    class: demo
    controlPlane:
       replicas: 3
```
will create a Cluster with an MHC.

**Comment by ykakarap** [comment]
After further discussions the we would like to recommend the following approach to have the ability to enable/disable an MHC per cluster and also provide a mechanism to override an MHC on a per Cluster basis:

For the Cluster topology, we would like to add an optional section named `machineHealthCheck` which would look like so:

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "example"
spec:
  ...
  topology:
    class: demo
    controlPlane:
      ...
      machineHealthCheck:
        # set to enable/disable the MHC on a per cluster basis.
        enable: (true | false | <not set>)
        
        # set the fields to override the MHC in ClusterClass.
        # MHC definition will be considered atomic. 
        # Fields from ClusterClass and Cluster topology will not be merged.
        # If specified MHC in Cluster topology will take precedence.
        maxUnhealthy: 1
        unhealthyRange: 1
        nodeStartupTimeout: 12m
        unhealthyConditions:
        - type: Ready
          status: Unknown
          timeout: 300s
        - type: Ready
          status: "False"
          timeout: 302s
```

The `machineHealthCheck.enable` field can be one of:
* `false`
    * If the value is set to `false` then no MHC will be created. This is irrespective of any MHC defined in the ClusterClass or any overrides defined in the Cluster topology.
* nil (not set)
    * If the `enable` field is not set then CAPI will inherit the MHC from either the ClusterClass or the Cluster topology. (MHC in Cluster topology will take precedence over MHC in ClusterClass). If no MHC is defined in ClusterClass or Cluster topology then no MHC will be created.
* `true`
    * If the value is set to `true` then an MHC is garunteed to be created. The cluster webhook will block the request if no MHC is defined in the ClusterClass or in the Cluster topology. 



**Additional details:**
* A validation will be added to Cluster webhook to make sure that an MHC is defined in the Cluster topology or in the ClusterClass if `.machineHealthCheck.enable` is set to `true`.
* Similarly, a validation will be added to ClusterClass to make sure that an MHC definition cannot be deleted from the ClusterClass if it is being used by a Cluster which has `.machineHealthCheck.enable` is set to `true`.

cc @vincepri @fabriziopandini @sbueringer 

cc @tenczar
