### ISSUE TITLE
Add patchMergeKey annotations to allow Kustomize overrides of list element fields

### ISSUE THREAD

**Issue by johananl** [kubernetes-sigs/cluster-api#6147]
**User Story**

As a developer I would like to be able to override fields of list elements in CAPI types using Kustomize so that I can leverage Kustomize for keeping workload cluster templates DRY.

**Detailed Description**

Kustomize is used by CAPI providers to keep cluster templates DRY. Example: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/4b535f6befba3b08dee7250d7dd83590757709ad/test/e2e/data/infrastructure-vsphere/kustomization/conformance/kustomization.yaml#L1

```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  ...
spec:
  kubeadmConfigSpec:
    ...
    files:
    - content: |
        foo
      path: /tmp/foo
      permissions: "0644"
```

Assume I want to use Kustomize to override the `permissions` field of the `files` entry above (but keep the `content` and any other field intact). At the moment, patching the list element using Kustomize **replaces** the list element rather than patch it.

As far as I can tell, this is caused by the fact that the `File` type doesn't have a `patchMergeKey` annotation (which should probably be on the `path` field):

https://github.com/kubernetes-sigs/cluster-api/blob/8059056ba0393039e14a64acab326183d3d7d0d0/bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go#L211

Relevant info: https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#merge-individual-elements-of-a-list-of-complex-elements

I'm wondering if adding a `patchMergeKey` annotation for all the CAPI types makes sense. Looking at the repo, it seems there is only one annotated type:

https://github.com/kubernetes-sigs/cluster-api/blob/58905fb5140a7844c3e24aa70d255fb8f9d0c491/api/v1alpha3/common_types.go#L189

**Anything else you would like to add:**

None

/kind feature
