### ISSUE TITLE
Support append for files in KubeadmConfigTemplate and KubeadmControlPlane

### ISSUE THREAD

**Issue by gnadaban** [kubernetes-sigs/cluster-api#6156]
**User Story**

As an operator I would like to configuer a larger `fs.inotify.max_user_watches` in `/etc/sysctl.conf` for the nodes using the `files:` block in order to avoid errors about not enough disk space when attempting to follow logs.

```yaml
  files:
        - content: "fs.inotify.max_user_watches=12345678"
          owner: root:root
          path: /etc/sysctl.conf
          permissions: "0644"
          append: true
```

**Detailed Description**

In order to append to files, the `append: true` flag for cloud-init must be supported.

**Anything else you would like to add:**

/kind feature
