### ISSUE TITLE
`clusterctl alpha topology plan` fails if infrastructure resource version does not match CAPI Contract Version 

### ISSUE THREAD

**Issue by apricote** [kubernetes-sigs/cluster-api#6220]
**What steps did you take and what happened:**

- Clone `cluster-api`
- Clone `cluster-api-provider-openstack`
- Create `tilt-settings.yaml`:
  
  ```yaml
  default_registry: "localhost:5000"
  provider_repos:
    - ../cluster-api-provider-openstack
  enable_providers:
    - openstack
    - kubeadm-bootstrap
    - kubeadm-control-plane
  kustomize_substitutions:
    CLUSTER_TOPOLOGY: "true"
  ```
- Create local kind cluster with `hack/kind-install-for-capd.sh`
- Deploy with tilt `tilt up` and wait until everything is ready
- Build clusterctl (or use latest release): `make clusterctl; export PATH=bin/:$PATH`
- Create file `cluster-resources.yaml`

  <details><summary>File Content</summary>

  ```yaml
  apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
  kind: KubeadmConfigTemplate
  metadata:
    name: default-worker
  spec:
    template:
      spec:
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
            name: '{{ local_hostname }}'
  ---
  apiVersion: cluster.x-k8s.io/v1beta1
  kind: Cluster
  metadata:
    name: example-cluster
  spec:
    topology:
      class: default-class
      controlPlane:
        replicas: 3
      version: v1.23.3
      workers:
        machineDeployments:
        - class: default-worker
          failureDomain: Zone1
          name: md-0
          replicas: 1
  ---
  apiVersion: cluster.x-k8s.io/v1beta1
  kind: ClusterClass
  metadata:
    name: default-class
  spec:
    controlPlane:
      machineInfrastructure:
        ref:
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
          kind: OpenStackMachineTemplate
          name: default-class-control-plane
      ref:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        name: default-class
    infrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: OpenStackClusterTemplate
        name: default-class
  
    workers:
      machineDeployments:
      - class: default-worker
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: KubeadmConfigTemplate
              name: default-class-worker
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
              kind: OpenStackMachineTemplate
              name: default-class-worker
  ---
  apiVersion: controlplane.cluster.x-k8s.io/v1beta1
  kind: KubeadmControlPlaneTemplate
  metadata:
    name: default-class
  spec:
    template:
      spec:
        kubeadmConfigSpec:
          clusterConfiguration:
            apiServer:
              extraArgs:
                cloud-provider: external
            controllerManager:
              extraArgs:
                cloud-provider: external
          initConfiguration:
            nodeRegistration:
              kubeletExtraArgs:
                cloud-provider: external
              name: '{{ local_hostname }}'
          joinConfiguration:
            nodeRegistration:
              kubeletExtraArgs:
                cloud-provider: external
              name: '{{ local_hostname }}'
  ---
  apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
  kind: OpenStackClusterTemplate
  metadata:
    name: default-class
  spec:
    template:
      spec:
        cloudName: openstack
        identityRef:
          kind: Secret
          name: cloud-config
        managedAPIServerLoadBalancer: true
        managedSecurityGroups: true
        nodeCidr: 10.6.0.0/24
  ---
  apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
  kind: OpenStackMachineTemplate
  metadata:
    name: default-class-control-plane
  spec:
    template:
      spec:
        cloudName: openstack
        flavor: foobar
        identityRef:
          kind: Secret
          name: cloud-config
        image: capi-v1.23.3
  ---
  apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
  kind: OpenStackMachineTemplate
  metadata:
    name: default-class-worker
  spec:
    template:
      spec:
        cloudName: openstack
        flavor: foobar
        identityRef:
          kind: Secret
          name: cloud-config
        image: capi-v1.23.3
  ```

  </details>

Then I executed the command and got following response:

```shell
$ clusterctl alpha topology plan -f cluster-resources.yaml -o output/ 
Detected a cluster with Cluster API installed. Will use it to fetch missing objects.
Error: failed to dry run the topology controller: error reading the ClusterClass: failed to get infrastructure cluster template for ClusterClass/default-class: failed to retrieve OpenStackClusterTemplate "default-class" in namespace "default": failed to retrieve OpenStackClusterTemplate external object "default"/"default-class": no matches for kind "OpenStackClusterTemplate" in version "infrastructure.cluster.x-k8s.io/v1beta1"
```

**What did you expect to happen:**

I expected `clusterctl alpha topology plan` to output a valid plan about the required topology changes, as CAPO conforms to the Provider Contract v1beta and I was able to succesfully create a cluster using `ClusterClass` with CAPO previously (not with the example manifests provided here in this issue).

**Anything else you would like to add:**

The error message is (in itself) correct, there is no `"OpenStackClusterTemplate" in version "infrastructure.cluster.x-k8s.io/v1beta1)"`, CAPO only has released `v1alpha4` CRDs so far. `util/conversion.UpdateReferenceAPIContract()` changes the referenced API version from `v1alpha4` to `v1beta1`.

It looks like `util.GetGVKMetadata` returns invalid labels in my local test setup with Kind (v1.23.3) and Tilt. According to `GetGVKMetadata` the CRD has exactly one label `cluster.x-k8s.io/v1beta1: v1beta1`, but the actual labels differ:

```shell
$ k get crd openstackclustertemplates.infrastructure.cluster.x-k8s.io -o=jsonpath='{.metadata.labels}' | jq
{
  "cluster.x-k8s.io/provider": "infrastructure-openstack",
  "cluster.x-k8s.io/v1alpha3": "v1alpha3",
  "cluster.x-k8s.io/v1alpha4": "v1alpha4",
  "cluster.x-k8s.io/v1beta1": "v1alpha4"
}
```

There is some [previous discussion](https://app.slack.com/client/T09NY5SBT/C8TSNPY4T/thread/C8TSNPY4T-1646060493.961359) to this issue in Slack.

**Environment:**

- Cluster-api version: `main` / 207e2a8c0ccf9ac584450d88d0742571f2874205
- Minikube/KIND version: `kind version 0.11.1`
- Kubernetes version: (use `kubectl version`): `Client v1.23.4, Server v1.23.3`
- OS (e.g. from `/etc/os-release`): `Arch Linux`

/kind bug
/area clusterctl
/area topology
