### ISSUE TITLE
ClusterClass Patches add operation can not concatenate a list to existing list

### ISSUE THREAD

**Issue by weikaipan** [kubernetes-sigs/cluster-api#6245]
**User Story**

As a operator I would like to author a patch that create a list of items and concatenate it to an existing list for users who supply an unknown size of list in `Cluster` `Variables`

**Detailed Description**

`ClusterClass`
```yaml
patches:    
  - name: foo
      definitions:
      - selector:
          apiVersion: vmware.infrastructure.cluster.x-k8s.io/v1beta1
          kind: VSphereMachineTemplate
          matchResources:
            controlPlane: true
        jsonPatches:
          - op: add
            path: /spec/template/spec/volumes/-
            valueFrom:
              template: |
                {{- range .var }}
                - capacity:
                  name: {{ .name }}
                {{- end }}
```
`Cluster`

```yaml
  variables:
      - name: var
        value:
          - name: 'foo'
          - name: 'bar'
```

`VSphereMachineTemplate`

```yaml
---
apiVersion: vmware.infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: "foo"
spec:
  template:
    spec:
      volumes: []
```

This results in error below

```yaml
 FieldValueInvalid: spec.template.spec.volumes: Invalid value: \"array\": spec.template.spec.volumes in body must be of type object: \"array\""
```

Since currently appending a list to a list resulting a nested list.
https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/tasks/experimental-features/cluster-class/write-clusterclass.md#writing-json-patches

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by sbueringer** [comment]
I'm not sure how we can implement it given that JSON patch does not support any such operation.

Do you have an idea how this can be solved within the limitations of the JSON Patch RFC6902 spec that we're using?

(related #5944)

**Comment by weikaipan** [comment]
I tried to initialize a list by add operation.
So I still use go-template to range over a list of items, and use `add` with `/spec/template/spec/kubeadmConfigSpec/files` instead of `/spec/template/spec/kubeadmConfigSpec/files/-`.

As long as the stanza is empty, the json patch creates a list for me. But it means only the first patch to that stanza can work like _concatenation_.

```yaml
       jsonPatches:
          - op: add
            path: /spec/template/spec/kubeadmConfigSpec/files
            valueFrom:
              template: |
                {{- range .foo }}
                content: |
                  {{ .data }}
                {{- end }}
```

**Comment by sbueringer** [comment]
Yup. I think that's how JSON Patches (RFC6902) work. I think if the array essentially does not exist, it is added. If it already exists it adds it as an array element.

**Comment by weikaipan** [comment]
But it implies that if I have another array type variable called `.bar`. The same pattern doesn't work because `files` is already added. Is it right?

**Comment by sbueringer** [comment]
Yup definitely. In general adding an array to an existing array will lead to the nested array. Independent how that situation occurs (from two variables or if the array already exists before)

**Comment by killianmuldoon** [comment]
@sbueringer should we close #5944 in favor of this? It seems to cover the same ground, just in a less detailed way.

**Comment by sbueringer** [comment]
Sounds good. I think at some point we mainly wanted to document the limitation in #5944. But as that's done we can close it. (I'll do it)

**Comment by sidharthsurana** [comment]
One possible way of solving this might to enhance the `ClusterClassPatch` type to include a looping construct
https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1beta1/clusterclass_types.go#L313

Examples of similar idea can be seen in ansible task loops construct https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html

The idea would be something like below:

`Cluster`

```
  variables:
      - name: var
        value:
          - name: 'foo'
          - name: 'bar'
```

`ClusterClass`
```
patches:    
  - name: foo
    definitions:
     - selector:
          apiVersion: vmware.infrastructure.cluster.x-k8s.io/v1beta1
          kind: VSphereMachineTemplate
          matchResources:
            controlPlane: true
        jsonPatches:
          - op: add
            path: /spec/template/spec/volumes/-
            valueFrom:
              template: |
                - capacity:
                  name: {{ .name }}
    with_items: {{ .var }}
```


The above code then could iteratively apply new jsonpatch add within the guideline on the RFC and still provide a solution.

**Comment by fabriziopandini** [comment]
/milestone v1.2
Personally, I think that the long-term answer for all the advanced patching use cases is external patches based on Runtime SDK, and this use case is a good candidate because we are hitting the limit of JSONpatch specification.

However, given that Runtime SDK/external patches is still a WIP we also could consider an option that does not require API changes / adding other abstractions/constructs on top of JSON patches, based on the idea of surfacing a new built-in variable with the current value being replaced and then rely on sprig functions.

The expected result should be something like

```
patches:    
  - name: foo
      definitions:
      - selector:
          apiVersion: vmware.infrastructure.cluster.x-k8s.io/v1beta1
          kind: VSphereMachineTemplate
          matchResources:
            controlPlane: true
        jsonPatches:
          - op: replace
            path: /spec/template/spec/volumes
            valueFrom:
              template: {{ concat .builtin.currentValue .var }}
```

But this requires a little bit of reasearch first
