### ISSUE TITLE
ClusterClass - requesting builtin variables to provide access to labels and annotations from Cluster

### ISSUE THREAD

**Issue by weikaipan** [kubernetes-sigs/cluster-api#6279]
**User Story**

As a developer I would like to access labels and annotations from `Cluster` for patching

**Detailed Description**

Our use cases define a `Cluster` object with labels and annotations in `Cluster`, `Cluster.spec.controlPlane`, and `Cluster.spec.machineDeployments`

The patch we would like to create is enabled by the values of annotation and labels, so requesting `builtin` variables to provide access to these fields.

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
 name: my-cluster-1
 namespace: default
 labels:
   label1: labelval1
spec:
 topology:
   class: my-clusterclass-1
   version: v1.21
   controlPlane:
     metadata:
       annotations:
          annotation1: string
       labels:
          label1: labelval2
     replicas: 1
   workers:
     machineDeployments:
     - metadata:
         annotations:
             annotation2: string
         labels:
             label1: labelval2
       class: ubuntu-worker
       name: ubuntu-workers
       replicas: 1
```

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature
