### ISSUE TITLE
CAPI waiting forever for the volume to be detached 

### ISSUE THREAD

**Issue by furkatgofurov7** [kubernetes-sigs/cluster-api#6285]
**What steps did you take and what happened:**

We have a use case where we are running a daemon set that mounts a volume. When draining the node, CAPI does not touch the daemon sets. Due to https://github.com/kubernetes-sigs/cluster-api/pull/4945 CAPI waits for the volumes to be detached and that is not an issue normally since all pods are deleted when draining. But since volumes are attached to the daemon set, they are never unmounted because the pod keeps running, which results in CAPI waiting forever for the volumes to be detached.  

**What did you expect to happen:**
Draining DS and detaching the volume successfully without deadlock

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:  v0.4..4
- Minikube/KIND version: NA
- Kubernetes version: (use `kubectl version`): 1.23.3
- OS (e.g. from `/etc/os-release`): SLES 15SP2

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
I think this happens because we use ignore all daemonsets: https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/machine/machine_controller.go#L532

I don't think we can just change the hard-coded value to false, maybe we should make it configurable.

**Comment by enxebre** [comment]
This is intrinsic to DaemonSets, even if it the property was true, drain would just be blocked but it won't graceful terminate the pod since it'd be automatically recreated by the DaemonSet.
To fully remove the Pod from that Node you could leverage labels/NodeSelectors so this might come in handy https://github.com/kubernetes-sigs/cluster-api/pull/6255

**Comment by maelk** [comment]
What about making it configurable whether we wait for the volumes to be all detached or not. Would it be problematic to delete a node where a daemonset still has a volume attached ? Once the node is deleted, the pod will be deleted and the pvc too. Would this be too risky ?

**Comment by sbueringer** [comment]
I think this probably depends on the infrastructure provider. I saw some weird issues in cases like this with OpenStack. But this might be due to that specific OpenStack.

In the OpenStack case the CSI pod running on that node would be responsible to unmount etc. (I don't remember the details). Not sure how safe this is in general, how graceful this will be handled by CSI and the infrastructure if a node/server is just deleted with attached volumens.

**Comment by lentzi90** [comment]
I think this old issue https://github.com/kubernetes/kubernetes/issues/54368#issuecomment-339378164 could be relevant here. It is about StatefulSets, but a DaemonSet with volumes is coming quite close.

From a safety perspective I guess the best thing would be to shutdown the node but then we are already in infrastructure provider territory.

**Comment by furkatgofurov7** [comment]
The draining of Daemonsets had been discussed in https://github.com/kubernetes/kubernetes/issues/75482 upstream k8s repo issue for a long time apparently but it has always been postponed (first been milestoned to v1.16) up until now. 
On the other hand, there is https://github.com/kubernetes-sigs/cluster-api/issues/6158 which is similar to what we have been discussing here

**Comment by enxebre** [comment]
You can use `.NodeDrainTimeout` to bypass draining after a timeout, the machine controller will proceed to delete the Node even though it has volumes attached. That would have the pertinent implications in each particular platform.

As for what cluster autoscaler does, we could consider doing something similar i.e taint deleting Nodes and evict DS pods manually. I'd question how strong is the use case as to support this opinionatedly vs enabling a consumer to do it as in https://github.com/kubernetes-sigs/cluster-api/issues/6285#issuecomment-1063967369

To get more context can you please elaborate your use case for running a DS with a volume?
Also wil

**Comment by maelk** [comment]
We have the node drain timeout, but CAPI is still blocking on the volumes even after the timeout has expired. Maybe that could be modified so that we don't wait for the volumes to be detached after the timeout has expired ? 

Regarding the use-case, we don't have much info. It is a customer using those and they did not give us any specific information.

Extending the timeout to the volumes would be acceptable solution for us.

**Comment by enxebre** [comment]
> We have the node drain timeout, but CAPI is still blocking on the volumes even after the timeout has expired.

@maelk By looking a the code I'd be surprised if that's the case, can you validate/confirm share logs?
https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/machine/machine_controller.go#L309-L353

**Comment by enxebre** [comment]
/priority awaiting-more-evidence
to hear from https://github.com/kubernetes-sigs/cluster-api/issues/6285#issuecomment-1070557608

**Comment by maelk** [comment]
Sorry for the delay, I was on PTO. I verified the inputs we got, and actually the node drain timeout was not set. So you are right about the current behaviour.
Our users do not want to set it because Rook is deployed and using timeouts would override some internal control mechanisms. Could we maybe consider splitting the timeouts, or adding another control knob to change the timeout behaviour for the volume part only ?

**Comment by furkatgofurov7** [comment]
@enxebre @vincepri how do you like the idea of having split the timeouts? like having a general drain timeout + volumes timeout, and within that, a timeout specifically for volumes?

**Comment by furkatgofurov7** [comment]
What we were thinking that could be doable is, introduce a new timeout, i.e called `volumeDrainTimeout` specifically for volumes,
and then, whenever we check whether we should wait for volumes we would have a `volumeDrainTimeout` set, so in a case where we have `nodeDrainTimeout` is set to 0 (meaning wait indefinitely and that is the scenario we are dealing with) and we have a volume that can never be detached, we could wait until either `nodeDrainTimeout` **OR** `volumeDrainTimeout` exceeds,  and based on whichever of the two timeouts exceeds first, we could move on with the node deletion, rather than being stuck waiting.

**Comment by enxebre** [comment]
>Our users do not want to set it because Rook is deployed and using timeouts would override some internal control mechanisms.

Can you elaborate on this so we can understand the full picture?
If we consider this a generic valid use case not covered by drainTimeout, then either volumeDrainTimeout or supporting draining daemonsets e.g using taints make sense to me, otherwise this could be a valid use case for a runtime extension hook.

**Comment by furkatgofurov7** [comment]
> then either volumeDrainTimeout or supporting draining daemonsets e.g using taints make sense to me

@enxebre great, thanks! I will try to put a draft PR up soon.

**Comment by maelk** [comment]
Here is our use case with Rook:
In order to preserve the Ceph cluster, Rook needs to control tightly the deprovisioning of the node, since there is a constraints on OSDs going down, if more than one replica of data is missing, the ceph cluster becomes unusable until it is back to max one replica of the data being gone. So to go through the upgrade, it uses PDB to prevent more than x nodes to go offline at once for reprovisioning. It will prevent the draining of any other node as long as the Ceph cluster is not ready to have more OSDs going down. So until the data is rebalanced and there is room to take another OSD down, the drain of the next node will be blocked. 
We do not want to override this mechanism with a drain timeout since it could break our Ceph cluster. However, we have a daemonset that mounts a volume, and currently that blocks the deprovisioning of the node without manual action. If we could set a timeout on that specific part of the deprovisioning without impacting the actual draining, then our problem would be solved.
Do you see another alternative ?

**Comment by fabriziopandini** [comment]
Sorry for getting late to this issue.
I'm not 100% sure I got the difference between forcing deletion due to nodeDrainTimeout expiring or due to a new volumeDrainTimeout, because if I got it right in both cases we are going to delete the node with attached volumes, or am I wrong?

Also, a couple of comments about API changes if we go down this path:
- if we are going to add a new timeout, it should go into ClusterTopology as well
- if I look at the [machine API](https://github.com/kubernetes-sigs/cluster-api/blob/c19d1f429c7dd5060e14a17f57a06164bb969dcc/api/v1beta1/machine_types.go#L94-L104) we are adding timeouts to spec without a proper organization; wondering if we can do a better job at modeling delete options

/cc @yastij @vincepri

**Comment by furkatgofurov7** [comment]
> in both cases we are going to delete the node with attached volumes, or am I wrong?

@fabriziopandini correct. 



> * if we are going to add a new timeout, it should go into ClusterTopology as well

I will look into adding it to #6413 which is on the flight now

 



> similarly, it should go in KCP/CP CRs, but this requires a contract update

First part is covered I believe, would you mind elaborating more on contract update part?

> * f I look at the [machine API](https://github.com/kubernetes-sigs/cluster-api/blob/c19d1f429c7dd5060e14a17f57a06164bb969dcc/api/v1beta1/machine_types.go#L94-L104) we are adding timeouts to spec without a proper organization; wondering if we can do a better job at modeling delete options

:+1:

**Comment by fabriziopandini** [comment]
@furkatgofurov7 if in both cases (existing nodeDrainTimeout and proposed volumeDrainTimeout) we are going to delete the node with attached volumes, why can't we use the existing nodeDrainTimeout?

Also, before proceeding, I would like to hear other opinions about the resulting API

WRT to the API contract the relevant part is documented [here](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/control-plane.html#required-spec-fields-for-implementations-using-machines); Changing this requires community agreement.

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 if in both cases (existing nodeDrainTimeout and proposed volumeDrainTimeout) we are going to delete the node with attached volumes, why can't we use the existing nodeDrainTimeout?

@fabriziopandini what if nodeDrainTimeout is set to default value (0s)? In that [case](https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/machine/machine_controller.go#L427), we reach [this](https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/machine/machine_controller.go#L309) condition where later we would be waiting for volumes to be detached indefinitely in the case of daemon sets. 

> Also, before proceeding, I would like to hear other opinions about the resulting API

:100: Absolutely, sorry I coded out that before and opened a PR today, maybe I should put hold or WIP, in that case?

> WRT to the API contract the relevant part is documented [here](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/control-plane.html#required-spec-fields-for-implementations-using-machines); Changing this requires community agreement.

Thanks, I will wait for others opinion and proceed based on the agreement we reach :+1:

**Comment by fabriziopandini** [comment]
> what if nodeDrainTimeout is set to default value (0s) or not set? ...

If I got this right what we are trying to solve is to delete the node even if there are attached volumes.
looking at the code, it seems to me that this can be achieved already today by setting nodeDrainTimeout to something greater than 0; [when the timeout is reached](https://github.com/kubernetes-sigs/cluster-api/blob/70c9771dbccb2ecd24d3fc36a68d2e39d6ecd165/internal/controllers/machine/machine_controller.go#L436-L439) the controller is going to stop waiting for volumes and the node deletion continues.

**Comment by furkatgofurov7** [comment]
> it seems to me that this can be achieved already today by setting nodeDrainTimeout to something greater than 0

Correct, but as we [discussed](https://github.com/kubernetes-sigs/cluster-api/issues/6285#issuecomment-1087244349) a bit earlier we have a use case where:

> Our users do not want to set it because Rook is deployed and using timeouts would override some internal control mechanisms. 

and more info on Rook deployment, please chech this comment: https://github.com/kubernetes-sigs/cluster-api/issues/6285#issuecomment-1092466360

**Comment by fabriziopandini** [comment]
> Our users do not want to set it because Rook is deployed and using timeouts would override some internal control mechanisms

That's probably the missing bit for me, how the CAPI nodeDrainTimeout can override the Rook internal control mechanis?

**Comment by maelk** [comment]
The issue with a timeout on the drain is that it renders the pdb settings done by Rook inefficient. Let's say we are doing an upgrade on a machineDeployment where Rook is deployed. Rook will set the PDB to allow 1 node to go away so that we keep enough OSDs (disks on the nodes) running to keep the Ceph cluster usable. So the draining of a first node will succeed. However, if a second node is to be drained by CAPI, it should block until the first node is back, and the pdb respected, otherwise the Ceph cluster will be unhealthy because of too many OSDs gone. So we cannot put a drain timeout because it might cause the second node to be deleted, and that would cause too many OSDs to be gone or the wrong OSD to be gone. However, once the first node comes back and the OSDs there are available again and the cluster is healthy again, then the draining will succeed. But in our case, a volume will block the deletion after draining succeeds. 

The result is that we cannot set a drain timeout otherwise we might break the Ceph cluster, but we need a timeout in case one of the volumes does not get deleted, independently of the draining operation.

Does this make our use case clear ?

**Comment by maelk** [comment]
Yes, if the volume was not owned by a daemonset, we would not have the issue. Either direction should be fine for us to solve this issue.

**Comment by enxebre** [comment]
> Yes, if the volume was not owned by a daemonset, we would not have the issue. Either direction should be fine for us to solve this issue.

Ok, so let's discuss evicting daemonSets, volume time out has no meaning with out a daemonSet backing the pod. As suggested above one option would be to use taints similar to what autoscaler does, thoughts? @fabriziopandini @sbueringer  @vincepri @CecileRobertMichon

**Comment by fabriziopandini** [comment]
I agree with @enxebre that it seems we are implementing a knob for a use case that can be solved in other ways.
I don't have preferences on using something different than DemonSet or using Taints, but I wonder if we should document this somewhere in the book

**Comment by enxebre** [comment]
>but I wonder if we should document this somewhere in the book

Today we stick to drain's default behaviour and that prevents daemonSets from being evicted. I created this https://github.com/kubernetes-sigs/cluster-api/pull/6421 to document current state of things.

Now, we should discuss if we want to implement daemonset eviction https://github.com/kubernetes-sigs/cluster-api/issues/6158. If so we need to think how to make it transitionally as this would be an API breaking change for existing behaviour. Alternatively, If there're arguments against supporting evicting daemonSets as core, this could be done via hook implementation.

**Comment by furkatgofurov7** [comment]
@fabriziopandini @sbueringer @vincepri @CecileRobertMichon I would appreciate your opinions on how to move forward with this issue. 

> Today we stick to drain's default behaviour and that prevents daemonSets from being evicted. I created this #6421 to document current state of things.

@enxebre thanks, that is helpful!



> Alternatively, If there're arguments against supporting evicting daemonSets as core, this could be done via hook implementation.

 I am not sure I got the point here, are you referring to introducing a new hook or making use of the existing ones, if the latter, from my understanding, `pre-drain.delete` hook  is too early and `pre-term.delete` hook is too late to help with our use case

**Comment by furkatgofurov7** [comment]
> /priority awaiting-more-evidence
> to hear from [#6285 (comment)](https://github.com/kubernetes-sigs/cluster-api/issues/6285#issuecomment-1070557608)

@enxebre is there anything missing in this issue or we can maybe remove this label?

**Comment by sbueringer** [comment]
How would an implementation that drains DaemonSets look like?

Regarding the variant with drain: is it something like: our machine controller would set a taint and then delete all DaemonSet pods? (the taint would be so the DaemonSet pods are not getting rescheduled).
(I'm not sure if just setting a taint evicts already running Pods from a Node)

Would we just evict all DaemonSet Pods? As far as I'm aware Pod deletion has a dependency on CNI working. Afaik if CNI is gone (i.e. the Calico pod has been drained) the kubelet will fail to delete Pods with an error like "Failed to stop Pod sandbox" (IIRC).


I didn't have the time to read through the upstream issues, but given that they haven't been implemented yet, is anyone aware of concerns that are showstoppers for CAPI?

**Comment by furkatgofurov7** [comment]
> am I right to say that your problem would be automatically solved if the pod having the volume were not owned by a daemon set so it would be naturally evicted as everything else letting the volume go away?

> Yes, if the volume was not owned by a daemonset, we would not have the issue. Either direction should be fine for us to solve this issue.



@enxebre @sbueringer  we have checked this again and confirmed that this problem still exists in a case where we have a deployment pod with a volume attached to it and that pod is **NOT** owned by a DaemonSet, so the above confirmation where we say `there is no issue when we have a volume not owned by a daemonset` is not accurate. 



So, in short, it is not only DaemonSet specific issue but rather a wider one where CAPI waits for volumes to be detached when the volume is attached to any resource (could be DS, deployment pod). 


Here, I am attaching more logs from the cluster where we have seen CAPI blocking the machine deletion (machine stuck in “Deleting” state forever) and hope this helps to better understand the problem.

==================================================================================================

We have a cluster where ceph is used as a storage CSI. Ceph runs on master nodes (3) and container mounting a network-file PVC in RWX mode on a worker using ceph. Once worker BaremetalHost is deleted, the machine starts deleting and gets stuck in the “Deleting” state forever

Below, you can see the YAML definitions of the resources involved in the test case:

Pod YAML:

```
apiVersion: v1
kind: Pod
metadata:
  
  name: test-deployment-pod
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: test-74fb4cb485
    ………………
nodeName: test-node-pool
  volumes:
  - name: registry-data
    persistentVolumeClaim:
      claimName: pvc-test

```

Persistent volume YAML:


```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph.cephfs.csi.ceph.com
  name: pvc-244556666-n332322
spec:
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-test
    namespace: kube-system
  csi:
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
status:
  phase: Bound
```


and PVC YAML attached to the pod:


```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: network-file
  volumeMode: Filesystem
  volumeName: pvc-244556666-n332322
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  phase: Bound
```


Machine stuck in Deleting state:

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: test-machine
  namespace: test-machine-namespace
spec:
……..
status:
  conditions:
  - lastTransitionTime: "2022-05-12T23:32:06Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-05-12T23:31:51Z"
    status: "True"
    type: BootstrapReady
  - lastTransitionTime: "2022-05-13T09:01:54Z"
    status: "True"
    type: DrainingSucceeded
  - lastTransitionTime: "2022-05-12T23:32:06Z"
    status: "True"
    type: InfrastructureReady
  - lastTransitionTime: "2022-05-13T08:35:32Z"
    message: 'Node condition MemoryPressure is Unknown. Node condition DiskPressure
      is Unknown. Node condition PIDPressure is Unknown. Node condition Ready is Unknown. '
    reason: NodeConditionsFailed
    status: Unknown
    type: NodeHealthy
  - lastTransitionTime: "2022-05-13T09:01:24Z"
    status: "True"
    type: PreDrainDeleteHookSucceeded
  - lastTransitionTime: "2022-05-13T09:01:54Z"
    message: Waiting for node volumes to be detached
    reason: WaitingForVolumeDetach
    severity: Info
    status: "False"
    type: VolumeDetachSucceeded
  infrastructureReady: true
  lastUpdated: "2022-05-13T09:01:24Z"
  nodeInfo:
    architecture: amd64
    containerRuntimeVersion: containerd://1.5.7
    kubeProxyVersion: v1.23.3
    kubeletVersion: v1.23.3
  nodeRef:
    apiVersion: v1
    kind: Node
    name: test-node-pool
    uid: 0xxxxx
  phase: Deleting
```

Corresponding Node:

```
apiVersion: v1
kind: Node
metadata:
  name: test-node-pool
spec:
  taints:
  - effect: NoSchedule
    key: node.kubernetes.io/unreachable
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
  unschedulable: true
status:
  conditions:
    message: Calico is running on this node
    reason: CalicoIsUp
    status: "False"
    type: NetworkUnavailable
    message: Kubelet stopped posting node status.
    reason: NodeStatusUnknown
    status: Unknown
    type: MemoryPressure
    message: Kubelet stopped posting node status.
    reason: NodeStatusUnknown
    status: Unknown
    type: DiskPressure
    message: Kubelet stopped posting node status.
    reason: NodeStatusUnknown
    status: Unknown
    type: PIDPressure
    message: Kubelet stopped posting node status.
    reason: NodeStatusUnknown
    status: Unknown
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  
  nodeInfo:
    …..
  volumesAttached:
  - devicePath: ""
    name: kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com-rook-ceph-volume1
  - devicePath: ""
    name: kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com-rook-ceph-volume2
  volumesInUse:
  - kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com-rook-ceph-volume1
- kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com-rook-ceph-volume2

```

CAPI logs while trying to delete the machine:

```
I0513 09:01:54.844912       1 machine_controller.go:311] controller/machine "msg"="Draining node" "cluster"="test-cluster" "name"="test-machine" "namespace"="test-machine-namespace" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" "node"="test-node-pool"
E0513 09:01:55.527274       1 machine_controller.go:800] 
1 machine_controller.go:603] controller/machine "msg"="Drain successful" "cluster"="test-cluster" "name"="test-machine" "namespace"="test-machine-namespace" "node"="test-node-pool" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" 
I0513 09:01:55.527636       1 machine_controller.go:352] controller/machine "msg"="Waiting for node volumes to be detached" "cluster"="test-cluster" "name"="test-machine" "namespace"="test-machine-namespace" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" "node"="test-node-pool"
```
and it keeps throwing the same `Waiting for node volumes to be detached" ` output forever with different timestamps.


However, if the node is deleted manually, the node is gone in this situation and CAPI won’t check for the volume anymore and CAPI proceeds with deletion of the machine as expected:

```
E0513 10:25:53.840191 1 machine_controller.go:558] controller/machine "msg"="Could not find node from noderef, it may have already been deleted" "error"="nodes \"test-node-pool\" not found" "cluster"="test-cluster" "name"="test-machine" "namespace"="test-machine-namespace" "node"="test-node-pool" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine"
E0513 10:25:53.840290 1 machine_controller.go:623] controller/machine "msg"="Could not find node from noderef, it may have already been deleted" "error"="Node \"test-node-pool\" not found" "cluster"="test-cluster" "machine"="test-machine" "name"="test-machine" "namespace"="test-machine-namespace" "node"="test-node-pool" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" 
```

Since this is not only specific to DS (up until now we were thinking it is the case) but it is wider and generic (other resources with volume not only DS), how do you feel/like the idea of introducing a volumeDetachTimeout we had initially and discussing in https://github.com/kubernetes-sigs/cluster-api/issues/6285#issuecomment-1090481942 ?
