### ISSUE TITLE
clusterctl alpha topology plan fails for a working ClusterClass definition

### ISSUE THREAD

**Issue by pydctw** [kubernetes-sigs/cluster-api#6365]
**What steps did you take and what happened:**

A ClusterClass definition that was able to create a cluster fails clusterctl alpha topology plan.

multi-az-clusterclass-v1.yaml (showing only relevant portion for the issue)
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: multi-az-clusterclass-v1
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: multi-az-clusterclass-v1-control-plane
    machineInfrastructure:
      ref:
        kind: AWSMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: multi-az-clusterclass-v1-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AWSClusterTemplate
      name: multi-az-clusterclass-v1
  workers:
    machineDeployments:
    - class: default-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: multi-az-clusterclass-v1-worker-bootstraptemplate
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AWSMachineTemplate
            name: multi-az-clusterclass-v1-worker-machinetemplate
  variables:
  - name: networkSubnets
    required: false
    schema:
      openAPIV3Schema:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            cidrBlock:
              type: string
            availabilityZone:
              type: string
            isPublic:
              type: boolean
            routeTableID:
              type: string
            natGatewayID:
              type: string
            tags:
              type: object
              additionalProperties:
                type: string
  patches:
  - name: networkSubnets
    definitions:
      - selector:
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
          kind: AWSClusterTemplate
          matchResources:
            infrastructureCluster: true
        jsonPatches:
          - op: add
            path: /spec/template/spec/network/subnets
            valueFrom:
              variable: networkSubnets
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSClusterTemplate
metadata:
  name: multi-az-clusterclass-v1
spec:
  template:
    spec: {}
---
...
```

multi-az-cc-cluster.yaml
```
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cni: multi-az-crs-0
  name: "multi-az"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  topology:
    class: multi-az-clusterclass-v1
    version: "v1.23.0"
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
      - class: "default-worker"
        name: "md-0"
        replicas: 1
    variables:
      - name: networkSubnets
        value:
        - availabilityZone: us-west-1a
          cidrBlock: "10.0.0.0/24"
        - availabilityZone: us-west-1a
          cidrBlock: "10.0.1.0/24"
          isPublic: true
        - availabilityZone: us-west-1c
          cidrBlock: "10.0.2.0/24"
        - availabilityZone: us-west-1c
          cidrBlock: "10.0.3.0/24"
          isPublic: true
```

clusterctl alpha topology plan
```
$ clusterctl alpha topology plan -f multi-az-clusterclass-v1.yaml -f multi-az-cc-cluster.yaml -o output
Using configuration File="/Users/wkwon/.cluster-api/clusterctl.yaml"
Detected a cluster with Cluster API installed. Will use it to fetch missing objects.
Error: failed to dry run the topology controller: error computing the desired state of the Cluster topology: failed to apply patches: failed to apply patch to template InfrastructureClusterTemplate infrastructure.cluster.x-k8s.io/v1beta1/AWSClusterTemplate: error applying json patch (RFC6902): [{"op":"add","path":"/spec/template/spec/network/subnets","value":[{"availabilityZone":"us-west-1a","cidrBlock":"10.0.0.0/24"},{"availabilityZone":"us-west-1a","cidrBlock":"10.0.1.0/24","isPublic":true},{"availabilityZone":"us-west-1c","cidrBlock":"10.0.2.0/24"},{"availabilityZone":"us-west-1c","cidrBlock":"10.0.3.0/24","isPublic":true}]}]: add operation does not apply: doc is missing path: "/spec/template/spec/network/subnets": missing value
sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster.(*topologyClient).Plan
	sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster/topology.go:209
sigs.k8s.io/cluster-api/cmd/clusterctl/client.(*clusterctlClient).TopologyPlan
	sigs.k8s.io/cluster-api/cmd/clusterctl/client/topology.go:55
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.runTopologyPlan
	sigs.k8s.io/cluster-api/cmd/clusterctl/cmd/topology_plan.go:126
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.glob..func15
	sigs.k8s.io/cluster-api/cmd/clusterctl/cmd/topology_plan.go:82
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.2.1/command.go:902
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.Execute
	sigs.k8s.io/cluster-api/cmd/clusterctl/cmd/root.go:94
main.main
	sigs.k8s.io/cluster-api/cmd/clusterctl/main.go:26
runtime.main
	runtime/proc.go:255
runtime.goexit
	runtime/asm_amd64.s:1581
```

**What did you expect to happen:**
clusterctl alpha topology plan creates templates successfully without an error.

**Anything else you would like to add:**
Initial discussion in [slack](https://kubernetes.slack.com/archives/C8TSNPY4T/p1648742049896199)

**Environment:**

- Cluster-api version: main branch
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
