### ISSUE TITLE
ClusterClass: support map variables

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6370]
**User Story**

As a user I would like to be able to use map ClusterClass variables.

**Detailed Description**

I think it would be useful if we would be able to define not only basic types, objects and arrays but also map variables.
From a JSON perspective maps are objects where all field values have the same schema.

This can be very useful if folks want to implement lookup behavior. Example:

Variable `mdConfig`:
```yaml
default-worker:
    osImage: ubuntu-18.04
windows-worker:
    osImage: windows-2012
``

Patch:
```yaml
    - selector:
        ...
      jsonPatches:
      - op: add
        path: "/spec/template/spec/customImage"
        valueFrom:
          template: "{{ (index .mdConfig .builtin.machineDeployment.class).osImage }}"
```

Comparison object vs. map:
* object:
    * all field keys must be defined in the schema
    * every field can have a different schema for its value
* map:
    * field keys have to be strings but don't have to be enumerated in the schema
    * all field values of a map have the same schema

/kind feature
/area topology
