### ISSUE TITLE
Cluster API State Metrics implementation

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api#6458]
Follow-up issue to track implementation of the merged proposal 
* #6404

as follow-up to

* #1477

Current state is that the contribution PR needs to be done for https://github.com/mercedes-benz/cluster-api-state-metrics to the `exp/state-metrics` directory which is WIP at the branch https://github.com/mercedes-benz/cluster-api/tree/exp/casm-introduce .

**User Story**
[xref proposal user stories](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20220411-cluster-api-state-metrics.md#user-stories)

**TODOs:**

- [x] Proposal: #6404
- [x] ~~Contribution: #6570~~ not necessary, we can directly use kube-state-metrics and the new CustomResource configuration
- [x] Integrate to tilt https://github.com/kubernetes-sigs/cluster-api/pull/7095
- [x] Implement metrics mentioned in the proposal but missing in the current implementation
    - exception: `_labels` metrics
- [x] Implement `cluster_info` including `.spec.controlPlaneEndpoint.host` as label metric to solve #5510 
    - https://github.com/kubernetes-sigs/cluster-api/pull/7095
- [x] ~~clarify and implement steps for image publishing~~
    - not required because we soon can use upstream kube-state-metrics images
- [x] Create issue to clarify and implement release manifest
- [x] resync the proposal to the current state https://github.com/kubernetes-sigs/cluster-api/pull/7183
- [x] review again the *status_*replica* metrics for consistency purposes #7166

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by chrischdi** [comment]
Looks like the kube-state-metrics project made the implementation obsolete.

> https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.5.0 is now available with a lot of great contributions from the community! It comes with more metrics for standard components and an experimental feature to create your own metrics for CRDs! :tada:  Isn't Friday the perfect opportunity to deploy this to your cluster? :wink:

Source: https://kubernetes.slack.com/archives/CJJ529RUY/p1654257314683059

Looks like we should adapt, check if we could do the same with configuration only and deploying kube-state-metrics instead :-)

**Comment by sbueringer** [comment]
Oh, interesting turn of events. Yeah let's figure out if that covers our use case.

**Comment by bavarianbidi** [comment]
As i currently prepare our internal repositories to make use of `cluster-api-state-metrics` and try to propose a generic description to adopt different infrastructure providers as well i just gave `kube-state-metrics` a short try with following config.

```yaml
kind: CustomResourceStateMetrics
spec: 
  resources: 
    - groupVersionKind: 
        group: cluster.x-k8s.io
        kind: Machine
        version: v1beta1
      metrics: 
        - each: 
            path: 
              - status
              - phase
          help: "machine phase"
          name: phase
```

As `kube-state-metrics` expect a `float` as value (https://github.com/kubernetes/kube-state-metrics/blob/7f09ca71ba25af4d2cbb1637e13b28c1d0028159/pkg/customresourcestate/registry_factory.go#L490-L525) above config will fail with

```
E0607 09:12:00.168168  126676 registry_factory.go:469] "kube_cluster_x-k8s_io_v1beta1_Machine_phase" err="[status,phase]: []: strconv.ParseFloat: parsing \"Runn
ing\": invalid syntax"
```

Tried to circumvent the fact that a float is required with following config where i defined the path to the only numbered value field in the `Machine` via

```yaml
kind: CustomResourceStateMetrics
spec: 
  resources: 
    - groupVersionKind: 
        group: cluster.x-k8s.io
        kind: Machine
        version: v1beta1
      metrics: 
        - each: 
            valueFrom:
              - metadata
              - generation
            path: 
              - status
              - phase
          help: "machine phase"
          name: phase
```

But still get an error:

```
E0607 09:12:00.168234  126676 registry_factory.go:469] "kube_cluster_x-k8s_io_v1beta1_Machine_phase_annotation" err="[status,phase]: [metadata,generation]: expe
cted number but found nil value"
```

It seems to me, that a well scoped metrics server for ClusterAPI (+ infrastructure implementations) still make sense.
