### ISSUE TITLE
CABPK generated Ignition bootstrap data ignores file ownership

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api#6469]
**What steps did you take and what happened:**

If specified:
```
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
spec:
  kubeadmConfigSpec:
    format: ignition
    files:
    - path: /test-file
      owner: nobody:nobody
      content: foo
```

`owner` field from file is neither rejected or used.

**What did you expect to happen:**

Created file `/test-file` using the configuration above to be owner by `nobody:nobody` on provisioned node using Ignition.

**Anything else you would like to add:**

Found while investigating #6403.

**Environment:**

- Cluster-api version: [v1.1.0](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.1.0)

/kind bug
