### ISSUE TITLE
MachinePool does not automatically rollout changes to the bootstrap.configRef

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#6563]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

I changed the bootstrap.configRef in a MachinePool and the MachinePool didn't rollout the change.

**What did you expect to happen:**

I expected the MachinePool to rollout the changes just like the MachineDeployment does.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Some more details:

Initial MachinePool
```yaml
spec:
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfig
          name: k8s-upgrade-and-conformance-uiq8gp-mp-0-config-cgroupfs
          namespace: k8s-upgrade-and-conformance-hf25m6
        dataSecretName: k8s-upgrade-and-conformance-uiq8gp-mp-0-config-cgroupfs
```
I updated `.spec.template.spec.bootstrap.configRef` to `k8s-upgrade-and-conformance-uiq8gp-mp-0-config` and the change was not rolled out.

The cause of this is that the dataSecretName is only set by the MachinePool controller if it is empty. If I remove the dataSecretName from the MachinePool the MachinePool controller picks up the data secret of the new BootstrapConfig and the change is rolled out.

In my opinion we should update the dataSecretName when the bootstrap configref is changed. Maybe even if the ref stays the same and only the dataSecretName in the status of the referenced resource is updated, this would probably be easier to implement as we just have to always propagate the dataSecretName of the referenced BootstrapConfig.

Notes:
* xref: https://kubernetes.slack.com/archives/C8TSNPY4T/p1653424783728609?thread_ts=1653424336.790119&cid=C8TSNPY4T
* This should not affect MachinePool bootstrap token rotation as neither the bootstrap configref nor the dataSecretName is changed in this case.
* This should not affect the case where only the dataSecretName is set and the bootstrap configref is not.

**Environment:**

- Cluster-api version: latest

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
