### ISSUE TITLE
Prefix selector labels of core components

### ISSUE THREAD

**Issue by erwinvaneyk** [kubernetes-sigs/cluster-api#6571]
**User Story**

As an operator I would like to deploy multiple CAPI components in the same namespace for multi-tenancy and organisational reasons.

**Detailed Description**

I am trying to deploy some Cluster API components in a single namespace, because of restrictions organizationally and because I am trying to deploy multiple instances of CAPI in the same cluster. 

This works great except for one issue: the label selectors of the components are overlapping. Among others, this is causing webhooks requests to get routed to incorrect pods. 

Components that have overlapping label selectors:
* core CAPI
* kubeadm control-plane
* kubeadm bootstrap
* CAPD

Each of these components has the default label selector of kubebuilder-generated projects, namely: `control-plane: controller-manager`. Other providers do prefix the labels nicely. For instance, CAPA uses the following label: `control-plane: capa-controller-manager`

We could choose to prefix the `control-plane` label in the components in this repository as follows:
* CAPI: capi-controller-manager
* CACPK: cacpk-controller-manager
* CABPK: cabpk-controller-manager
* CAPD: capd-controller-manager

**Anything else you would like to add:**

* This could also be a bug report, since I am not sure if the choice for the default labels is intentional or not.
* If we decide to prefix this would require a migration note, since kubernetes does not allow updating of label selectors in Deployments.

/kind feature

**Comment by sbueringer** [comment]
What exactly are the restrictions on Deployments, we can't change them at all?

**Comment by sbueringer** [comment]
Unfortunately that only helps when the upgrade is done with clusterctl. Everyone who tries to run CAPI in a GitOps mode will have that problem.

**Comment by fabriziopandini** [comment]
/triage accepted
/help
/remove lifecycle-stale

I think we should take a look at label selectors for ensuring that deploying all CAPI components in a single namespace works, but support for deploying multiple instances of CAPI in the same cluster is out of scope

**Comment by sbueringer** [comment]
I'm not sure I understand the problem:

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: bootstrap-kubeadm
  name: capi-kubeadm-bootstrap-webhook-service
  namespace: capi-kubeadm-bootstrap-system
spec:
...
  selector:
    cluster.x-k8s.io/provider: bootstrap-kubeadm
```


```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cluster.x-k8s.io/provider: bootstrap-kubeadm
    control-plane: controller-manager
  name: capi-kubeadm-bootstrap-controller-manager
  namespace: capi-kubeadm-bootstrap-system
spec:
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: bootstrap-kubeadm
      control-plane: controller-manager
```

I understand that you would run into a problem if you deploy multiple-instances of the same provider, but multiple different providers in the same namespace should work I guess (?)
