### ISSUE TITLE
clusterctl get kubeconfig results in faulty kubeconfig file after switching to Docker Desktop

### ISSUE THREAD

**Issue by RobinDeBock** [kubernetes-sigs/cluster-api#6595]
**What steps did you take and what happened:**
- Removed docker from system
- Clean install of Docker Desktop
- Created a bootstap cluster with Kind
- Created a workload cluster with `clusterctl init`
- Used `clusterctl get kubeconfig` on the newly created workload cluster
- Using this kubeconfig file to connect to the cluster results in  
`The connection to the server localhost:8080 was refused - did you specify the right host or port?`

**What did you expect to happen:**
That using clusterctl get kubeconfig results in a working kubeconfig file.

**Anything else you would like to add:**
- `clusterctl get kubeconfig` worked correctly before switching to Docker Desktop.
- Using `kind get kubeconfig` still works.
<details>
  <summary>kind-kubeconfig.yaml (Click to expand)</summary>
 
```yaml 

```
</details>

- Using `clusterctl get kubeconfig`results in mostly the same kubeconfig file, except from the IP address.
<details>
  <summary>clusterctl-kubeconfig.yaml (Click to expand)</summary>
 
```yaml 

```
</details>
- In the period of me using setting up the cluster (using `clusterctl get kubeconfig`) and switching to Docker Desktop, an update has been available to clusterctl. I have not installed this one yet and would like to stay on this version if possible.

**Environment:**

- Cluster-api version: `GitVersion:"v1.1.3"`
- Minikube/KIND version: `v0.12.0 go1.17.8 linux/amd64`
- Kubernetes version: (use `kubectl version`):
  - Client: `GitVersion:"v1.22.3" `
  - Server, both Kind cluster and workload cluster have version `v1.22.7`
- OS (e.g. from `/etc/os-release`): `Ubuntu 20.04.4 LTS`
- Docker Desktop: `20.10.16`

/kind bug
/area provider/docker
/area networking
/area clusterctl

**Comment by sbueringer** [comment]
If I understood correctly you got
```
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

when using `clusterctl-kubeconfig.yaml` ?


Then there is something wrong with the kubectl call. Otherwise it would use `https://172.18.0.3:6443` and not the default server URL.

**Comment by RobinDeBock** [comment]
Hey @sbueringer

I'm going to switch back to Docker on the CLI as Docker Desktop uses a VM which impacts performance, so the time to test this setup will be limited.

To come back to your questions:
> Is the cluster entirely reconciled?
The cluster is fully operational. As described before, this is the exact same cluster that I was using before. The **only** difference is that the IP address in the kubeconfig file resulting from `clusterctl get kubeconfig` is different from the one from `kind get kubeconfig` and the first one can't be used ot communicate with the cluster. Everything else is working fine.

> What does clusterctl describe cluster show?

<details>
  <summary>clusterctl describe cluster result (Click to expand)</summary>
 
```yaml 
Name:         master-cluster
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  cluster.x-k8s.io/v1beta1
Kind:         Cluster
Metadata:
  Creation Timestamp:  2022-06-07T17:44:02Z
  Finalizers:
    cluster.cluster.x-k8s.io
  Generation:  2
  Managed Fields:
    API Version:  cluster.x-k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:controlPlaneReady:
        f:infrastructureReady:
        f:observedGeneration:
        f:phase:
    Manager:      manager
    Operation:    Update
    Subresource:  status
    Time:         2022-06-07T17:42:56Z
    API Version:  cluster.x-k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:finalizers:
          .:
          v:"cluster.cluster.x-k8s.io":
      f:spec:
        .:
        f:clusterNetwork:
          .:
          f:pods:
            .:
            f:cidrBlocks:
          f:serviceDomain:
          f:services:
            .:
            f:cidrBlocks:
        f:controlPlaneEndpoint:
          .:
          f:host:
          f:port:
        f:controlPlaneRef:
          .:
          f:apiVersion:
          f:kind:
          f:name:
          f:namespace:
        f:infrastructureRef:
          .:
          f:apiVersion:
          f:kind:
          f:name:
          f:namespace:
        f:paused:
    Manager:         clusterctl
    Operation:       Update
    Time:            2022-06-07T17:44:02Z
  Resource Version:  1442
  UID:               73e25d98-7f39-48a7-a8be-5d763aaffa8c
Spec:
  Cluster Network:
    Pods:
      Cidr Blocks:
        192.168.0.0/16
    Service Domain:  cluster.local
    Services:
      Cidr Blocks:
        10.128.0.0/12
  Control Plane Endpoint:
    Host:  172.18.0.3
    Port:  6443
  Control Plane Ref:
    API Version:  controlplane.cluster.x-k8s.io/v1beta1
    Kind:         KubeadmControlPlane
    Name:         master-cluster-control-plane
    Namespace:    default
  Infrastructure Ref:
    API Version:  infrastructure.cluster.x-k8s.io/v1beta1
    Kind:         DockerCluster
    Name:         master-cluster
    Namespace:    default
Status:
  Conditions:
    Last Transition Time:  2022-06-07T17:44:19Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-06-07T17:44:19Z
    Status:                True
    Type:                  ControlPlaneInitialized
    Last Transition Time:  2022-06-07T17:44:19Z
    Status:                True
    Type:                  ControlPlaneReady
    Last Transition Time:  2022-06-07T17:44:15Z
    Status:                True
    Type:                  InfrastructureReady
  Control Plane Ready:     true
  Infrastructure Ready:    true
  Observed Generation:     2
  Phase:                   Provisioned
Events:                    <none>
```
</details>

> Any recurring errors in controller logs?
No errors found as the whole clusters seems to be running fine.

Somehow switching to Docker Desktop messed up the networking, but only when using the kubeconfig files from `clusterctl get kubeconfig`
