### ISSUE TITLE
Break out controlPlane version into individual component versions

### ISSUE THREAD

**Issue by karan** [kubernetes-sigs/cluster-api#69]
As proposed in https://docs.google.com/document/d/1-sYb3EdkRga49nULH1kSwuQFf1o6GvAw_POrsNo5d8c/edit#, change [`ControlPlane and Kubelet`](https://github.com/kubernetes/kube-deploy/blob/master/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go#L140-L147) version spec to this:

```
    componentVersions:
       apiserver: 1.8.3
       controller-manager: 1.8.3
       scheduler: 1.8.3
       kubelet: 1.8.3
       apiStorage:
         name: etcd
         version: 3.2.18
```

For most users breaking up the versions is inconsequential. But there's edge cases where some have their own forks with private patches where they'd like control over individual components.

Here's a bit more context on this from a recent meeting (first bullet) - https://docs.google.com/document/d/16ils69KImmE94RlmzjWDrkmFZysgB2J4lGnYMRN89WM/edit#heading=h.sxts13qhj5fd
