### ISSUE TITLE
Improve ClusterAPI upgrade workflow with ClusterClass

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7212]
**User Story**

As a user I would like to have a smooth Cluster API upgrade process with ClusterClass-based clusters.

### Current state

*Note*: The following is only relevant if the Cluster API upgrade contains apiVersion bumps of control plane / bootstrap / infra provider CRDs.

ClusterClass inline patches are coupled to a specific template apiVersion. However, the Cluster topology controller always uses the latest apiVersion during reconciliation. When a template apiVersion is bumped the pre-existing inline patches won't be applied anymore.

In the following example the ClusterClass has been written for CAPD v1beta1. If now the CAPD CRDs are bumped to v1beta2 the patches won't apply anymore as the topology controller is using v1beta2 automatically. This will trigger a rollout of the Cluster without the patches.
```yaml
kind: ClusterClass
[...]
infrastructure:
  ref:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerMachineTemplate
    name: quick-start-docker-worker-machinetemplate
   namespace: default
- apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
  kind: DockerMachineTemplate
  matchResources:
    controlPlane: true
---
kind: CustomResourceDefinition
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    cluster.x-k8s.io/v1beta1: v1beta1_v1beta2
  name: dockermachinetemplates.infrastructure.cluster.x-k8s.io
```

The only workaround as of today is to pause all Clusters before the Cluster API upgrade, then upgrade all ClusterClasses to the new apiVersion and then unpause all Clusters. The goal of this issue is to decouple the ClusterAPI upgrade from upgrading the ClusterClass to use the new apiVersion.

### Proposal: Cluster topology controller should use apiVersions from the ClusterClass

The topology controller would use the exact apiVersions specified in the ClusterClass and not the latest available.

The update workflow then looks like this: (example with CAPD v1beta1=>v1beta2)
* ClusterAPI and ClusterClass-based clusters are deployed
* ClusterAPI is upgraded
* Cluster topology reconciliation still works
  * The reconciler still uses CAPD v1beta1 objects to reconcile the cluster
* ClusterClass is upgraded to use CAPD v1beta2 types
  * The template refs and the patches are upgraded at the same time to v1beta2
  * This step doesn't have to be done directly after the upgrade, but eventually before v1beta1 is dropped

Tasks:
* [ ] Additionally we should drop the automatic apiVersion bump in the ClusterClass controller. As of today the bump doesn't work anyway as the request to bump the apiVersion in the template ref fails, because then the selectors don't match anymore.
* [ ] Adjust Cluster topology controller to read templates from ClusterClass and current objects from the managed topology via the version specified in the ClusterClass
* [ ] Let's consider adding a condition to the ClusterClass which surfaces if a ClusterClass is using not the latest apiVersions.

/kind feature
