### ISSUE TITLE
ClusterClass improve inline patch selector validation

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#7213]
**User Story**

As a user I would like to get validation errors if parts of my selector don't match anything.

**Detailed Description**

As of today we have validation in our ClusterClass webhook which validates that a selector matches at least one template in a ClusterClass. As selectors can be configured to match multiple templates at the same time this is not enough.

**Anything else you would like to add:**

Proposal:

> There has to be a matching resource (same apiVersion+kind) for every matchResource configured (control plane, infrastructure cluster, each individual MD class). It's not good enough if just the entire selector matches something.

Example:
```yaml
  patches:
  - name: config
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        matchResources:
          controlPlane: true
          machineDeploymentClass:
          - names:
            - default-worker
```

Our current validation would succeed if apiVersion+kind matches at least one of control plane or MD class default-worker.

With the stricter validation the selector has to match both the control plane and MD class default-worker.

This way we make sure that every single part of the selector is "used" and not unintentionally doesn't match anything.

/kind feature
