### ISSUE TITLE
MachineDeployment.spec.replicas defaulting should take into account autoscaler min/max size if defined

### ISSUE THREAD

**Issue by zhouke1991** [kubernetes-sigs/cluster-api#7293]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Kubernetes version v1.23.8
cluster-api version v1.1.5
capa version v1.2.0
cluster-autoscaler v1.20.0

I deployed an autoscaler deployment against a workload cluster in the mgmt cluster. When I apply a large requests pod in the workload cluster and the pod is in a pending status. In this scenario, the autoscaler will work. I found the replicas of MachineSet change to 2 but the count of ready is always 1. I also check the description of MachineSet, and the MachineSet controller repeatedly created and deleted the machine.

**What did you expect to happen:**
I found a workaround in this [https://github.com/kubernetes-sigs/cluster-api/issues/5442#issuecomment-1190713981](link). He told us just unset the replicas of machineDeployments. But if I unset the replicas, it will use the default value replicas=1. I want to not only setup a cluster with replicas=3 but also make the autoscaler can work. How can I do it?

The cluster YAML like this:
```
spec: 
   topology
      workers:
          machineDeployments:
          - class: my-worker
            failureDomain: us-west-2a
            name: md-0
            replicas: 3
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The action of machineset controller
![21664256338_ pic](https://user-images.githubusercontent.com/18651198/192501082-b8081903-8139-45e7-96f6-8c39a28066d9.jpg)
