### ISSUE TITLE
ClusterClass: Old VSphereMachineTemplate get patched before new one is created

### ISSUE THREAD

**Issue by farodin91** [kubernetes-sigs/cluster-api#7386]
**What steps did you take and what happened:**

1. (Adopt cluster by ClusterClass)
2. Upgrade kubeversion
3. clusterclass tried to patch old VSphereMachineTemplate of the controlplane
4. relaxed VSphereMachineTemplate validation
5. clusterclass patched old VSphereMachineTemplates of the controlplane
6. clusterclass created new VSphereMachineTemplates of the controlplane
7. controlplane upgrade went through.
8. MachineDeployment upgrade went through without any problem (VSphereMachineTemplate validation wasn't reactivated yet)

**What did you expect to happen:**
I didn't expect to relax the VSphereMachineTemplate validation. (Error was immutable spec.)

**Anything else you would like to add:**
https://kubernetes.slack.com/archives/C8TSNPY4T/p1665141098457919

clusterclass.yaml
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: "vsphere-class"
  namespace: default
spec:
  controlPlane:
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VSphereMachineTemplate
        name: vsphere-class-template
        namespace: default
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: vsphere-class-controlplane
      namespace: default
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: VSphereClusterTemplate
      name: 'vsphere-class'
      namespace: default
  patches:
  - definitions:
    - jsonPatches:
      - op: replace
        path: /spec/template/spec/template
        valueFrom:
          template: "{{ index .vsphereTemplates .builtin.controlPlane.version }}"
      selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VSphereMachineTemplate
        matchResources:
          controlPlane: true
    - jsonPatches:
      - op: replace
        path: /spec/template/spec/template
        valueFrom:
          template: "{{ index .vsphereTemplates .builtin.machineDeployment.version }}"
      selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VSphereMachineTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - vsphere-class-worker
    name: networkNameControlPlane
  variables:
  - name: vsphereTemplates
    required: true
    schema:
      openAPIV3Schema:
        type: object
        additionalProperties:
          # Schema of the map values.
          type: string
  workers:
    machineDeployments:
    - class: vsphere-class-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: vsphere-class-worker-bootstrap-template
            namespace: default
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: VSphereMachineTemplate
            name: vsphere-class-worker-machinetemplate
            namespace: default
        metadata: {}
```

template.yaml
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: vsphere-class-template
  namespace: "{{ .Release.Namespace }}"
spec:
  template:
    spec:
      template: "template"
      ...
```

cluster.yaml
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: cluster-name
    topology.cluster.x-k8s.io/owned: ''
  name: cluster-name
  namespace: cluster-name
spec:
  controlPlaneEndpoint:
    host: x
    port: 6443
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: cluster-name-cp
    namespace: cluster-name
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: VSphereCluster
    name: cluster-name
    namespace: cluster-name
  topology:
    class: vsphere-class
    controlPlane:
      metadata: {}
      replicas: 3
    variables:
      - name: vsphereTemplates
        value:
          v1.23.6: /DC/vm/path/ubuntu-2004-kube-v1.23.6-93a07762f
          v1.24.4: /DC/vm/path/ubuntu-2004-kube-v1.24.4-98432d802
    version: v1.24.4
    workers:
      machineDeployments:
        - class: vsphere-class-worker
          metadata: {}
          name: md-0
          replicas: 5
```

**Environment:**

- Cluster-api version: 1.2.2
- minikube/kind version:
- Kubernetes version: (use `kubectl version`): 1.24.4
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
