### ISSUE TITLE
CrashLoopBackOff executing provider following book instructions

### ISSUE THREAD

**Issue by pablochacin** [kubernetes-sigs/cluster-api#742]
/kind bug

When developing a cluster-api provider [according to the instructions in the cluster-api book](https://kubernetes-sigs.github.io/cluster-api/provider_implementations/overview.html), the pod for the manager enters in a `CrashLoopBackOff` status with the following error:
```
kubectl logs cluster-api-provider-solas-controller-manager-0 --namespace cluster-api-provider-solas-system -c manager
flag provided but not defined: -metrics-addr
Usage of /manager:
  -kubeconfig string
    	Paths to a kubeconfig. Only required if out-of-cluster.
  -master string
    	The address of the Kubernetes API server. Overrides any value in kubeconfig. Only required if out-of-cluster.
```

Comparing [the code provided in the book](https://kubernetes-sigs.github.io/cluster-api/provider_implementations/register_schemes.html) for  `cmd/manager/main.go` with he code automatically generated by kubebuilder (see [this example](https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/project/cmd/manager/main.go)) we found that the definition for the `metrics-addr` is missing:
```
var metricsAddr string
 flag.StringVar(&metricsAddr, "metrics-addr", ":8080", "The address the metric endpoint binds to.")
```
This is problematic because the manifest for the provider's pod passes this argument:
```
  - args:
    - --metrics-addr=127.0.0.1:8080
    command:
    - /manager
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: SECRET_NAME
      value: cluster-api-provider-solas-webhook-server-secret
    image: cluster-api-provider-solas
    imagePullPolicy: IfNotPresent
    name: manager
``` 

The addition of this argument can be traced to the patch at `config/default/manager_auth_proxy_patch.yaml` applied during customization:
```
      - name: manager 
        args:
        - "--metrics-addr=127.0.0.1:8080"
``` 
This patch is referenced in `config/default/kustomization.yaml' 
```
 # Comment the following 3 lines if you want to disable
  # the auth proxy (https://github.com/brancz/kube-rbac-proxy)
  # which protects your /metrics endpoint.
- ../rbac/auth_proxy_service.yaml
- ../rbac/auth_proxy_role.yaml
- ../rbac/auth_proxy_role_binding.yaml
```
**Environment:**

* kubebuilder 1.0.8
* Cluster-api version: 0.0.0-alpha.4
* Kubernetes version: (use `kubectl version`): v1.13.2
* OS (e.g. from `/etc/os-release`): OpenSUSE Leap 15.0
