### ISSUE TITLE
ClusterClass-enabled clusters get stuck on version change

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api#7428]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

If you change the `spec.topology.version` value on a ClusterClass-enabled Cluster resource to a version that doesn't exist, or isn't supported for any reason (e.g., corresponding machine image doesn't exit), your kubeadmcontrolplane will get stuck in a permanent failure loop like this:

```
  status:
    conditions:
    - lastTransitionTime: "2022-10-17T21:51:49Z"
      message: Rolling 3 replicas with outdated spec (1 replicas up to date)
      reason: RollingUpdateInProgress
      severity: Warning
      status: "False"
      type: Ready
```

The problem from a UX perspective is that there appears to be no way to address this situation using the original configuration vector that got you into this mess (`spec.topology.version` on the Cluster). For eample this is what happens when you either undo the change, or update the `version` to a known-existent version:

```
- lastTransitionTime: "2022-10-18T16:06:13Z"
  message: Control plane upgrade to v1.25.2 on hold. Control plane is upgrading
   to version v1.24.7
```

**What did you expect to happen:**

I would expect that 2nd update to `spec.topology.version` to idempotently reconcile. It's surprising that the previous stuck state transition blocks any future configuration changes.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- minikube/kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
