### ISSUE TITLE
Consider the PlatformKustomization when generating the JSONPatch in GenerateCIArtifactsInjectedTemplateForDebian

### ISSUE THREAD

**Issue by lentzi90** [kubernetes-sigs/cluster-api#7457]
**User Story**

As a [developer/user/operator] I would like to [high level description] for [reasons]

As a infrastructure provider developer I would like to inject my own `preKubeadmCommands` for when using CI artifacts.

**Detailed Description**

[GenerateCIArtifactsInjectedTemplateForDebian](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/framework/kubernetesversions/template.go#L71) is a nice way to patch a clusterctl template in order to get the latest CI artifacts when running e2e tests. It takes a source template, a platform-specific patch and creates a kustomize overlay that merges this together with a patch for the CI artifacts.
It is clever enough to avoid overwriting any `files` or `preKubeadmCommands` in the source template, as can be seen here: https://github.com/kubernetes-sigs/cluster-api/blob/1bf70d5c24004977844b9da7570853c32e29c6b3/test/framework/kubernetesversions/template.go#L175-L186
However, it does *not* check the platform patch. This means that it will overwrite the platform patch IF the following is true:

1. The source template has no `preKubeadmCommands` and/or no `files`
2. The platform patch *has* `preKubeadmCommands` and/or `files` (matching what is missing in the source template)

In my case there is a source template without `preKubeadmCommands` and I would like to use a platform patch to add some platform specific commands when using CI artifacts. Unfortunately, `GenerateCIArtifactsInjectedTemplateForDebian` overwrites them.

Here is a minimal example of how the templates/kustomizations looks like.

Source template
```yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
spec:
  template:
    spec:
      files:
      - content: ${CLOUD_PROVIDER_CONF_B64}
        encoding: base64
        owner: root
        path: /etc/kubernetes/cloud.conf
        permissions: "0600"
...
```

Platform patch
```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane
spec:
  version: ${KUBERNETES_VERSION}
  kubeadmConfigSpec:
    files:
    - content: |
        #!/bin/bash
        # Download and import the locally built controller image
        ...
      owner: root:root
      path: /usr/local/bin/ci-artifacts-platform.sh
      permissions: "0750"
    preKubeadmCommands:
    - /usr/local/bin/ci-artifacts-platform.sh
```

CI artifacts patch generated
```yaml
- op: add
  path: /spec/template/spec/files/-
  value:
    content: |
      #!/bin/bash
      ...
    owner: root:root
    path: /usr/local/bin/ci-artifacts.sh
    permissions: "0750"
# Note this! It will clear the preKubeadmCommands.
# The same was not added for the files above since the source template already had files.
- op: add
  path: /spec/template/spec/preKubeadmCommands
  value: []
- op: add
  path: /spec/template/spec/preKubeadmCommands/-
  value: /usr/local/bin/ci-artifacts.sh
```

The resulting manifests
```yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
  namespace: default
spec:
  template:
    spec:
      files:
      - content: |
          #!/bin/bash
          # Download and import the locally built controller image
          ...
        owner: root:root
        path: /usr/local/bin/ci-artifacts-platform.sh
        permissions: "0750"
      - content: |
          #!/bin/bash
          ...
        owner: root:root
        path: /usr/local/bin/ci-artifacts.sh
        permissions: "0750"
      preKubeadmCommands:
      - /usr/local/bin/ci-artifacts.sh
```
Note how the two files are correctly present, but the `preKubeadmCommands` has only one command (the other was overwritten).

**Anything else you would like to add:**

I would suggest solving this by adding or extending so that also the platform patch is checked.
https://github.com/kubernetes-sigs/cluster-api/blob/1bf70d5c24004977844b9da7570853c32e29c6b3/test/framework/kubernetesversions/template.go#L152-L155

/kind feature

**Comment by fabriziopandini** [comment]
/triage accepted
I'm generally ok with avoiding to override the platform patch if it already exists, but before implementing the change it I would like to hear opinions from people using this in providers
cc @yastij @CecileRobertMichon

**Comment by lentzi90** [comment]
After some more trial and error and hacking I have some more observations.

In some cases the order of the `preKubeadmCommands` can be important. I tried to add a script for pre-pulling a container image, only to realize that it must be run *after* the CI artifacts injection, since that ensures the proper version of containerd and `ctr`. As far as I can tell, there is no way to add a command after it though, because it is always [added at the end](https://github.com/kubernetes-sigs/cluster-api/blob/2a1d191c2c5082d0f9a877cda3aba70d17757553/test/framework/kubernetesversions/template.go#L184).

This got me thinking about alternatives. One would be to add a way to inject additional container images to pull [in the script](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/framework/kubernetesversions/data/debian_injection_script.envsubst.sh.tpl#L110). Something like this perhaps?

```bash
for i in "${!ADDITIONAL_CONTAINERS[@]}"; do
  echo "downloading container: ${ADDITIONAL_CONTAINERS[$i]}"
  wget -O "container-$i" "${ADDITIONAL_CONTAINERS[$i]}"
  echo "Importing container-$i"
  sudo ctr -n k8s.io images import "container-$i"
done
```

It would be interesting to know if others would find something like this useful also.

**Comment by CecileRobertMichon** [comment]
> As a infrastructure provider developer I would like to inject my own preKubeadmCommands for when using CI artifacts.

I'm +1 on this idea in general as we also need this for CAPZ (and it's in fact the reason we haven't been using `GenerateCIArtifactsInjectedTemplateForDebian` so far. Maintaining the different templates for a combination of features + CI vs. not CI is very costly and can be quite confusing to newcomers. 

Taking this even further, one idea I've been playing with but haven't had time to try and implement yet is taking this out of the e2e framework and making this directly part of the kubeadm webhook behind a feature flag. That way we would just use regular templates and kubeadm would inject the script directly when a CI version is specified. This would allow using clusterctl, tilt and every other tool consistently for testing and developing with clusters built with an unreleased k8s version. Just an idea.

**Comment by sbueringer** [comment]
@lentzi90 Can you try what happens if you drop the code to insert the empty arrays? I just recently saw some effect which might mean that the addition works regardless of adding the empty array or not.

In case that doesn't work, I'm fine to check if the strategic merge patch in PlatformKustomization contains those paths or not, if we find a good way to do it.

But overall (especially considering the ordering constraints) I wonder if we should just re-design the whole thing.

**Comment by lentzi90** [comment]
Alright I have done some testing. At first it looked like it could work without adding the array actually, but then I realized this was because my own strategic merge was adding the array anyway. :facepalm: If my patch did not add the array and it was not there in the source, then I got this error:
```
Error: add operation does not apply: doc is missing path: "/spec/template/spec/preKubeadmCommands/-": missing value
```

But this highlights another issue also: the platform-specific patch is applied as a `patchesStrategicMerge`, which indeed adds missing arrays, but also completely replaces existing arrays. :disappointed: 
This is arguably harder to fix. Changing it to a json patch is not reasonable since the provider would need to be able to control what to apply it on, and this is done in the [kustomization.yaml](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/framework/kubernetesversions/data/kustomization.yaml) that lives in the CAPI framework. The only solution I could come up with is to make it an overlay instead. This way the provider has full control over what kind of patches to add and can decide if json or strategic merge is used (or actually do anything they want that kustomize supports).

**Summary:**

1. Inserting empty arrays *is necessary* when using `patchesJson6902`, and if this is done on an existing array it will be replaced.
2. `patchesStrategicMerge` (used for platform-specific patch) overwrites arrays completely, so if both the source template and the platform patch has a `files` array, only the files from the platform patch will be in the rendered manifest.

---

Here is the kustomization used to test it:

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ci-artifacts-source-template.yaml
patchesStrategicMerge:
- platform-kustomization.yaml
patchesJson6902:
- path: kubeadmconfigtemplate-patch.yaml
  target:
    group: bootstrap.cluster.x-k8s.io
    kind: KubeadmConfigTemplate
    name: ".*-md-0"
    version: v1beta1
```

```yaml
# ci-artifacts-source-template.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
spec:
  template:
    spec:
      files:
      - content: ${CLOUD_PROVIDER_CONF_B64}
        encoding: base64
        owner: root
        path: /etc/kubernetes/cloud.conf
        permissions: "0600"
```

```yaml
# platform-kustomization.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
spec:
  template:
    spec:
      files:
      - content: |
          #!/bin/bash
          # Download and import the locally built controller image
          ...
        owner: root:root
        path: /usr/local/bin/ci-artifacts-platform.sh
        permissions: "0750"
        # Note: If these lines are added, they will add the array and make things work.
        # preKubeadmCommands:
        # - /usr/local/bin/ci-artifacts-platform.sh
```

```yaml
# kubeadmconfigtemplate-patch.yaml
- op: add
  path: /spec/template/spec/files/-
  value:
    content: |
      #!/bin/bash
      ...
    owner: root:root
    path: /usr/local/bin/ci-artifacts.sh
    permissions: "0750"
- op: add
  path: /spec/template/spec/preKubeadmCommands/-
  value: /usr/local/bin/ci-artifacts.sh
```
