### ISSUE TITLE
MachinePool stuck deleting if cluster already removed

### ISSUE THREAD

**Issue by AverageMarcus** [kubernetes-sigs/cluster-api#7559]
**What steps did you take and what happened:**

When deleting a cluster (CAPA in my case) I get into a situation where the cluster is completely cleaned up by CAPA before the capi-controller has managed to remove the `MachinePool` CR. By the time it tries to, there's no infra left anymore and the kubeconfig secret has been deleted. 
This is blocking the deletion of the `MachinePool` CR because one of the steps in the `reconcileDelete` process is to [delete nodes from within the cluster](https://github.com/kubernetes-sigs/cluster-api/blob/cfdc9cdf4463c5328780d2d27c0838d9d4a16ccb/exp/internal/controllers/machinepool_controller.go#L233).

This is impossible to do as the cluster no longer exists so the function errors and isn't able to complete the deletion (remove the finalizer). This in turn blocks the deletion of the `Cluster` resource and we're left with just the `Cluster` and `MachinePool` CRs leftover in a permanent deleting phase.

The error reported by capi-controller:
```
capi-controller-manager-785b7666d-d4rc9 manager E1117 14:07:02.211439       1 controller.go:326] "Reconciler error" err="failed to retrieve kubeconfig secret for Cluster org-giantswarm/marc2: secrets \"marc2-kubeconfig\" not found" controller="machinepool" controllerGroup="cluster.x-k8s.io" controllerKind="MachinePool" machinePool="org-giantswarm/marc2-machine-pool0" namespace="org-giantswarm" name="marc2-machine-pool0" reconcileID=52dcac4c-bd2a-4acc-9df0-56d117d6ac9f
```

**What did you expect to happen:**

The finalizer should be removed from the `MachinePool` resource to allow deletion to complete.

**Anything else you would like to add:**

I'm happy opening a PR to update the logic to allow for the delete to complete in the instance that the kubeconfig no longer exists.

**Environment:**

- Cluster-api version: v1.2.4 (but code is the same in latest release)
- minikube/kind version:
- Kubernetes version: (use `kubectl version`): v1.23
- OS (e.g. from `/etc/os-release`):

/kind bug
/area machine

---

**Example manifests:**

Before delete:

<details>
<summary>Cluster</summary>

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    cluster.giantswarm.io/description: marcus's test cluster
    network-topology.giantswarm.io/mode: GiantSwarmManaged
  finalizers:
  - cluster.cluster.x-k8s.io
  - network-topology.finalizers.giantswarm.io
  labels:
    cluster.x-k8s.io/cluster-name: marc1
    cluster.x-k8s.io/watch-filter: capi
  name: marc1
  namespace: org-giantswarm
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 100.64.0.0/12
  controlPlaneEndpoint:
    host: ""
    port: 0
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: marc1
    namespace: org-giantswarm
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSCluster
    name: marc1
    namespace: org-giantswarm
status:
  conditions:
  - lastTransitionTime: "2022-11-18T07:13:50Z"
    message: Scaling up control plane to 3 replicas (actual 0)
    reason: ScalingUp
    severity: Warning
    status: "False"
    type: Ready
  - lastTransitionTime: "2022-11-18T07:13:50Z"
    message: Waiting for control plane provider to indicate the control plane has
      been initialized
    reason: WaitingForControlPlaneProviderInitialized
    severity: Info
    status: "False"
    type: ControlPlaneInitialized
  - lastTransitionTime: "2022-11-18T07:13:50Z"
    message: Scaling up control plane to 3 replicas (actual 0)
    reason: ScalingUp
    severity: Warning
    status: "False"
    type: ControlPlaneReady
  - lastTransitionTime: "2022-11-18T07:13:55Z"
    message: 3 of 7 completed
    reason: NatGatewaysCreationStarted
    severity: Info
    status: "False"
    type: InfrastructureReady
  - lastTransitionTime: "2022-11-18T07:13:57Z"
    status: "True"
    type: NetworkTopologyReady
  controlPlaneReady: false
  infrastructureReady: false
  observedGeneration: 1
  phase: Provisioning

```

</details>

<details>
<summary>MachinePool</summary>

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  annotations:
    machine-pool.giantswarm.io/name: marc1-machine-pool0
  creationTimestamp: "2022-11-18T07:13:50Z"
  finalizers:
  - machinepool.cluster.x-k8s.io
  labels:
    cluster.x-k8s.io/cluster-name: marc1
    cluster.x-k8s.io/watch-filter: capi
    giantswarm.io/machine-pool: marc1-machine-pool0
  name: marc1-machine-pool0
  namespace: org-giantswarm
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    kind: Cluster
    name: marc1
    uid: d13e583e-1713-419d-9b26-25ad0be2e8a3
spec:
  clusterName: marc1
  minReadySeconds: 0
  providerIDList:
  - aws:///eu-west-2a/i-03cXXXXX9cc8247c5
  - aws:///eu-west-2c/i-0acXXXXbe35df2213
  - aws:///eu-west-2b/i-0f6982XXXX04b7ab8
  replicas: 3
  template:
    metadata: {}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfig
          name: marc1-machine-pool0
          namespace: org-giantswarm
        dataSecretName: marc1-machine-pool0
      clusterName: marc1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachinePool
        name: marc1-machine-pool0
        namespace: org-giantswarm
      version: v1.23.13
status:
  availableReplicas: 3
  bootstrapReady: true
  conditions:
  - lastTransitionTime: "2022-11-18T07:22:58Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-11-18T07:19:52Z"
    status: "True"
    type: BootstrapReady
  - lastTransitionTime: "2022-11-18T07:19:54Z"
    status: "True"
    type: InfrastructureReady
  - lastTransitionTime: "2022-11-18T07:22:58Z"
    status: "True"
    type: ReplicasReady
  infrastructureReady: true
  nodeRefs:
  - name: ip-10-50-109-198.eu-west-2.compute.internal
    uid: XXXXXXXX-04f3-XXXX-8a42-2532XXXXX344
  - name: ip-10-50-212-64.eu-west-2.compute.internal
    uid: 294XXXX83-fbc2-XXXX-97X5-e4XXXXXXd63
  - name: ip-10-50-172-220.eu-west-2.compute.internal
    uid: c8bXXXX9-XXXX-4XX8-82bb-eb16XXXX8f63
  observedGeneration: 3
  phase: Running
  readyReplicas: 3
  replicas: 3

```

</details>

<details>
<summary>AWSMachinePool</summary>

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachinePool
metadata:
  annotations:
    cluster-api-provider-aws: "true"
  creationTimestamp: "2022-11-18T07:13:50Z"
  finalizers:
  - awsmachinepool.infrastructure.cluster.x-k8s.io
  - capa-iam-operator.finalizers.giantswarm.io/nodes
  generation: 4
  labels:
    cluster.x-k8s.io/cluster-name: marc1
    cluster.x-k8s.io/watch-filter: capi
  name: marc1-machine-pool0
  namespace: org-giantswarm
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: MachinePool
    name: marc1-machine-pool0
    uid: 8f1e48d0-1fec-4df7-912c-f4297e5ff805
spec:
  availabilityZones:
  - eu-west-2b
  - eu-west-2c
  - eu-west-2a
  awsLaunchTemplate:
    ami: {}
    iamInstanceProfile: nodes-machine-pool0-marc1
    imageLookupBaseOS: ubuntu-22.04
    imageLookupFormat: capa-ami-{{.BaseOS}}-v{{.K8sVersion}}-gs
    imageLookupOrg: "706635527432"
    instanceType: m5.xlarge
    rootVolume:
      deviceName: /dev/sda1
      size: 300
      type: gp3
    sshKeyName: ""
  defaultCoolDown: 5m0s
  maxSize: 10
  minSize: 3
  mixedInstancesPolicy:
    instancesDistribution:
      onDemandAllocationStrategy: prioritized
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 100
      spotAllocationStrategy: lowest-price
  providerID: arn:aws:autoscaling:eu-west-2:XXXXXXX:autoScalingGroup:15bXXXXad-XXX-47d8-XXXX-33d0XXXX47b:autoScalingGroupName/marc1-machine-pool0
  providerIDList:
  - aws:///eu-west-2a/i-03cXXXXX9cc8247c5
  - aws:///eu-west-2c/i-0acXXXXbe35df2213
  - aws:///eu-west-2b/i-0f6982XXXX04b7ab8
  subnets:
  - filters:
    - name: tag:sigs.k8s.io/cluster-api-provider-aws/cluster/marc1
      values:
      - owned
    - name: tag:sigs.k8s.io/cluster-api-provider-aws/role
      values:
      - private
    - name: availabilityZone
      values:
      - eu-west-2b
      - eu-west-2c
      - eu-west-2a
status:
  conditions:
  - lastTransitionTime: "2022-11-18T07:19:54Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-11-18T07:19:54Z"
    status: "True"
    type: ASGReady
  - lastTransitionTime: "2022-11-18T07:19:52Z"
    status: "True"
    type: LaunchTemplateReady
  instances:
  - instanceID: i-03cXXXXX9cc8247c5
  - instanceID: i-0acXXXXbe35df2213
  - instanceID: i-0f6982XXXX04b7ab8
  launchTemplateID: lt-01c42f098fdd0c58f
  ready: true
  replicas: 3
```

</details>

After delete:

<details>
<summary>Cluster</summary>

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    cluster.giantswarm.io/description: marcus's test cluster
    network-topology.giantswarm.io/mode: GiantSwarmManaged
  creationTimestamp: "2022-11-18T07:13:50Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2022-11-18T07:28:57Z"
  finalizers:
  - cluster.cluster.x-k8s.io
  generation: 3
  labels:
    cluster.x-k8s.io/cluster-name: marc1
    cluster.x-k8s.io/watch-filter: capi
  name: marc1
  namespace: org-giantswarm
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 100.64.0.0/12
  controlPlaneEndpoint:
    host: marc1-apiserver-XXXXXXX.eu-west-2.elb.amazonaws.com
    port: 6443
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: marc1
    namespace: org-giantswarm
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSCluster
    name: marc1
    namespace: org-giantswarm
status:
  conditions:
  - lastTransitionTime: "2022-11-18T07:22:03Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-11-18T07:19:27Z"
    status: "True"
    type: ControlPlaneInitialized
  - lastTransitionTime: "2022-11-18T07:22:03Z"
    status: "True"
    type: ControlPlaneReady
  - lastTransitionTime: "2022-11-18T07:17:36Z"
    status: "True"
    type: InfrastructureReady
  - lastTransitionTime: "2022-11-18T07:13:57Z"
    status: "True"
    type: NetworkTopologyReady
  controlPlaneReady: true
  failureDomains:
    eu-west-2a:
      controlPlane: true
    eu-west-2b:
      controlPlane: true
    eu-west-2c:
      controlPlane: true
  infrastructureReady: true
  observedGeneration: 3
  phase: Deleting

```

</details>

<details>
<summary>MachinePool</summary>

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  annotations:
    machine-pool.giantswarm.io/name: marc1-machine-pool0
  creationTimestamp: "2022-11-18T07:13:50Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2022-11-18T07:28:57Z"
  finalizers:
  - machinepool.cluster.x-k8s.io
  labels:
    cluster.x-k8s.io/cluster-name: marc1
    cluster.x-k8s.io/watch-filter: capi
    giantswarm.io/machine-pool: marc1-machine-pool0
  name: marc1-machine-pool0
  namespace: org-giantswarm
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    kind: Cluster
    name: marc1
    uid: d13e583e-1713-419d-9b26-25ad0be2e8a3
spec:
  clusterName: marc1
  minReadySeconds: 0
  providerIDList:
  - aws:///eu-west-2a/i-03cXXXXX9cc8247c5
  - aws:///eu-west-2c/i-0acXXXXbe35df2213
  - aws:///eu-west-2b/i-0f6982XXXX04b7ab8
  replicas: 3
  template:
    metadata: {}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfig
          name: marc1-machine-pool0
          namespace: org-giantswarm
        dataSecretName: marc1-machine-pool0
      clusterName: marc1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachinePool
        name: marc1-machine-pool0
        namespace: org-giantswarm
      version: v1.23.13
status:
  availableReplicas: 3
  bootstrapReady: true
  conditions:
  - lastTransitionTime: "2022-11-18T07:22:58Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-11-18T07:19:52Z"
    status: "True"
    type: BootstrapReady
  - lastTransitionTime: "2022-11-18T07:19:54Z"
    status: "True"
    type: InfrastructureReady
  - lastTransitionTime: "2022-11-18T07:22:58Z"
    status: "True"
    type: ReplicasReady
  infrastructureReady: true
  nodeRefs:
  - name: ip-10-50-109-198.eu-west-2.compute.internal
    uid: XXXXXXXX-04f3-XXXX-8a42-2532XXXXX344
  - name: ip-10-50-212-64.eu-west-2.compute.internal
    uid: 294XXXX83-fbc2-XXXX-97X5-e4XXXXXXd63
  - name: ip-10-50-172-220.eu-west-2.compute.internal
    uid: c8bXXXX9-XXXX-4XX8-82bb-eb16XXXX8f63
  observedGeneration: 4
  phase: Deleting
  readyReplicas: 3
  replicas: 3

```

</details>

<details>
<summary>AWSMachinePool</summary>

```yaml
Error from server (NotFound): awsmachinepools.infrastructure.cluster.x-k8s.io "marc1-machine-pool0" not found
```

</details>
