### ISSUE TITLE
Creating partitions with Ignition bootstrap format fails when Ignition 3.1 is used.

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api#7679]
**What steps did you take and what happened:**

Following fragment of `KubeadmControlPlane` spec:

```yaml
...
    diskSetup:
      filesystems:
      - device: /dev/disk/azure/scsi1/lun0
        extraOpts:
        - -E
        - lazy_itable_init=1,lazy_journal_init=1
        filesystem: ext4
        label: etcd_disk
        overwrite: false
      partitions:
      - device: /dev/disk/azure/scsi1/lun0
        layout: true
        overwrite: false
```

Creates a following Ignition fragment:

```json
[
  {
    "device": "/dev/disk/azure/scsi1/lun0",
    "partitions": [
      {}
    ]
  }
]
```

Which with latest (3374.2.0) Flatcar stable, using Ignition 3.1, produces the following error which makes machine fail to boot:
```console
[    3.847409] ignition[548]: failed to fetch config: unable to translate 2.x ignition to 3.1: error at $.storage.disks.0.partitions.0: a partition number >= 1 or a label must be specified
[    3.853019] ignition[548]: failed to acquire config: unable to translate 2.x ignition to 3.1: error at $.storage.disks.0.partitions.0: a partition number >= 1 or a label must be specified
[    3.853914] systemd[1]: ignition-fetch.service: Main process exited, code=exited, status=1/FAILURE
[    3.854335] ignition[548]: Ignition failed: unable to translate 2.x ignition to 3.1: error at $.storage.disks.0.partitions.0: a partition number >= 1 or a label must be specified
[    3.854686] systemd[1]: ignition-fetch.service: Failed with result 'exit-code'.
```

**What did you expect to happen:**

Machine to boot successfully.

**Anything else you would like to add:**

While migrating to Ignition 3.1 natively would be the best thing to do,  I think we can just add a `number: N` for each partition we create, which should solve the issue.

As a workaround, one can apply `number: N` themselves using `ignition.containerLinuxConfig.additionalConfig` with fragment like this:
```yaml
          storage:
            disks:
            - device: /dev/disk/azure/scsi1/lun0
              partitions:
              - number: 1
            filesystems:
            - name: etcd_disk
              mount:
                device: /dev/disk/azure/scsi1/lun0
                format: ext4
                label: etcd_disk
                options:
                - -E
                - lazy_itable_init=1,lazy_journal_init=1
```

**Environment:**

- Cluster-api version: v1.3.0
- Kubernetes version: (use `kubectl version`): v1.23.13
- OS (e.g. from `/etc/os-release`): latest (3374.2.0) Flatcar stable

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by sbueringer** [comment]
Sounds okay to me

**Comment by primeroz** [comment]
I have been trying to use this snippet, actually from the example here https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/cluster-template-flatcar.yaml

the issue i am having is that the Disk is `properly formatted and labeled` but is not mounted 


```
➜ kubectl get kubeadmcontrolplane fctest1 -o json | jq .spec.kubeadmConfigSpec.ignition.containerLinuxConfig.additionalConfig -r 
systemd:
  units:
  - name: kubeadm.service
    dropins:
    - name: 10-flatcar.conf
      contents: |
        [Unit]
        After=oem-cloudinit.service
# Workaround for https://github.com/kubernetes-sigs/cluster-api/issues/7679.
storage:
  disks:
  - device: /dev/disk/azure/scsi1/lun0
    partitions:
    - number: 1
  filesystems:
  - name: etcd_disk
    mount:
      device: /dev/disk/azure/scsi1/lun0
      format: ext4
      label: etcd_disk
      path: /var/lib/etcddisk
      options:
      - -E
      - lazy_itable_init=1,lazy_journal_init=1
```

```
➜ kubectl view-secret fctest1-tf2lh value | jq -r .storage.filesystems                                                          
[
  {
    "mount": {
      "device": "/dev/disk/azure/scsi1/lun0",
      "format": "ext4",
      "label": "etcd_disk",
      "options": [
        "-E",
        "lazy_itable_init=1,lazy_journal_init=1"
      ]
    },
    "name": "etcd_disk"
  }
]
```

* Even with `mounts` section defined in the `KubeadmControlPlane` spec we get no mount unit because it actually need the `filesystems` section in the `diskSetup`  section to be defined as well but in the PR to CAPZ those sections are set to `[]` (https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/cluster-template-flatcar.yaml#L78) 
* adding a `path` to the `ignition` `storage.filesystems` does not seem to mount the disk or even render in the actual ignition 

should we define the disks both in the `spec.diskSetup` and in the `ignition.additionalConfig` ?

**Comment by primeroz** [comment]
Just to follow up, i was able to get around the issue reported here and also get the disks mounted by mixing the `.diskSetup` and `ignition.AdditionalConfig` like this 

* define the partition in `ignition.AdditionalConfig`
```
➜ kubectl get kubeadmcontrolplane fctest1 -o json | jq .spec.kubeadmConfigSpec.ignition.containerLinuxConfig.additionalConfig -r                                                                                   
                                                                                                                                                                                                                   
systemd:       
  units:   
  - name: kubeadm.service                      
    dropins:
    - name: 10-flatcar.conf                                                                                                                                                                                        
      contents: |                                                                                                                                                                                                  
        [Unit]
        After=oem-cloudinit.service
# Workaround for https://github.com/kubernetes-sigs/cluster-api/issues/7679.
storage:                                     
  disks:            
  - device: /dev/disk/azure/scsi1/lun0
    partitions:                                 
    - number: 1
```
* define `filesystems` and `mounts` in `kubeadmConfigSpec`
```
➜ kubectl get kubeadmcontrolplane fctest1 -o json | jq .spec.kubeadmConfigSpec.diskSetup                                         
{
  "filesystems": [
    {
      "device": "/dev/disk/azure/scsi1/lun0",
      "extraOpts": [
        "-E",
        "lazy_itable_init=1,lazy_journal_init=1"
      ],
      "filesystem": "ext4",
      "label": "etcd_disk",
      "overwrite": false
    }
  ]
}

➜ kubectl get kubeadmcontrolplane fctest1 -o json | jq .spec.kubeadmConfigSpec.mounts   
[
  [
    "etcd_disk",
    "/var/lib/etcddisk"
  ]
]
```

which renders to

```
➜ kubectl view-secret fctest1-cdqgf value | jq -r .storage.disks                                                 
[
  {
    "device": "/dev/disk/azure/scsi1/lun0",
    "partitions": [
      {
        "number": 1
      }
    ]
  }
]


➜ kubectl view-secret fctest1-cdqgf value | jq -r .storage.filesystems                                           
[
  {
    "mount": {
      "device": "/dev/disk/azure/scsi1/lun0",
      "format": "ext4",
      "label": "etcd_disk",
      "options": [
        "-E",
        "lazy_itable_init=1,lazy_journal_init=1"
      ]
    },
    "name": "etcd_disk"
  }
]


➜ kubectl view-secret fctest1-cdqgf value | jq -r '.systemd.units[] | select (.name == "var-lib-etcddisk.mount")'
{
  "contents": "[Unit]\nDescription = Mount etcd_disk\n\n[Mount]\nWhat=/dev/disk/azure/scsi1/lun0\nWhere=/var/lib/etcddisk\nOptions=\n\n[Install]\nWantedBy=multi-user.target\n",
  "enabled": true,
  "name": "var-lib-etcddisk.mount"
}
```

and on node

```
fctest1-control-plane-e95df458-9xvqn / # blkid | grep sda
/dev/sda: LABEL="etcd_disk" UUID="0d6a6b3e-00b9-4fd6-9e20-86cc2fd3cb90" BLOCK_SIZE="4096" TYPE="ext4"

fctest1-control-plane-e95df458-9xvqn / # df -h /var/lib/etcddisk/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda        9.8G  125M  9.2G   2% /var/lib/etcddisk

fctest1-control-plane-e95df458-9xvqn / # ls -la /var/lib/etcddisk/etcd/member/
total 16
drwx------. 4 root root 4096 Feb 22 08:41 .
drwx------. 3 root root 4096 Feb 22 08:41 ..
drwx------. 2 root root 4096 Feb 22 08:41 snap
drwx------. 2 root root 4096 Feb 22 08:41 wal
```

This is not very ideal though, i wonder if it would be better to define everything in `ignition.AdditionalConfig` and just set the `mount unit` there as well as a `file` unless we think the fix to actually use only `KubeadmConfigSpec` is doable ? 

What do you think ? 

( sorry for interjecting in this issue btw, i just really want to move away from ubuntu into flatcar :) )
