### ISSUE TITLE
ClusterClass jsonPatch array is being generated as a single string when valueFrom is template

### ISSUE THREAD

**Issue by nikParasyr** [kubernetes-sigs/cluster-api#7890]
Hello,

Thanks for all your work :) I have an issue with array being generated as single string when using jsonPatches and ClusterClass.
The steps below are a simplified reproduction case as the original I had is much more complex with a lot of extra noise.

**What steps did you take and what happened:**
I have this variable definition:
```
  - name: ntpServers
    schema:
      openAPIV3Schema:
        type: array
        items:
          type: string
```

The variable is set as:
```
ntpServers:
- 0.nl.pool.ntp.org
- 1.nl.pool.ntp.org
```

The jsonPatch looks like:

 ```
   - name: ntpServers
    description: "Set ntp servers"
    enabledIf: "{{ if .ntpServers }}true{{end}}"
    definitions:
    - selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true        
      jsonPatches:
      - op: replace
        path: "/spec/template/spec/kubeadmConfigSpec/ntp/servers"
        valueFrom:
          template: "{{ .ntpServers }}" 
```

The rendered template looks like this:
```
    ntp:
      servers:
      - 0.nl.pool.ntp.org 1.nl.pool.ntp.org
```
Basically it is rendered as a single string and not an array.

**What did you expect to happen:**
`ntpServers` should be rendered as an array and not a single string. So it should look like:
```
    ntp:
      servers:
      - 0.nl.pool.ntp.org 
      - 1.nl.pool.ntp.org
```

**Anything else you would like to add:**
- Using `variable` instead of `template` under `valueFrom` makes it work as expected. But in my actual case i use tempalte as im doing multiple changes in one go and it is not really handy to have a multitude of jsonPatches.
- This seems to me a bit related with #6245 which was not solved in favor of runtimeSDK. The limitations of that issue are being documented but this seems to be a bit more than just merging/appending arrays so it is outside of what is being documented.

**Environment:**

- Cluster-api version: 1.3.1
- minikube/kind version: 0.16.0
- Kubernetes version: (use `kubectl version`): unrelated
- OS (e.g. from `/etc/os-release`): unrelated

/kind bug
/area topology
