### ISSUE TITLE
Simplify external patch definition in ClusterClass

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api#8210]
When a user wants to include an external patch in a ClusterClass they have to specify the following in the ClusterClass `.spec`

```
  patches:
  - name: test-patch
    external:
      generateExtension: generate-patches.k8s-upgrade-with-runtimesdk
      validateExtension: validate-topology.k8s-upgrade-with-runtimesdk
      discoverVariablesExtension: discover-variables.k8s-upgrade-with-runtimesdk
```

This issue is about considering the following improvements to the API:

1. Change `generateExtension` and `validateExtension` to `generatePatchExtension` and `validatePatchExtension` respectively to make them consistent with `discoverVariablesExtension`

2. Allow users to specify an external patch using a single field. This would result in something like:
```
  patches:
  - name: test-patch
    external:
      extension: k8s-upgrade-with-runtimesdk
```
Where the three runtime hooks - generateExtension, validateExtension and  discoverVariablesExtension - can be inferred from the extension through the Runtime SDK discovery process.

/area topology
/area runtime-sdk
/kind api-change

**Comment by adam-jian-zhang** [comment]
@killianmuldoon , which release will this feature be implemented, 1.14 or future?
After this, do we support short version only, or both? This will impact design decisions for next version of TKG,

I am considering multiple hooks in the same ExtensionConfig, different endpoint for supporting different k8s  tkr version, something like,
```yaml
apiVersion: runtime.cluster.x-k8s.io/v1alpha1
kind: ExtensionConfig
metadata:
  name: tkg-runtimesdk-2.3
spec:
  clientConfig:
    caBundle: <...>
    service:
      name: tkg-extension-2.3-webhook-service
      namespace: extension-system
      port: 443
  settings:
    defaultAllHandlersToBlocking: "true"
```
```yaml
# For CC-<2.3, 1.25>
patches:
- name: tkg-patch
  external:
  generateExtension: generate-patches-1.25.tkg-runtimesdk-2.3 # version number in the hook definition
  validateExtension: validate-topology-1.25.tkg-runtimesdk-2.3
  discoverVariablesExtension: discover-variables-1.25.tkg-runtimesdk-2.3
```
```yaml
# For CC-<2.3, 1.26>
patches:
- name: tkg-patch
  external:
  generateExtension: generate-patches-1.26.tkg-runtimesdk-2.3 # version number in the hook definition
  validateExtension: validate-topology-1.26.tkg-runtimesdk-2.3
  discoverVariablesExtension: discover-variables-1.26.tkg-runtimesdk-2.3
```
What do you think? Or should I organize different k8s tkr in different service?
