### ISSUE TITLE
Managed Cluster Topology and cluster-autoscaler

### ISSUE THREAD

**Issue by MaxFedotov** [kubernetes-sigs/cluster-api#8217]
Hi @elmiko and @sbueringer.

Want to go back to this issue after https://github.com/kubernetes-sigs/cluster-api/pull/7990 was merged.
If I understand correctly, now it is possible to add a new `machineDeployment` to managed `Cluster` and specify `cluster-autoscaler` annotations in spec like:
```
    workers:
      machineDeployments:
      - class: default-worker
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "4"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "2"
        name: md-1
```
and defaulting webhook will set `replicas` field of created `machineDeployment` to a value specified in `cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size` annotation.

But if I will update this field, for example, set `cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "3"` in `Cluster` spec, defaulting webhook will not update `replicas` field, due to this [check](https://github.com/kubernetes-sigs/cluster-api/blob/6fede8c8cbc83e108aa6a5bc4507ed3aae096105/api/v1beta1/machinedeployment_webhook.go#L307-L311)
```
func calculateMachineDeploymentReplicas(ctx context.Context, oldMD *MachineDeployment, newMD *MachineDeployment, dryRun bool) (int32, error) {
	// If replicas is already set => Keep the current value.
	if newMD.Spec.Replicas != nil {
		return *newMD.Spec.Replicas, nil
	}
```
And this completely prevents an ability to use cluster-autoscaler annotations when using managed Cluster topologies and `machineDeployment` is already created. Because if `machineDeployments` are managed by `topology controller` and `workers .machineDeployments .[].metadata .annotations` are updated it generates a `Patch` which includes only updated fields. So a user doesn't have any ability to set `newMD.Spec.Replicas` to `nil` value.

Maybe it is possible to modify this check and exclude `machineDeployments` created by `topology controller` from it?

Thanks!

/kind feature
