### ISSUE TITLE
clusterctl move should pause all root hierachies

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#8388]
### What would you like to be added (User Story)?

As an operator I would like to move my objects without controllers taking actions during the operation

### Detailed Description

As of today clusterctl move pauses cluster and cluster class before moving so the corresponding controllers stops reconciling the objects being moved

The same should apply to all the other root hierarchies, like e.g. InClusterIPPool

### Anything else you would like to add?

This issue has been discovered while investigating https://github.com/kubernetes-sigs/cluster-api/issues/8384

### Label(s) to be applied

/kind feature
/area clusterctl

**Comment by srm09** [comment]
This would require us having to institute and update the contract so that IPPool implementations expose a `paused` field. The behavior of the implementation controllers should respect the value of this new field, similar to what the CAP* controllers do for  the `paused` filed of the `Cluster` object.

The above seems like a good idea but is a departure from the current way of implementing infra specific objects and having corresponding objects in CAPI, read `Cluster` and `VSphereCluster`, or `Machine` and `AWSMachine`. It might make sense to augment the IPAM proposal to bring in a `IPPool` object which refers to a concrete/provider specific implementation. Something like,
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: IPPool
metadata:
  name: system-pool
  namespace: default
spec:
  providerRef:
    apiVersion: ipam.cluster.x-k8s.io/v1alpha1
    kind: InClusterIPPool
    name: system-in-cluster-pool
```
This saves us from augmenting the contract and having to depend on the providers to implement this logic. It also means that we are following CAPI convention of keeping the provider specific logic separate and not being dependent on them. If we wanna also think about ClusterClass integration of IP pools, it'd follow the current convention and use an `IPPoolTemplate` object (although this one is not necessary a great advantage of this approach).
