### ISSUE TITLE
Clusterapi unable to describe vpc . 

### ISSUE THREAD

**Issue by defyjoy** [kubernetes-sigs/cluster-api#8445]
### What steps did you take and what happened?

I have tried to deploy EKS using cluster api - 

Here are are my configuration for bootstrap-config.yaml - 

```
apiVersion: bootstrap.aws.infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSIAMConfiguration
spec:
  eks:
    iamRoleCreation: false # Set to true if you plan to use the EKSEnableIAM feature flag to enable automatic creation of IAM roles
    managedMachinePool:
      disable: false # Set to false to enable creation of the default node role for managed machine pools
    fargate:
      disable: false # Set to false to enable creation of the default role for the fargate profiles
```

What I wanted was to deploy EKS on existing vpc with existing subnets ( private subnets ) and vpc with pod cidr association - `100.64.0.0/16`

Below is the configuration for EKS deployment - 

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi-eks-quickstart
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 100.64.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: capi-eks-quickstart-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: capi-eks-quickstart
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: capi-eks-quickstart
  namespace: default
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: capi-eks-quickstart-control-plane
  namespace: default
spec:
  # eksClusterName: eks-test
  secondaryCidrBlock: 100.64.0.0/16
  region: eu-west-1  
  associateOIDCProvider: true
  version: v1.25.0
  endpointAccess:
    public: false
    private: true
  network:
    vpc:
      id: vpc-<random number>
      cidrBlock: 10.10.0.0/16
    subnets:
    - id: subnet-<random number>
    - id: subnet-<random number>
    - id: subnet-<random number>
  vpcCni:
    disable: false
    env:
    - name: AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG
      value: "true" 
    - name: ENABLE_PREFIX_DELEGATION
      value: "true"
  addons:
  - name: vpc-cni
    version: v1.12.5-eksbuild.2
    conflictResolution: overwrite
  # sshKeyName: clusterapi
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: capi-eks-quickstart-pool-0
  namespace: default
spec:
  clusterName: capi-eks-quickstart
  replicas: 3
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: capi-eks-quickstart
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: capi-eks-quickstart-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: capi-eks-quickstart-pool-0
  namespace: default
spec: {}

```

But what I am seeing in the capa-controller -

```
[capa-controller-manager-7cb7c6dfc-lxbbg] I0403 02:00:32.504751       1 logger.go:68] "Reconciling AWSManagedControlPlane"
[capa-controller-manager-7cb7c6dfc-lxbbg] E0403 02:00:32.862625       1 controller.go:326] "Reconciler error" err=<
[capa-controller-manager-7cb7c6dfc-lxbbg] 	failed to reconcile network for AWSManagedControlPlane default/capi-eks-quickstart-control-plane: .spec.vpc.id is set but VPC resource is missing in AWS; failed to describe VPC resources. (might be in creation process): failed to query ec2 for VPCs: RequestExpired: Request has expired.
[capa-controller-manager-7cb7c6dfc-lxbbg] 		status code: 400, request id: c3594011-1c3f-4e10-b44e-63c75e78cb81
```

Here is the describe vpc returns - 

```
{
  "Vpcs": [
    {
      "CidrBlock": "10.10.0.0/16",
      "DhcpOptionsId": "dopt--<random number>",
      "State": "available",
      "VpcId": "vpc--<random number>",
      "OwnerId": "<random number>",
      "InstanceTenancy": "default",
      "CidrBlockAssociationSet": [
        {
          "AssociationId": "vpc-cidr-assoc-<random number>",
          "CidrBlock": "10.10.0.0/16",
          "CidrBlockState": {
            "State": "associated"
          }
        },
        {
          "AssociationId": "vpc-cidr-assoc-<random number>",
          "CidrBlock": "100.64.0.0/16",
          "CidrBlockState": {
            "State": "associated"
          }
        }
      ],
      "IsDefault": false     
    }   
  ]
}
```
So yes,  the vpc exists in the credentials through which the provider was created 

### What did you expect to happen?

I expect capa-controller to find and reconcile with the existing vpc. However I also checked the permission for the provider. It does have describe vpc permission. I am also rechecked multiple times the vpc exists in that account. 

### Cluster API version

```
registry.k8s.io/cluster-api-aws/cluster-api-aws-controller:v2.0.2
```

Above is the image I am using . Not sure how to get the cluster api version . Some help will be appreciated . 

### Kubernetes version

Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.1 ( Management Cluster ) 

EKS Version - v1.25.0

### Anything else you would like to add?

These is one thing I would like to add . When I tried this with fresh cluster api ( which creates the vpc and related resources ) it worked just fine . 

### Label(s) to be applied

/kind bug
/area/provider/aws
