### ISSUE TITLE
Provide a way to bootstrap declaratively

### ISSUE THREAD

**Issue by tjamet** [kubernetes-sigs/cluster-api#8456]
### What would you like to be added (User Story)?

As a cluster maintainer, I would like to deploy the cluster API declaratively using my standard git ops procedures.

### Detailed Description

Being a cluster maintainer, I store all my cluster definition as code.

Being an operator, I would expect the cluster API to be deployable using usual deployment strategies like helm or Kustomise.

This would allow me to store and manage the operator configuration as code, applying the standard code review mechanisms.

An example of it could be to use [argocd](https://argo-cd.readthedocs.io/en/stable) to maintain the cluster API deployments:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api
  namespace: bootstrap
spec:
  destination:
    server: https://kubernetes.default.svc
  project: cluster-api
  source:
    chart: cluster-api
    repoURL: https://cluster-api.sigs.k8s.io/charts
    targetRevision: v1.4.0
    helm:
      values: |
        infrastructure:
        - aws
        core: cluster-api:v1.1.5
```

### Label(s) to be applied

/kind feature
/area bootstrap
/area operator
