### ISSUE TITLE
[capd] Support for rootless docker

### ISSUE THREAD

**Issue by josecastillolema** [kubernetes-sigs/cluster-api#8494]
### What would you like to be added (User Story)?

Is there a way to run **capd** using rootless docker?
I am getting this error in the capd-system pod:
`failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error creating device nodes: mount /dev/bus/usb/002/003:/run/containerd/io.containerd.runtime.v2.task/k8s.io/7094ef726dcfe7972689f3071b13a7bbc1cbfe158b679f79167c85def8a111b4/rootfs/dev/bus/usb/002/003 (via /proc/self/fd/6), flags: 0x1000: no such file or directory: unknown`

Have tried updating the **dockersock** volume path but got the same result:
```
  - hostPath:
      path: /run/user/1000/docker.sock
      type: ""
    name: dockersock
```

### Detailed Description

Support for rootless docker on **capd**

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

**Comment by josecastillolema** [comment]
Updating the management kind cluster setup as follows did the trick:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mgmt
networking:
  apiServerAddress: "127.0.0.1"
nodes:
- role: control-plane
  image: docker.io/kindest/node:v1.23.6
  extraMounts:
    - hostPath: /run/user/1000/docker.sock
      containerPath: /var/run/docker.sock
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
```
