### ISSUE TITLE
Enable configuring docker for machine

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api#866]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Someone may want to use specified docker version, so it is better to enable end user can set some docker configurations.

/cc @vincepri @detiber 

FYI @jichenjc @xunpan @morvencao @clyang82

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by neolit123** [comment]
> When I was using kube 1.14.0, kubelet cannot start up due to following errors:

well it's not an error, just a warning. recommendation is here: https://kubernetes.io/docs/setup/cri/

> It is better to enable end user can configure docker cgroup driver in Machine Spec, comments?
> Besides, someone may also want to use specified docker version as well, so it is better to enable end user can set some docker configurations as well.

i'm leaning towards no, as i don't think the machine spec can/should handle container runtime specific flags.

**Comment by gyliu513** [comment]
@neolit123 @vincepri but any comments for how we can handle the docker that want to be used by customer?

For OpenStack provider, we are using `user-data` to install docker, but the problem is that the end user need to update `user-data` to specify the docker version which is not convenient.

**Comment by jichenjc** [comment]
also, it's not convenient to enable debug for kubeadm 

if we can have a cluster wide configuration (in cluster.yaml or not can be further discussed) to set debug level of kubeadm, to set docker version , docker format etc will be easier to configure

**Comment by vincepri** [comment]
@gyliu513 I'm not sure if that falls under the responsibilities for cluster-api. These concerns seem more appropriate for image stamping which is something that we haven't discussed in details yet  or could fall under machine configuration (open proposal) in some form of user-data as you mentioned.

Could we have some sort of automation (provider-specific) that lives outside of cluster-api to allow users to customize their own docker version?

@jichenjc That's something different from the issue's description. We've been talking about bringing kubeadm support upstream (with some sort of pluggable optional hook) in a next iteration, which would allow users to set kubeadm flags.

**Comment by detiber** [comment]
@vincepri yes and no. Currently CRI would fall both under image stamping and also bootstrapping (since the two need to align).

**Comment by derekwaynecarr** [comment]
i am actually surprised by this message as the default driver for the
kubelet is cgroupfs, and its only if the host os configures with systemd
should the kubelet use systemd.

its actually simpler in the long run if we can just have the kubelet detect
the right thing from the container runtime so it stops being a top-level
install choice.

**Comment by detiber** [comment]
@derekwaynecarr I'd love to see the kubelet handle this, it would make life a lot easier for downstream users.

**Comment by neolit123** [comment]
> i am actually surprised by this message as the default driver for the
kubelet is cgroupfs, and its only if the host os configures with systemd
should the kubelet use systemd.

the rational behind the message is here:
https://kubernetes.io/docs/setup/cri/#cgroup-drivers

> its actually simpler in the long run if we can just have the kubelet detect
the right thing from the container runtime so it stops being a top-level
install choice.

there is/was an ongoing effort on this front by a single developer (filbranden):

https://github.com/filbranden/kubernetes-community/blob/009f067c6bc106d062a416d0a1537de5ffa8c023/contributors/design-proposals/node/cgroup-driver-kubelet-and-runtime.md

**Comment by gyliu513** [comment]
My thinking is how about update `providerSpec` by adding some parameters to specify `docker config` etc? As far as I can see, I think both VM and docker should be treated at same level as `providerSpec`.

```
spec:
    providerSpec:
      value:
        apiVersion: "openstackproviderconfig/v1alpha1"
        kind: "OpenstackProviderSpec"
        flavor: m1.xlarge
        image: KVM-Ubt16.04-Srv-x64
        sshUserName: cloudusr
        keyName: cluster-api-provider-openstack
        availabilityZone: nova
        networks:
        - uuid: e2d9ead6-759b-4592-873d-981d3db07c86
        floatingIP: 9.20.206.22
        securityGroups:
        - uuid: 97acf9d4-e5bf-4fff-a2c0-be0b04fbc44b
        userDataSecret:
          name: master-user-data
          namespace: openstack-provider-system
        trunk: false
    versions:
      kubelet: 1.14.0
      controlPlane: 1.14.0
```

@derekwaynecarr so you mean that kubelet should detect docker cgroup driver and start with a driver same as docker?
