### ISSUE TITLE
CAPI 1.4.2 not allowing fields with null values

### ISSUE THREAD

**Issue by DimpleRajaVamsi** [kubernetes-sigs/cluster-api#8722]
### What steps did you take and what happened?

At present, we are using CAPI 1.2.8 and one of the variables filed (`kube-vip` in the `TKR_DATA` variable) was `null` and everything is working. While trying to upgrade the CAPI from 1.2.8 to 1.4.2 Cluster creation is not working on debugging found some issues with schema.

Before (working in CAPI 1.2.8)
```
    - name: TKR_DATA
      required: false
      schema:
        openAPIV3Schema:
          type: object
          additionalProperties:
            type: object
            properties:
              kubernetesSpec:
                type: object
                properties:
                  version:
                    type: string
                  imageRepository:
                    type: string
                  etcd:
                    type: object
                    properties:
                      imageTag:
                        type: string
                  coredns:
                    type: object
                    properties:
                      imageTag:
                        type: string
              osImageRef:
                type: object
                properties:
                  name:
                    type: string
              labels:
                type: object
                additionalProperties:
                  type: string
```

Update schema for 1.4.2 (Note: this is not actual schema present in the cluster)
```
    - name: TKR_DATA
      required: false
      schema:
        openAPIV3Schema:
          type: object
          additionalProperties:
            type: object
            properties:
              kubernetesSpec:
                type: object
                properties:
                  version:
                    type: string
                  imageRepository:
                    type: string
                  etcd:
                    type: object
                    properties:
                      imageTag:
                        type: string
                      imageRepository:
                        type: string
                  pause:
                    type: object
                    properties:
                      imageTag:
                        type: string
                      imageRepository:
                        type: string
                  coredns:
                    type: object
                    properties:
                      imageTag:
                        type: string
                      imageRepository:
                        type: string
                  kube-vip:
                    nullable: true
                    type: object
                    properties:
                      imageTag:
                        type: string
                      imageRepository:
                        type: string
              osImageRef:
                type: object
                properties:
                  name:
                    type: string
              labels:
                type: object
                additionalProperties:
                  type: string
```

After updating the clusterclass with the updated schema on the environment, tried creating the cluster but still it is failing with the below error
```
E0523 06:41:47.913410       1 controller.go:329] "Reconciler error" err="admission webhook \"default.cluster.cluster.x-k8s.io\" denied the request: Cluster.cluster.x-k8s.io \"tkc-01\" is invalid: spec.topology.variables.v1.25.7+vmware.2.kubernetesSpec.kube-vip: Invalid value: \"null\": .v1.25.7+vmware.2.kubernetesSpec.kube-vip in body must be of type object: \"null\"" controller="cluster" controllerGroup="cluster.x-k8s.io" controllerKind="Cluster" Cluster="test/tkc-01" namespace="test" name="tkc-01" reconcileID=0fec188c-4b76-4b7d-a3e6-4b7909a4a65a
```

I looked at the env and the `nullable` property from the `TKR_DATA` variable schema is not present.

### What did you expect to happen?

Cluster creation should work with the `TKR_DATA` variable having the `kube-vip` field as `null`.

### Cluster API version

1.4.2

### Kubernetes version

1.25.6

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
