### ISSUE TITLE
Failed to create v1alpha4 apiVersion of cluster object

### ISSUE THREAD

**Issue by JadeFlute0127** [kubernetes-sigs/cluster-api#8810]
### What steps did you take and what happened?

When I used the latest version (1.4.2) of clusterctl for init and then executed the `kubectl apply - f cluster-test-v1alpha4.yaml` , I attempted to create a v1alpha4 version of the cluster. However, after `kubectl describe cluster cluster-test-v1alpha4`, I found that the apiVersion was still v1beta1.

I want to test the v1alpha version of the cluster, but I obtained the v1beta1 version of the cluster by applying cluster-test-v1alpha4. yaml defined with v1alpha4 apiVersion.

following:
1. `kubectl apply - f cluster-test-v1alpha4.yaml`
```
# cluster-test-v1alpha4.yaml
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: test-v1alpha4
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks: [10.128.0.0/12]
    pods:
      cidrBlocks: [192.168.0.0/16]
    serviceDomain: cluster.local
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: DockerCluster
    name: test-v1alpha4
    namespace: default
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    name: test-v1alpha4-control-plane
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: DockerCluster
metadata:
  name: test-v1alpha4
  namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: DockerMachineTemplate
metadata:
  name: test-v1alpha4-control-plane
  namespace: default
spec:
  template:
    spec:
      extraMounts:
        - containerPath: "/var/run/docker.sock"
          hostPath: "/var/run/docker.sock"
---
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
metadata:
  name: test-v1alpha4-control-plane
  namespace: default
spec:
  replicas: 3
  machineTemplate:
    infrastructureRef:
      kind: DockerMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
      name: test-v1alpha4-control-plane
      namespace: default
  kubeadmConfigSpec:
    clusterConfiguration:
      controllerManager:
        extraArgs: {enable-hostpath-provisioner: 'true'}
      apiServer:
        certSANs: [localhost, 127.0.0.1, 0.0.0.0, 121.36.247.182, host.docker.internal]
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs: {eviction-hard: 'nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%'}
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs: {eviction-hard: 'nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%'}
  version: 1.23.6
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: DockerMachineTemplate
metadata:
  name: test-v1alpha4-md-0
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
kind: KubeadmConfigTemplate
metadata:
  name: test-v1alpha4-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs: {eviction-hard: 'nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%'}
---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: MachineDeployment
metadata:
  name: test-v1alpha4-md-0
spec:
  clusterName: test-v1alpha4
  replicas: 3
  selector:
    matchLabels:
  template:
    spec:
      clusterName: test-v1alpha4
      version:  1.23.6
      bootstrap:
        configRef:
          name: test-v1alpha4-md-0
          namespace: default
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: test-v1alpha4-md-0
        namespace: default
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: DockerMachineTemplate
```
2. `kubectl get clusters`
![image](https://github.com/kubernetes-sigs/cluster-api/assets/35321989/908fb19c-f557-4926-83db-6280db800548)

3. `kubectl describe cluster test-v1alpha4`
```
Name:         test-v1alpha4
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  cluster.x-k8s.io/v1beta1
Kind:         Cluster
Metadata:
  Creation Timestamp:  2023-06-07T09:10:16Z
  Finalizers:
    cluster.cluster.x-k8s.io
  Generation:  3
  Managed Fields:
    API Version:  cluster.x-k8s.io/v1alpha4
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:clusterNetwork:
          .:
          f:pods:
            .:
            f:cidrBlocks:
          f:serviceDomain:
          f:services:
            .:
            f:cidrBlocks:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-06-07T09:10:16Z
    API Version:  cluster.x-k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"cluster.cluster.x-k8s.io":
      f:spec:
        f:controlPlaneEndpoint:
          f:host:
          f:port:
        f:controlPlaneRef:
        f:infrastructureRef:
    Manager:      manager
    Operation:    Update
    Time:         2023-06-07T09:10:17Z
    API Version:  cluster.x-k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
        f:infrastructureReady:
        f:observedGeneration:
        f:phase:
    Manager:         manager
    Operation:       Update
    Subresource:     status
    Time:            2023-06-07T09:14:04Z
  Resource Version:  7704
  UID:               4e162cfb-24fe-4dc0-81a8-96317b092b82
Spec:
  Cluster Network:
    Pods:
      Cidr Blocks:
        192.168.0.0/16
    Service Domain:  cluster.local
    Services:
      Cidr Blocks:
        10.128.0.0/12
  Control Plane Endpoint:
    Host:  172.19.0.3
    Port:  6443
  Control Plane Ref:
    API Version:  controlplane.cluster.x-k8s.io/v1beta1
    Kind:         KubeadmControlPlane
    Name:         test-v1alpha4-control-plane
    Namespace:    default
  Infrastructure Ref:
    API Version:  infrastructure.cluster.x-k8s.io/v1beta1
    Kind:         DockerCluster
    Name:         test-v1alpha4
    Namespace:    default
Status:
  Conditions:
    Last Transition Time:  2023-06-07T09:14:04Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-06-07T09:10:53Z
    Status:                True
    Type:                  ControlPlaneInitialized
    Last Transition Time:  2023-06-07T09:14:04Z
    Status:                True
    Type:                  ControlPlaneReady
    Last Transition Time:  2023-06-07T09:10:17Z
    Status:                True
    Type:                  InfrastructureReady
  Control Plane Ready:     false
  Infrastructure Ready:    true
  Observed Generation:     3
  Phase:                   Provisioned
Events:
  Type    Reason               Age   From                Message
  ----    ------               ----  ----                -------
  Normal  Provisioning         14m   cluster-controller  Cluster test-v1alpha4 is Provisioning
  Normal  InfrastructureReady  14m   cluster-controller  Cluster test-v1alpha4 InfrastructureReady is now true
  Normal  Provisioned          14m   cluster-controller  Cluster test-v1alpha4 is Provisioned
```

### What did you expect to happen?

I want to test the v1alpha version of the cluster, but I obtained the v1base1 version of the cluster by applying cluster test v1alpha4. yaml defined with v1alpha4 apiVersion.

I expect the apiVersion of the cluster to be v1alpha4 instead of v1beta1

### Cluster API version

1.4.2

### Kubernetes version

v1.27.1

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
