### ISSUE TITLE
Fail to init with clusterctl v0.4.8

### ISSUE THREAD

**Issue by JadeFlute0127** [kubernetes-sigs/cluster-api#8823]
### What steps did you take and what happened?

When I used clusterctl to init through clusterctl. yaml, an error was reported as follows:

```
controlplane $ clusterctl init  --infrastructure docker -v5
Using configuration File="/root/.cluster-api/clusterctl.yaml"
Fetching providers
Fetching File="cluster-api-components.yaml" Provider="cluster-api" Type="CoreProvider" Version="v0.4.8"
Error: failed to get provider components for the "cluster-api" provider: failed to detect default target namespace: Invalid manifest. There should be no more than one resource with Kind Namespace in the provider components yaml
sigs.k8s.io/cluster-api/cmd/clusterctl/client.(*clusterctlClient).addToInstaller
        /workspace/cmd/clusterctl/client/init.go:265
sigs.k8s.io/cluster-api/cmd/clusterctl/client.(*clusterctlClient).setupInstaller
        /workspace/cmd/clusterctl/client/init.go:199
sigs.k8s.io/cluster-api/cmd/clusterctl/client.(*clusterctlClient).Init
        /workspace/cmd/clusterctl/client/init.go:101
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.runInit
        /workspace/cmd/clusterctl/cmd/init.go:148
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.glob..func12
        /workspace/cmd/clusterctl/cmd/init.go:87
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.Execute
        /workspace/cmd/clusterctl/cmd/root.go:93
main.main
        /workspace/cmd/clusterctl/main.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:225
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1371
```

```
# clusterctl.yaml
cert-manager:
  url: "https://github.com/cert-manager/cert-manager/releases/latest/cert-manager.yaml"
providers:
  # override a pre-defined provider
  - name: "cluster-api"
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/v0.4.8/cluster-api-components.yaml"
    type: "CoreProvider"
  - name: "infrastructure-docker"
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/v0.4.8/infrastructure-components-development.yaml"
    type: "InfrastructureProvider"
  - name: "bootstrap-kubeadm"
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/v0.4.8/bootstrap-components.yaml"
    type: "BootstrapProvider"
  - name: "control-plane-kubeadm"
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/v0.4.8/control-plane-components.yaml"
    type: "ControlPlaneProvider"
```

### What did you expect to happen?

No errors were reported and the cluster API can be installed normally

### Cluster API version

v0.4.8

### Kubernetes version

1.27.1

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
