### ISSUE TITLE
Set Kubernetes version in machinepool machine

### ISSUE THREAD

**Issue by shyamradhakrishnan** [kubernetes-sigs/cluster-api#9017]
### What would you like to be added (User Story)?

As an operator, I would like to see the Kubernetes version of machinepool machines.

### Detailed Description

Currently, machinepool machines does not show the Kubernetes version in the output. As an operator, I cannot make decisions to upgrade the machines based on this. During machinepool machine reconciliation, it would be great if the Kubernetes version of the node can bet set in machinepool machine.

### Label(s) to be applied

/kind feature
/area machinepool

**Comment by fabriziopandini** [comment]
/triage accepted
cc @Jont828

**Comment by Jont828** [comment]
That makes sense to me. Just to be clear, do you want to copy the field `MachinePool.Spec.Template.Spec.Version` to `Machine.Spec.Version`?

**Comment by sbueringer** [comment]
I think it's important that the version in Machine reflects the reality. If we just copy it over from MachinePool this is probably not the case. (Imagine the version in MachinePool is bumped, that doesn't mean that all MachinePool Machines suddenly have the new version)

**Comment by shyamradhakrishnan** [comment]
Agree with @sbueringer , I think we should set the version of node to the machine during reconciliation. In may cases, even in our case, in a single machine pool, it may happen that unless older nodes are deleted, there may be a mix of old and new nodes and it may be correct to show the version of actual nodes here.

**Comment by Jont828** [comment]
Right now, in the CAPD implementation, we can find the version in `Machine.status.nodeInfo`. Do you think we'd just want to copy it over to `spec.version` instead?

```
nodeInfo:
  architecture: amd64
  bootID: d9f43ab2-0f4a-4edb-bbe0-eb2a99086619
  containerRuntimeVersion: containerd://1.7.1
  kernelVersion: 5.15.79.1-microsoft-standard-WSL2
  kubeProxyVersion: v1.26.6
  kubeletVersion: v1.26.6
  machineID: 98f4fed0a17a4306bdd22e4bb106aece
  operatingSystem: linux
  osImage: Debian GNU/Linux 11 (bullseye)
  systemUUID: 98f4fed0a17a4306bdd22e4bb106aece
```
