### ISSUE TITLE
Cluster initialisation freezes when custom AMI is used

### ISSUE THREAD

**Issue by debjitk** [kubernetes-sigs/cluster-api#9022]
### What steps did you take and what happened?

When `AWSMachineTemplate` is provided with a custom `ami`, even those available through `clusterawsadm` the cluster creation freezes at `WaitingForKubeadmInit`

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
....
spec:
  template:
    spec:
      ami:
        id: ami-0c6f34a64f2ba7ea6
      instanceType: t3.medium
      ....
```

### What did you expect to happen?

Cluster to get provisioned properly

### Cluster API version

v1.4.4

### Kubernetes version

v1.27.3

### Anything else you would like to add?

The `ami` are either that are provided by the `aws` sig or built using `image-builder` 

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
