### ISSUE TITLE
Copy labels from provider to cluster

### ISSUE THREAD

**Issue by lknite** [kubernetes-sigs/cluster-api#9088]
### What would you like to be added (User Story)?

Am implementing the adding of clusters managed by cluster api into argocd, to make gitops work.

As part of this I would like to put labels on the provider yaml such as:
- addons-cert-manager
- addons-fluent-bit

Currently I am copying all labels from the cluster crd to argocd allowing me to manage addons using gitops.

However, it is preferred to put the addons labels on the provider yaml.  To add this to my controller though would require adding every provider crd.

If there were an option to copy all labels from the provider to the cluster this would be ideal, allowing my tool to work at the cluster level rather than provider.

### Detailed Description

Proposal:
Add annotation to cluster yaml which indicates to copy all labels from provider to cluster.

Something like:
cluster.x-k8s.io/copy-all-labels

Or, preferably we could add copying/syncing all labels from provider to cluster all the time.  Since, if it is not being used and there are no labels, no one will notice the feature exists, only those putting labels on their provider yamls might notice.

### Example
provider yaml:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  labels:
    addons-test: "true"
    addons-test_b: "true"
  name: vc-test
  namespace: vc-test
```
cluster yaml:
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    cluster.x-k8s.io/copy-all-labels
  labels:
    addons-test: "true"
    addons-test_b: "true"
```

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
