### ISSUE TITLE
Cannot create more than 1 replica of the `control-plane`

### ISSUE THREAD

**Issue by debjitk** [kubernetes-sigs/cluster-api#9102]
### Cannot create more than 1 replica of the `control plane`. Following are the outputs from different commands

Output from `clusterctl describe cluster dev-clustr`

```
NAME                                                           READY  SEVERITY  REASON     SINCE  MESSAGE
Cluster/dev-clustr                                             False  Warning   ScalingUp  6m     Scaling up control plane to 3 replicas (actual 1)
├─ClusterInfrastructure - AWSCluster/dev-clustr                True                        6m23s
└─ControlPlane - KubeadmControlPlane/dev-clustr-control-plane  False  Warning   ScalingUp  6m     Scaling up control plane to 3 replicas (actual 1)
  └─Machine/dev-clustr-control-plane-nbvfj                     True                        6m10s
```

Output from `kubectl get machines`

```
NAME                             CLUSTER      NODENAME   PROVIDERID                              PHASE         AGE   VERSION
dev-clustr-control-plane-nbvfj   dev-clustr              aws:///us-west-2a/i-0aee019602cfff1a9   Provisioned   10m   v1.27.3
```

Output from `kubectl get awsmachines`

```
NAME                             CLUSTER      STATE     READY   INSTANCEID                              MACHINE
dev-clustr-control-plane-ggsmv   dev-clustr   running   true    aws:///us-west-2a/i-0aee019602cfff1a9   dev-clustr-control-plane-nbvfj
```

Here is the simple configuration for the `control-plane`

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: dev-clustr
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 172.20.0.0/16
    services:
      cidrBlocks:
        - 172.18.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: dev-clustr-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSCluster
    name: dev-clustr
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: dev-clustr
  namespace: default
spec:
  region: us-west-2
  sshKeyName: host
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: dev-clustr-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
        name: "{{ ds.meta_data.local_hostname }}"
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
        name: "{{ ds.meta_data.local_hostname }}"
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSMachineTemplate
      name: dev-clustr-control-plane
  replicas: 3
  version: v1.27.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: dev-clustr-control-plane
  namespace: default
spec:
  template:
    spec:
      iamInstanceProfile: capi-control-plane
      instanceType: t3.medium
      sshKeyName: host
```

### What did you expect to happen?

Provision the cluster according to the provided configuration

### Cluster API version

v1.5.0

### Kubernetes version

v1.27.3

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
