### ISSUE TITLE
Inhibate cluster's CA certificates management capability

### ISSUE THREAD

**Issue by BarthV** [kubernetes-sigs/cluster-api#9168]
### What would you like to be added (User Story)?

As a cluster operator I would like to inhibate cluster-api ability to provision CA certificates used for managed cluster provisioning.

I want CAPI to strongly guarantee that it will never try to manage any of `***-ca `, `***-etcd`, `***-proxy` and `***-sa`  secrets.

### Detailed Description

When a new cluster is created, CAPI default behavior is to generate multiple CA certs for this cluster and store them in multiple kube secrets. These CA are independant and not signed by any root CA (this is ok, CAPI is not intended to support such feature).

If I want to generate these secrets using a third party mechanism (eg. using cert-manager), I'd like to avoid CAPI to generate these secret "by accident". I'd lke to inform CAPI to never create such certificates and completely skip the cert management code loop.

Currently there's 2 possible workaround, both of them have big drawbacks & I personally found them quite inelegant : 

1) Using [Cluster paused spec](https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api/cluster.x-k8s.io/Cluster/v1beta1@v1.5.0#spec-paused) to stop any reconciliation before certificates are generated.
  * The drawback of this workaround is that it requires a manual operation to unpause the Cluster resource after the certificates are generated. This orchestration mecanism must be done by a human or a third party automation tool/controller. It also breaks the asynchronous philosophy of kube resources...

2) Preprovision empty secrets for each expected CA certificate. Cert-manager (or any other provisioning mecanism) will just have to fill & overwrite these empty secrets. It's a valid solution because secrets will never be created by CAPI while failing controller with an error : 
```
unable to lookup or create cluster certificates" err="missing data for key tls.crt" controller="kubeadmcontrolplane"
```
  * While it's perfectly working, the drawback of this workaround is that we're not absolutely sure that CAPI will never manage these secrets. We're relying on an error, not a normal & valid tested behavior. So this workaround is not very reliable.
  
**--> I'd rather have a Cluster spec (or whatever KubeadmControlPlane spec) to ask CAPI to never ever write CA secrets with a strong guarantee**

Example:
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cluster-with-unmanaged-ca
spec:
  generateCAcerts: false
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.254.0.0/15
    services:
      cidrBlocks:
        - 10.253.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: my-control-planes
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KubevirtCluster
    name: my-workers
    namespace: default
```

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
