### ISSUE TITLE
Configurable namingStrategy for KCP, MD and MP in classy Clusters

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api#9323]
Some context:
* In clusters that are not using ClusterClass users can freely decide on how to name KCP, MD and MP objects.
* This allows users to follow naming conventions for KCP / MD / MS / Machine objects and eventually infrastructure resources
  * Note: In CAPI it is generally undefined how or if a Machine name maps to a specific infrastructure resource name. Some provider might guarantee a certain mapping or even use the Machine name directly for a server.
* With ClusterClass today we generate names as follows:
  * KCP:  `{cluster-name}-{random-suffix}`
  * MD: `{cluster-name}-{md-topology-name}-{random-suffix}`
  * MP: `{cluster-name}-{mp-topology-name}-{random-suffix}`

As a management cluster operator I would like to be able to configure how KCP, MD and MP objects are named in classy Clusters.

Note: This is also important to reach feature parity between classy and non-classy Clusters, so folks that have to follow naming conventions can start using ClusterClass.

### Proposal

The proposal is now basically to make the currently hard-coded name formats configurable.

Per default the behavior stays the same as today.
Additionally users can customize the names by providing a namingStrategy on the ClusterClass

Example:
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
spec:
  controlPlane:
    namingStrategy:
      name: "{{ .cluster.name }}-{{ .randomSuffix }}"
  workers:
    machineDeployments:
    - class: "default-worker"
      namingStrategy:
        name: "{{ .cluster.name }}-{{ .machineDeployment.topologyName }}-{{ .randomSuffix }}"
   # Same for MachinePools
```

Notes:
* the names are simple go templates
* they will get some data that can be used for rendering that should be ~ aligned to builtin variables for ClusterClass (although we only provide a very small subset of those variables as things like e.g. MD replicas or version don't make sense)
* Existing objects are not affected, we will only generate a name once per object on creation
* If we're getting close to the max name lengths we should follow the same pattern as the SimpleNameGenerator to ensur the last few characters are a random string.
* Required changes: ClusterClass API type, name calculation, e2e test coverage (just set namingStrategies in one of our test ClusterClasses)
* We would like to propose to cherry-pick this back into v1.5 (based on "Enhancements or additions to experimental Cluster API features" ([CONTRIBUTIN.md](https://github.com/kubernetes-sigs/cluster-api/blob/main/CONTRIBUTING.md))
