### ISSUE TITLE
reference clusterclass in specific namespace

### ISSUE THREAD

**Issue by MagnusRef** [kubernetes-sigs/cluster-api#9391]
### What would you like to be added (User Story)?

As a operator i would like to separate my cluster resources from my clusterclass. As it is right now you can only specify the name of the cluster class in spec.topology.class, but not what namespace it is in.

I think it is good to separate clusters and the clusterclasses and its associated resources for security and a more cleaner look.

### Detailed Description

Add in the possibility to reference class not only by name but also namespace.
eg.
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test-1
  namespace: test-clusters
spec:
  ...
  topology:
    className: capi-cc
    classNamespace: capi-classes
    version: v1.25.8
    ...
```

### Label(s) to be applied

/kind feature
/area clusterclass
