### ISSUE TITLE
Topology feature randomizes infrastructureTemplate name

### ISSUE THREAD

**Issue by cwrau** [kubernetes-sigs/cluster-api#9586]
### What steps did you take and what happened?

We have a cluster with a clusterclass and the necessary (OpenStack-)machine-templates. CAPI creates new machine-templates with these together with the patches and variables.

When we create a new machine-template, which is really different, and use this in the cluster the generated machine-template has a new name even though it is exactly the same.

Broken down example;

old machine-template:

```yaml
spec:
  template:
    spec:
      flavor: standard.2.1905
```

old clusterclass has no patch here.

new machine-template:

```yaml
spec:
  template:
    spec:
      flavor: compute-plane-placeholder
```

new clusterclass has the following patch:

```yaml
- op: add                            
  path: /spec/template/spec/flavor   
  valueFrom:                         
    variable: machineDeploymentFlavor
```

Both of these newly generated templates have the following spec;

```yaml
spec:
  template:
    spec:
      flavor: standard.2.1905
```

but different names, old: `infra-gwv52` new: `infra-ncjrw`

### What did you expect to happen?

I expected the name suffix of the generated machine-template to be a hash of it's spec, because otherwise the machines get rolled without any purpose.

### Cluster API version

v1.5.1

### Kubernetes version

v1.25.8

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
