### ISSUE TITLE
Missing support for "clusterctl.cluster.x-k8s.io/move" label since v1alpha4

### ISSUE THREAD

**Issue by Endevir** [kubernetes-sigs/cluster-api#9630]
### What steps did you take and what happened?

Hi!
I'm using custom Secret to provide credentials for OpenStack infrastructure provider.
Applied manifest like this (with `clusterctl.cluster.x-k8s.io/move: "true"` label, according to [docs](https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#move)):
```
apiVersion: v1
kind: Secret
metadata:
  name: capi-clouds-config-secret
  namespace: capi-management-cluster
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
data:
  cacert: $CACERT_BASE64
  clouds.yaml: $CLOUDS_YAML_BASE64
```

But during `clusterctl move --to-kubeconfig=kube.yaml --namespace capi-management-cluster --dry-run -v 10` 

I run into this line in logs: `Excluding secret from move (not linked with any Cluster) name="capi-clouds-config-secret"` and have  secret skipped (breaking provider reconciliation in target cluster).

### What did you expect to happen?

Secret with `clusterctl.cluster.x-k8s.io/move: "true"` label should also be moved into target cluster

### Cluster API version

1.5.3

### Kubernetes version

v1.27.6

### Anything else you would like to add?

Seems like tracking `clusterctl.cluster.x-k8s.io/move` label was dropped since v1alpha4 (API for [v1alpha3](https://github.com/kubernetes-sigs/cluster-api/blob/0eb51f07dcaf5c07cc7b04b9db3f4313f9c44dcf/cmd/clusterctl/api/v1alpha3/labels.go#L35C2-L35C22) still contains `ClusterctlMoveLabel` mentions).

However, label still is mentioned in docs: https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#move

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
