### ISSUE TITLE
simplify the cluster-api configuration

### ISSUE THREAD

**Issue by chenzhiwei** [kubernetes-sigs/cluster-api#971]
/kind feature

**Describe the solution you'd like**

Currently cluster-api accepts 3 yaml files, even there is a script to automatically generate them, it is still complex.

I propose to have a declarative configuration file, cluster-api convert it to the 3 yaml files internally.

For format can be something like:

```
apiVersion: cluster.k8s.io/v1alpha1
Kind: ClusterAPIConfiguration

auth:
    username: user
    password: pass
    url: https://example.com

clusters:
  - name: cluster1
     other: objects
     addons:
        - addons.yaml
```

The command to create cluster can simplify to: `clusterctl -c config.yaml create cluster`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
