### ISSUE TITLE
Cannot create IPAddressClaim due to webhook after introducing v1beta1

### ISSUE THREAD

**Issue by mcbenjemaa** [kubernetes-sigs/cluster-api#9882]
### What steps did you take and what happened?

I wanted to create an IPAddressClaim 

```
---
apiVersion: ipam.cluster.x-k8s.io/v1beta1
kind: IPAddressClaim
metadata:
  name: my-claim
spec:
  poolRef:
    apiGroup: ipam.cluster.x-k8s.io
    kind: InClusterIPPool
    name: inclusterippool-sample
```

But this failed, 

```
Error from server (InternalError): error when creating "examples/ipam/ip-addr-claim.yaml": Internal error occurred: failed calling webhook "validation.ipaddressclaim.ipam.cluster.x-k8s.io": failed to call webhook: the server could not find the requested resource
```

and neither `v1alpha1` works

### What did you expect to happen?

IPAddressClaim created

### Cluster API version

v1.6

### Kubernetes version

v1.28.4

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.
